// Brand information and summaries
export const brandInfo: Record<string, { summary: string; founded?: string; location?: string }> = {
  "Bambu Lab": {
    summary: "Bambu Lab is a revolutionary force in the 3D printing industry, founded in 2021 by a team of former DJI engineers in Shenzhen, China. The company emerged with a clear mission to make 3D printing accessible, reliable, and intelligent for both hobbyists and professionals. Their flagship product, the Bambu Lab X1 Carbon, quickly became a game-changer in the market, featuring advanced AI-powered features, multi-color printing capabilities, and exceptional print speeds.\n\nThe company's innovative approach integrates cutting-edge technology with user-friendly design, offering features like automatic calibration, remote monitoring through their mobile app, and a sophisticated ecosystem that includes their AMS (Automatic Material System) for seamless multi-color printing. Bambu Lab has achieved remarkable success by addressing long-standing pain points in desktop 3D printing, including reliability issues and complex setup procedures.\n\nTheir P1 and A1 series printers have expanded their product line to serve different market segments while maintaining their commitment to quality and innovation. The company has built a thriving community of users who appreciate their commitment to continuous software updates and feature improvements. Bambu Lab's success is evidenced by their rapid market penetration and strong customer loyalty, establishing them as a leading innovator in the consumer and professional 3D printing space within just a few years of operation.",
    location: "Shenzhen, China",
    founded: "2021"
  },
  "Overture": {
    summary: "Overture 3D is a prominent filament manufacturer based in China, dedicated to providing high-quality, affordable 3D printing materials to makers worldwide. The company has built its reputation on delivering consistent filament quality while maintaining competitive pricing, making 3D printing more accessible to hobbyists and professionals alike. Overture's flagship products include their popular PLA and PETG filament lines, which have garnered widespread acclaim for their excellent dimensional accuracy and consistent color quality.\n\nThe company operates with a customer-first philosophy, actively engaging with the 3D printing community to understand their needs and continuously improve their products. Their commitment to quality control is evident in their rigorous testing procedures, ensuring each spool meets exacting standards for diameter tolerance and material purity. Overture has achieved significant success in the competitive filament market by focusing on reliability and value, making them a favorite among budget-conscious makers who refuse to compromise on quality.\n\nThe company offers an extensive color palette across their product lines, enabling creative freedom for users. Their filaments are compatible with a wide range of 3D printers, demonstrating versatility that appeals to diverse user needs. Overture has also earned recognition for their excellent customer service and responsive support team. As they continue to expand their product offerings and global distribution network, Overture remains committed to democratizing 3D printing through affordable, high-quality materials.",
    location: "China",
    founded: "2017"
  },
  "Overture 3D": {
    summary: "Overture 3D is a prominent filament manufacturer based in China, dedicated to providing high-quality, affordable 3D printing materials to makers worldwide. The company has built its reputation on delivering consistent filament quality while maintaining competitive pricing, making 3D printing more accessible to hobbyists and professionals alike. Overture's flagship products include their popular PLA and PETG filament lines, which have garnered widespread acclaim for their excellent dimensional accuracy and consistent color quality.\n\nThe company operates with a customer-first philosophy, actively engaging with the 3D printing community to understand their needs and continuously improve their products. Their commitment to quality control is evident in their rigorous testing procedures, ensuring each spool meets exacting standards for diameter tolerance and material purity. Overture has achieved significant success in the competitive filament market by focusing on reliability and value, making them a favorite among budget-conscious makers who refuse to compromise on quality.\n\nThe company offers an extensive color palette across their product lines, enabling creative freedom for users. Their filaments are compatible with a wide range of 3D printers, demonstrating versatility that appeals to diverse user needs. Overture has also earned recognition for their excellent customer service and responsive support team. As they continue to expand their product offerings and global distribution network, Overture remains committed to democratizing 3D printing through affordable, high-quality materials.",
    location: "China",
    founded: "2017"
  },
  "3DXTech": {
    summary: "3DXTech is a leading American manufacturer of high-performance 3D printing filaments, headquartered in Grand Rapids, Michigan. Founded by engineers passionate about advancing additive manufacturing, the company has established itself as a premier supplier of specialty and engineering-grade filaments. Their roots in industrial manufacturing inform their approach to material development, resulting in filaments that meet demanding professional applications.\n\n3DXTech's flagship products include their CarbonX line of carbon fiber reinforced materials and FibreX composite filaments, which deliver exceptional strength-to-weight ratios for functional parts. The company has achieved notable success in serving industries including aerospace, automotive, and manufacturing, where material performance is critical. Their commitment to American manufacturing ensures consistent quality and supports local jobs.\n\n3DXTech invests heavily in research and development, continuously pushing the boundaries of what's possible with FDM printing. Their materials undergo rigorous testing to provide detailed technical data sheets, giving engineers confidence in part performance. The company also offers custom material development services, working with clients to create specialized formulations for unique applications. As additive manufacturing continues to evolve, 3DXTech remains at the forefront, developing next-generation materials that enable new possibilities.",
    location: "Grand Rapids, Michigan, USA",
    founded: "2014"
  },
  "Filamentum": {
    summary: "Filamentum is a prestigious European filament manufacturer based in the Czech Republic, renowned for their exceptional quality and vibrant color offerings. Founded with a vision to create premium 3D printing materials, the company has established itself as a leader in the European market and beyond. Filamentum's manufacturing facility in Hulín combines traditional European craftsmanship with modern production techniques, ensuring every spool meets exacting quality standards.\n\nTheir flagship Extrafill line showcases an extensive palette of precisely formulated colors, with exceptional consistency and finish quality that appeals to both professionals and enthusiasts. The company has achieved remarkable success by focusing on material science and color development, creating unique shades that stand out in the market. Filamentum's commitment to sustainability is evident in their environmentally conscious production practices and recyclable packaging.\n\nTheir Crystal Clear PLA has become particularly celebrated for its transparency and clarity, setting a benchmark in the industry. The company's technical materials line includes innovative formulations like their biodegradable Nylon and specialty composites that deliver professional-grade performance. Filamentum has earned numerous awards for their quality and innovation, establishing their reputation as a premium brand. As they continue to grow, Filamentum remains dedicated to pushing the boundaries of filament quality and color science.",
    location: "Czech Republic",
    founded: "2013"
  },
  "Amolen": {
    summary: "Amolen is an innovative 3D printing filament brand that has rapidly gained recognition for delivering quality materials at accessible price points. Based in China with global distribution, Amolen has built a strong presence in the maker community through their commitment to consistency and value. The company's founders recognized the need for reliable, affordable filaments that don't compromise on performance, and this vision drives their product development.\n\nAmolen's flagship PLA and PETG lines have earned praise for their excellent dimensional accuracy and smooth printing characteristics. The company has achieved impressive growth by focusing on customer satisfaction and responsive service, building a loyal following among hobbyists and small businesses. Their color selection includes both standard and specialty options, providing creative flexibility for diverse projects.\n\nAmolen invests in quality control systems that ensure consistent diameter tolerances and material purity across all spools. The company has successfully positioned itself in the competitive mid-range market segment, offering premium quality at moderate prices. Their packaging includes vacuum-sealed bags with desiccant, demonstrating attention to material preservation. Amolen actively engages with the 3D printing community through social media and customer forums, gathering feedback to refine their offerings.",
    location: "China"
  },
  "FormFutura": {
    summary: "FormFutura is a distinguished Dutch filament manufacturer that has earned international recognition for their premium materials and innovative formulations. Founded in Nijmegen, Netherlands, the company represents the best of European engineering and quality standards. FormFutura's roots lie in a deep passion for 3D printing and material science, driving them to develop some of the most advanced filaments available.\n\nTheir flagship EasyFil line showcases their expertise in creating user-friendly materials that deliver professional results without complicated settings. The company has achieved remarkable success with specialty materials, including their ReForm recycled filaments and innovative Galaxy PLA with stunning visual effects. FormFutura's commitment to sustainability sets them apart, with several product lines incorporating recycled materials without compromising performance.\n\nTheir HDglass line has become particularly renowned for delivering crystal-clear prints with excellent mechanical properties. The company maintains rigorous quality control throughout their production process, ensuring consistent diameter and material properties. FormFutura provides comprehensive technical support and detailed printing guidelines, empowering users to achieve optimal results. They continue to innovate, regularly introducing new materials that address evolving market needs while maintaining their commitment to European quality standards.",
    location: "Nijmegen, Netherlands",
    founded: "2012"
  },
  "Taulman3D": {
    summary: "Taulman3D is a pioneering American manufacturer specializing in engineering-grade nylon filaments, based in Missouri, USA. Founded by materials expert Taulman, the company has become synonymous with high-performance nylon materials for 3D printing. Their deep roots in material science and polymer chemistry have positioned them as industry leaders in developing advanced filament formulations.\n\nTaulman3D's flagship product, the iconic Nylon 618, revolutionized desktop 3D printing by bringing industrial-grade nylon to consumer machines. The company has achieved legendary status among makers and professionals who require exceptional strength, flexibility, and durability in their prints. Their extensive nylon portfolio includes specialized formulations for different applications, from the clear Nylon 230 to the bridge-building capable Alloy 910.\n\nTaulman3D's commitment to American manufacturing ensures consistent quality and supports domestic production. Their technical expertise is unmatched, with detailed material specifications and printing guidance that help users achieve success with challenging materials. The company actively collaborates with the maker community, taking feedback seriously and continuously refining formulations. Taulman3D continues to push boundaries in polymer development, exploring new formulations that expand what's possible with FDM technology.",
    location: "Missouri, USA"
  },
  "Ultimaker": {
    summary: "Ultimaker is a globally renowned 3D printing company headquartered in Utrecht, Netherlands, with offices across Europe and the United States. Founded in 2011 by Martijn Elserman, Erik de Bruijn, and Siert Wijnia, the company emerged from the open-source RepRap community with a vision to make professional 3D printing accessible. Ultimaker's flagship products include their industry-leading Ultimaker S-series and Method series printers, which have set benchmarks for reliability and print quality in professional environments.\n\nThe company has achieved extraordinary success in the enterprise and education sectors, with their printers deployed in thousands of businesses, schools, and design studios worldwide. Ultimaker's comprehensive ecosystem includes not only exceptional hardware but also their own line of premium filaments engineered specifically for optimal performance with their printers. Their materials portfolio spans standard thermoplastics to advanced engineering materials, all manufactured to strict quality standards.\n\nThe company revolutionized workflow with Ultimaker Cura, their free, open-source slicing software that has become the industry standard, used by millions globally. Ultimaker's commitment to the open-source community continues through their active development and sharing of innovations. The company's dedication to reliability has made their printers the choice for mission-critical applications across industries. Ultimaker continues to innovate with advanced features like their Material Station and Air Manager, enhancing the professional printing experience.",
    location: "Utrecht, Netherlands",
    founded: "2011"
  },
  "Siraya Tech": {
    summary: "Siraya Tech is an innovative manufacturer specializing in high-performance resin materials for SLA and DLP 3D printing, with operations based in California and manufacturing in Asia. The company was founded by materials scientists dedicated to advancing resin printing technology and making professional-grade materials accessible to makers. Siraya Tech's flagship products include their acclaimed Fast, Blu, and Tenacious resins, which have become favorites among resin printing enthusiasts for their excellent mechanical properties and printability.\n\nThe company has achieved rapid success by focusing on formulation chemistry that delivers superior toughness and reduced brittleness compared to standard resins. Their Tenacious resin, in particular, has become legendary in the community for its flexibility and impact resistance, perfect for functional parts. Siraya Tech's commitment to innovation is evident in their diverse product line, which includes specialized resins for different applications from miniatures to engineering prototypes.\n\nThe company actively engages with the resin printing community, gathering feedback and continuously refining formulations. Their success is built on transparency, providing detailed technical data and responsive customer support. Siraya Tech's resins work seamlessly across various resin printer brands, demonstrating universal compatibility. Their water-washable options have also gained popularity for simplifying post-processing workflows. As resin printing continues to grow, Siraya Tech remains at the forefront, developing innovative materials that expand creative and functional possibilities.",
    location: "California, USA"
  },
  "NinjaTek": {
    summary: "NinjaTek is a premier American manufacturer specializing in flexible and engineering-grade filaments, based in Manheim, Pennsylvania. Founded by materials engineers passionate about expanding the possibilities of 3D printing, the company has become synonymous with high-quality flexible filaments. NinjaTek's flagship product, NinjaFlex, revolutionized desktop 3D printing by making reliable flexible filament printing accessible to consumer machines.\n\nThe company has achieved remarkable success by focusing on TPU and TPE materials that deliver exceptional flexibility, durability, and printability. Their proprietary formulations undergo extensive testing to ensure consistent performance across various printer platforms. NinjaTek's product line has expanded to include Cheetah, a faster-printing flexible filament, and Armadillo, an engineering TPU with outstanding abrasion resistance.\n\nTheir success is built on deep technical expertise and close collaboration with the maker community. NinjaTek provides comprehensive printing guides and technical support, helping users achieve success with flexible materials. The company's materials have enabled countless innovative projects, from custom grips to impact-resistant cases. NinjaTek continues to innovate, developing new formulations that push the boundaries of flexible filament performance, earning them the status of gold standard for flexible printing.",
    location: "Manheim, Pennsylvania, USA"
  },
  "eSun": {
    summary: "eSun is a major Chinese filament manufacturer and pioneer in the 3D printing materials industry, headquartered in Shenzhen. Founded in 2002, the company has over two decades of experience in polymer materials and has grown into one of the world's largest producers of 3D printing filaments. eSun's extensive product portfolio includes their popular PLA+, ABS+, and PETG lines, which have earned global recognition for consistent quality at competitive prices.\n\nThe company operates state-of-the-art manufacturing facilities with rigorous quality control systems, ensuring dimensional accuracy and material purity. Their flagship ePLA and ePLA-ST lines showcase their expertise in PLA formulation, delivering enhanced mechanical properties and beautiful finish quality. eSun has achieved remarkable success through innovation and scale, serving both consumer and industrial markets worldwide.\n\nThe company's commitment to research and development has resulted in numerous specialty materials, including their popular silk PLA series with stunning sheen effects. Their biodegradable and eco-friendly material options demonstrate environmental consciousness while maintaining performance standards. eSun's success is evidenced by their global distribution network spanning over 200 countries and regions. The company continues to invest in advanced manufacturing technology and material science, developing next-generation filaments for emerging applications.",
    location: "Shenzhen, China",
    founded: "2002"
  },
  "ColorFabb": {
    summary: "ColorFabb is a prestigious Dutch filament manufacturer renowned for their innovative materials and exceptional quality standards. Based in the Netherlands, the company was founded by materials enthusiasts dedicated to creating unique and high-performance 3D printing filaments. ColorFabb's roots in European manufacturing excellence are evident in their meticulous attention to detail and consistent quality.\n\nTheir flagship products include the innovative woodFill, metalFill, and nGen lines, which have set new standards for specialty filaments. The company achieved breakthrough success with their composite filaments that incorporate real wood, copper, and bronze particles, creating prints with authentic appearance and feel. ColorFabb's nGen filament represents their commitment to developing next-generation copolyesters with superior toughness and chemical resistance.\n\nThe company collaborates closely with material suppliers and the 3D printing community to develop innovative formulations. ColorFabb's materials are manufactured with precise diameter tolerances and undergo extensive testing for consistency. Their commitment to innovation continues with regular releases of new materials that expand creative possibilities. As they grow, ColorFabb remains dedicated to their founding principles of quality, innovation, and exceptional customer service.",
    location: "Netherlands",
    founded: "2013"
  },
  "Matter3D": {
    summary: "Matter3D is an emerging filament manufacturer committed to delivering quality 3D printing materials with a focus on consistency and value. The company has established itself by understanding the needs of both hobbyist and professional users, developing materials that perform reliably across various applications. Matter3D's product line emphasizes practical materials that deliver dependable results, making them a trusted choice for everyday printing needs.\n\nTheir flagship PLA and PETG offerings have gained recognition for excellent layer adhesion and smooth surface finish. The company operates with a customer-centric philosophy, actively seeking feedback to refine their formulations and expand their product range. Matter3D has achieved growing success by balancing quality and affordability, making professional-grade materials accessible to a broader audience.\n\nTheir commitment to quality control ensures consistent diameter tolerances and material properties throughout every spool. The company's packaging includes proper moisture protection, demonstrating attention to material preservation and customer success. Matter3D provides clear printing guidelines and responsive customer support, helping users achieve optimal results. The company continues to expand their material portfolio based on community needs and emerging applications.",
    location: "USA"
  },
  "Prusament": {
    summary: "Prusament is the premium filament brand from Prusa Research, the renowned Czech 3D printer manufacturer founded by Josef Průša. Manufactured in Prague, Czech Republic, Prusament represents the company's commitment to producing the finest quality filaments to complement their industry-leading printers. Josef Průša's vision for Prusament was to create filaments with unprecedented consistency and quality control, setting new industry standards.\n\nThe company invested in custom-designed extrusion lines with advanced monitoring systems that measure diameter 50 times per second, ensuring exceptional precision. Prusament's flagship PLA and PETG lines have become benchmarks for quality, with diameter tolerances of ±0.02mm, significantly tighter than industry standards. Prusa Research's deep roots in the open-source 3D printing community inform their approach to material development and transparency.\n\nThe company has achieved remarkable success by vertical integration, controlling every aspect from raw material selection to final packaging. Prusament materials undergo rigorous testing with detailed specifications published for every batch, providing users with confidence and traceability. Their commitment to sustainability is evident in their cardboard spool options and recyclable packaging. The brand has earned global recognition and numerous industry awards for quality and innovation.",
    location: "Prague, Czech Republic",
    founded: "2019"
  },
  "SUNLU": {
    summary: "SUNLU is a prominent Chinese 3D printing materials manufacturer that has gained significant international recognition for their quality filaments and competitive pricing. Based in China with global distribution, SUNLU has built a strong presence across consumer and professional markets. The company was founded with a mission to make 3D printing accessible through reliable, affordable materials without compromising on performance.\n\nSUNLU's flagship PLA and PETG lines have earned widespread acclaim for their excellent dimensional accuracy and consistent printing characteristics. The company has achieved impressive growth by focusing on customer satisfaction and maintaining strict quality control throughout their manufacturing process. Their extensive product catalog includes a diverse range of materials from basic PLA to specialty filaments like silk, matte, and metallic variants.\n\nSUNLU operates modern manufacturing facilities equipped with advanced extrusion equipment and quality testing systems. The company's success is reflected in their strong presence on major retail platforms and growing international distribution network. SUNLU provides excellent value with vacuum-sealed packaging and included desiccant for optimal material preservation. The company actively engages with the global 3D printing community, gathering feedback to improve their products.",
    location: "China"
  },
  "Sunlu": {
    summary: "SUNLU is a prominent Chinese 3D printing materials manufacturer that has gained significant international recognition for their quality filaments and competitive pricing. Based in China with global distribution, SUNLU has built a strong presence across consumer and professional markets. The company was founded with a mission to make 3D printing accessible through reliable, affordable materials without compromising on performance.\n\nSUNLU's flagship PLA and PETG lines have earned widespread acclaim for their excellent dimensional accuracy and consistent printing characteristics. The company has achieved impressive growth by focusing on customer satisfaction and maintaining strict quality control throughout their manufacturing process. Their extensive product catalog includes a diverse range of materials from basic PLA to specialty filaments like silk, matte, and metallic variants.\n\nSUNLU operates modern manufacturing facilities equipped with advanced extrusion equipment and quality testing systems. The company's success is reflected in their strong presence on major retail platforms and growing international distribution network. SUNLU provides excellent value with vacuum-sealed packaging and included desiccant for optimal material preservation. The company actively engages with the global 3D printing community, gathering feedback to improve their products.",
    location: "China"
  },
  "HATCHBOX": {
    summary: "HATCHBOX is a widely recognized American filament brand that has become a favorite among 3D printing enthusiasts for their reliable quality and excellent value proposition. Based in the United States, HATCHBOX has built a strong reputation through consistent performance and customer satisfaction. The company was founded with a clear focus on delivering dependable filaments that work well across various printer platforms without requiring extensive tuning.\n\nHATCHBOX's flagship PLA and ABS lines have earned legendary status in the maker community for their ease of use and consistent results. The company has achieved remarkable success by maintaining strict quality control while keeping prices accessible to hobbyists and professionals alike. Their signature bright orange spools have become iconic in the 3D printing community, instantly recognizable on maker workbenches worldwide.\n\nHATCHBOX's commitment to consistency is evident in their tight diameter tolerances and reliable material properties batch after batch. The company offers an extensive color palette, providing creative flexibility for diverse projects from functional prototypes to artistic creations. Their materials have been extensively tested by the community, with countless successful prints validating their reliability. HATCHBOX continues to expand their material offerings based on community needs while maintaining their core commitment to quality, reliability, and value.",
    location: "USA"
  },
  "Hatchbox": {
    summary: "HATCHBOX is a widely recognized American filament brand that has become a favorite among 3D printing enthusiasts for their reliable quality and excellent value proposition. Based in the United States, HATCHBOX has built a strong reputation through consistent performance and customer satisfaction. The company was founded with a clear focus on delivering dependable filaments that work well across various printer platforms without requiring extensive tuning.\n\nHATCHBOX's flagship PLA and ABS lines have earned legendary status in the maker community for their ease of use and consistent results. The company has achieved remarkable success by maintaining strict quality control while keeping prices accessible to hobbyists and professionals alike. Their signature bright orange spools have become iconic in the 3D printing community, instantly recognizable on maker workbenches worldwide.\n\nHATCHBOX's commitment to consistency is evident in their tight diameter tolerances and reliable material properties batch after batch. The company offers an extensive color palette, providing creative flexibility for diverse projects from functional prototypes to artistic creations. Their materials have been extensively tested by the community, with countless successful prints validating their reliability. HATCHBOX continues to expand their material offerings based on community needs while maintaining their core commitment to quality, reliability, and value.",
    location: "USA"
  },
  "GreenGate3D": {
    summary: "GreenGate3D is an innovative American filament manufacturer based in Colorado, dedicated to producing high-quality materials with an emphasis on environmental sustainability. The company was founded by 3D printing enthusiasts who recognized the need for eco-conscious materials without compromising on performance. GreenGate3D's commitment to sustainability is woven into every aspect of their operation, from material sourcing to packaging choices.\n\nTheir flagship products focus on biodegradable and recycled materials that deliver professional-grade results while minimizing environmental impact. The company has achieved notable success by appealing to environmentally conscious makers who value both quality and sustainability. GreenGate3D's materials are manufactured with careful attention to diameter consistency and material purity, ensuring reliable printing performance.\n\nThe company's roots in the Colorado maker community inform their hands-on approach to product development and customer relationships. GreenGate3D provides detailed technical specifications and printing profiles to help users achieve optimal results. They actively participate in the maker community, attending events and engaging directly with customers. The company continues to research and develop new sustainable material formulations that expand possibilities for eco-friendly 3D printing.",
    location: "Colorado, USA"
  },
  "MatterHackers": {
    summary: "MatterHackers is a leading American 3D printing company headquartered in Lake Forest, California, serving as both a comprehensive retailer and materials manufacturer. Founded in 2013 by passionate makers, the company has grown into one of North America's most trusted sources for 3D printing supplies and expertise. MatterHackers' in-house filament brand offers carefully formulated materials developed through extensive testing and community feedback.\n\nTheir flagship PRO Series filaments deliver professional-grade performance for demanding applications, while their MH Build series provides reliable quality for everyday printing. The company has achieved remarkable success by combining their retail expertise with direct material manufacturing, ensuring they understand customer needs intimately. MatterHackers' roots in the maker community are evident in their commitment to education, offering extensive resources, tutorials, and technical guides.\n\nTheir success extends beyond materials to include exceptional customer service, with knowledgeable support staff helping users solve printing challenges. The company operates a sophisticated quality control system, ensuring their filaments meet strict standards for diameter tolerance and material consistency. MatterHackers has built a thriving community through their platform, connecting makers and sharing knowledge. The company continues to expand their product line based on real-world application needs and customer feedback.",
    location: "Lake Forest, California, USA",
    founded: "2013"
  },
  "Printed Solid": {
    summary: "Printed Solid is a dedicated 3D printing materials supplier and manufacturer based in the United States, focused on serving the maker community with quality filaments and exceptional service. The company was founded by 3D printing enthusiasts who understood the importance of reliable materials for successful printing outcomes. Printed Solid has built their reputation through careful material selection and rigorous quality standards.\n\nTheir product line includes both proprietary formulations and carefully curated materials from trusted manufacturers. The company's flagship Jessie line of premium filaments showcases their commitment to delivering exceptional quality and unique color offerings. Printed Solid has achieved success by combining material expertise with hands-on customer support from experienced 3D printing practitioners.\n\nThe company operates with a philosophy that every detail matters, from material formulation to packaging and presentation. Printed Solid's commitment to quality control ensures consistent performance across their entire product range. Their carefully selected color palette includes both classic and unique options that appeal to creative makers. The company continues to expand their offerings while maintaining their core values of quality, community, and customer service.",
    location: "USA"
  },
  "Atomic Filament": {
    summary: "Atomic Filament is a premium American filament manufacturer based in Cincinnati, Ohio, renowned for their exceptional quality and unique color formulations. Founded by materials enthusiasts dedicated to advancing 3D printing, the company has established itself as a leader in premium filaments. Atomic Filament's roots in American manufacturing are evident in their commitment to local production and strict quality control.\n\nTheir flagship products showcase stunning color depth and consistency, with proprietary formulations that deliver outstanding results. The company has achieved remarkable success by focusing on the high-end segment, offering materials that justify their premium positioning through superior performance. Atomic Filament's unique color offerings, including their popular metallic and carbon fiber enhanced materials, have earned them a devoted following among makers who demand the best.\n\nThe company's commitment to American manufacturing ensures every spool meets exacting standards while supporting domestic production. Atomic Filament provides comprehensive technical data and responsive customer support, helping users achieve exceptional results. Their dedication to innovation drives continuous development of new colors and material formulations. The company's reputation for quality has made them a preferred choice for makers who refuse to compromise on material performance and appearance.",
    location: "Cincinnati, Ohio, USA"
  },
  "QIDI": {
    summary: "QIDI Tech is a prominent Chinese manufacturer of 3D printers and materials, headquartered in Ruian City, Zhejiang Province. Founded in 2014, the company has grown into a significant player in the global 3D printing market, known for reliable equipment and quality materials. QIDI's engineering team brings extensive experience in precision manufacturing and automation technology.\n\nTheir flagship printers, including the X-series and i-series, have earned international recognition for build quality and reliability. The company has achieved impressive success by focusing on enclosed printer designs that enable printing of engineering materials like ABS and nylon with excellent results. QIDI's vertical integration extends to their filament production, ensuring optimal compatibility between their printers and materials.\n\nTheir commitment to quality control is evident throughout their manufacturing process, from raw materials to finished products. The company's success is reflected in their growing global presence, with products sold in over 50 countries. QIDI provides comprehensive customer support and continuously updates their products based on user feedback. As they continue to innovate, QIDI remains committed to delivering quality products that empower makers to bring their ideas to life with confidence.",
    location: "Ruian City, Zhejiang Province, China",
    founded: "2014"
  },
  "Phaetus": {
    summary: "Phaetus is an innovative Chinese manufacturer specializing in high-performance 3D printing hotends, extruders, and materials, based in Shenzhen. Founded by engineers passionate about pushing the boundaries of FDM technology, the company has become renowned for developing cutting-edge components that enhance printing capabilities. Phaetus's flagship products include the Dragon hotend series and Dragonfly hotend, which have set new standards for heat dissipation efficiency and high-temperature printing.\n\nThe company has achieved remarkable success through innovation, developing proprietary technologies that enable faster printing speeds and improved temperature control. Their Rapido high-flow hotend has become particularly celebrated for enabling unprecedented print speeds without sacrificing quality. Phaetus's commitment to research and development is evident in their continuous release of advanced products that address real-world printing challenges.\n\nThe company's success extends beyond hardware to include their line of premium filaments engineered specifically for high-performance printing. Their materials are formulated to complement their hotend technology, enabling users to fully utilize their equipment's capabilities. Phaetus actively engages with the 3D printing community, incorporating feedback into product development. As they continue to innovate, Phaetus remains dedicated to advancing additive manufacturing technology through engineering excellence.",
    location: "Shenzhen, China"
  },
  "Gizmo Dorks": {
    summary: "Gizmo Dorks is an enthusiastic American filament and 3D printing supplies brand serving the maker community with quality materials and accessories. Based in the United States, the company was founded by makers for makers, with a deep understanding of what the community needs for successful 3D printing. Gizmo Dorks has built their reputation by offering reliable filaments at accessible price points, making quality 3D printing materials available to a broad audience.\n\nTheir product line spans standard materials like PLA and PETG to specialty filaments including wood-fill and flexible materials. The company's flagship offerings emphasize consistent quality and ease of use, ensuring reliable results across various printer platforms. Gizmo Dorks has achieved success by maintaining a strong connection with the maker community, actively listening to feedback and adapting their products accordingly.\n\nTheir commitment to customer satisfaction is evident in their responsive support and clear communication. The company offers an extensive color selection, providing creative flexibility for diverse projects. Gizmo Dorks ensures proper packaging with vacuum-sealed bags and desiccant for optimal material preservation. As they grow, Gizmo Dorks remains committed to their founding mission of supporting the maker community with quality materials and exceptional value.",
    location: "USA"
  },
  "Polymaker": {
    summary: "Polymaker is a leading global filament manufacturer headquartered in Shanghai, China, with a subsidiary in the Netherlands, renowned for their innovative materials and engineering excellence. Founded in 2012 by Dr. Luo Xiaofan, the company emerged from academic research with a mission to develop high-performance materials for additive manufacturing. Polymaker's roots in material science are evident in their sophisticated approach to polymer formulation and product development.\n\nTheir flagship PolyLite and PolyMax series have set new standards for consumer filaments, delivering exceptional mechanical properties and ease of printing. The company has achieved remarkable international success, establishing themselves as a premium brand trusted by both hobbyists and industrial users. Polymaker's commitment to innovation has resulted in groundbreaking products like their PolySmooth filament, which can be post-processed to achieve injection-molded surface quality.\n\nThe company operates state-of-the-art facilities with rigorous quality control, ensuring consistency across every spool. Polymaker has earned numerous industry awards for their material innovations and product quality. Their success extends to strategic partnerships with leading printer manufacturers, ensuring optimal material performance. As they continue to grow globally, Polymaker remains committed to pushing the boundaries of what's possible with 3D printing materials through continuous innovation.",
    location: "Shanghai, China & Netherlands",
    founded: "2012"
  },
};

// Helper function to get brand info
export const getBrandInfo = (brandName: string) => {
  return brandInfo[brandName] || null;
};
