// Generate and decode shareable settings links

import type { PrintSettings } from './settingsFormatters';

export interface ShareableSettings {
  filamentId?: string;
  printerId?: string;
  nozzleTemp: number;
  bedTemp: number;
  printSpeed?: number;
  cooling?: number;
  retraction?: number;
  chamberTemp?: number;
}

// Generate a short code for shareable links
export function generateShortCode(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
  let code = '';
  for (let i = 0; i < 8; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return code;
}

// Encode settings to URL-safe base64
export function encodeSettings(settings: ShareableSettings): string {
  const json = JSON.stringify(settings);
  return btoa(json).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

// Decode settings from URL-safe base64
export function decodeSettings(encoded: string): ShareableSettings | null {
  try {
    const base64 = encoded.replace(/-/g, '+').replace(/_/g, '/');
    const json = atob(base64);
    return JSON.parse(json);
  } catch {
    return null;
  }
}

// Generate shareable URL with encoded settings
export function generateShareableUrl(settings: ShareableSettings): string {
  const encoded = encodeSettings(settings);
  return `${window.location.origin}/shared-settings?s=${encoded}`;
}

// Parse settings from current URL
export function parseSettingsFromUrl(): ShareableSettings | null {
  const params = new URLSearchParams(window.location.search);
  const encoded = params.get('s');
  if (!encoded) return null;
  return decodeSettings(encoded);
}

// Convert PrintSettings to ShareableSettings
export function toShareableSettings(
  settings: PrintSettings,
  filamentId?: string,
  printerId?: string
): ShareableSettings {
  return {
    filamentId,
    printerId,
    nozzleTemp: settings.nozzleTemp,
    bedTemp: settings.bedTemp,
    printSpeed: settings.printSpeed,
    cooling: settings.cooling,
    retraction: settings.retraction,
    chamberTemp: settings.chamberTemp,
  };
}

// Generate social share URLs
export function getSocialShareUrl(
  platform: 'reddit' | 'discord' | 'twitter' | 'email',
  shareUrl: string,
  title: string
): string {
  const encodedUrl = encodeURIComponent(shareUrl);
  const encodedTitle = encodeURIComponent(title);
  const encodedBody = encodeURIComponent(`Check out these print settings for ${title}:\n\n${shareUrl}\n\nGenerated by FilaScope`);

  switch (platform) {
    case 'reddit':
      return `https://www.reddit.com/submit?url=${encodedUrl}&title=${encodedTitle}`;
    case 'twitter':
      return `https://twitter.com/intent/tweet?url=${encodedUrl}&text=${encodedTitle}`;
    case 'email':
      return `mailto:?subject=${encodedTitle}&body=${encodedBody}`;
    case 'discord':
      // Discord doesn't have a direct share URL, copy to clipboard instead
      return shareUrl;
    default:
      return shareUrl;
  }
}
