// Format settings data into various output formats

export interface PrintSettings {
  filamentName: string;
  material: string;
  vendor: string;
  printerName?: string;
  nozzleTemp: number;
  nozzleTempMin?: number;
  nozzleTempMax?: number;
  bedTemp: number;
  bedTempMin?: number;
  bedTempMax?: number;
  printSpeed?: number;
  cooling?: number;
  retraction?: number;
  chamberTemp?: number;
  dryingTemp?: number;
  dryingTime?: number;
}

export type ExportFormat = 'plain' | 'json' | 'markdown' | 'html';

export function formatAsPlainText(settings: PrintSettings): string {
  const lines = [
    `${settings.filamentName} - Print Settings`,
    '━'.repeat(50),
    '',
    `Material: ${settings.material}`,
    `Vendor: ${settings.vendor}`,
    settings.printerName ? `Printer: ${settings.printerName}` : null,
    '',
    '── Temperature Settings ──',
    `Nozzle Temperature: ${settings.nozzleTemp}°C${settings.nozzleTempMin && settings.nozzleTempMax ? ` (Range: ${settings.nozzleTempMin}-${settings.nozzleTempMax}°C)` : ''}`,
    `Bed Temperature: ${settings.bedTemp}°C${settings.bedTempMin && settings.bedTempMax ? ` (Range: ${settings.bedTempMin}-${settings.bedTempMax}°C)` : ''}`,
    settings.chamberTemp ? `Chamber Temperature: ${settings.chamberTemp}°C` : null,
    '',
    settings.printSpeed ? `Print Speed: ${settings.printSpeed} mm/s` : null,
    settings.cooling !== undefined ? `Cooling: ${settings.cooling}%` : null,
    settings.retraction ? `Retraction: ${settings.retraction}mm` : null,
    '',
    settings.dryingTemp ? '── Drying Requirements ──' : null,
    settings.dryingTemp ? `Drying Temperature: ${settings.dryingTemp}°C` : null,
    settings.dryingTime ? `Drying Time: ${settings.dryingTime} hours` : null,
    '',
    '━'.repeat(50),
    'Generated by FilaScope • filascope.com',
  ];

  return lines.filter(Boolean).join('\n');
}

export function formatAsJSON(settings: PrintSettings): string {
  const data = {
    filament: settings.filamentName,
    material: settings.material,
    vendor: settings.vendor,
    printer: settings.printerName || null,
    settings: {
      nozzle_temp: settings.nozzleTemp,
      nozzle_temp_range: settings.nozzleTempMin && settings.nozzleTempMax 
        ? { min: settings.nozzleTempMin, max: settings.nozzleTempMax }
        : null,
      bed_temp: settings.bedTemp,
      bed_temp_range: settings.bedTempMin && settings.bedTempMax
        ? { min: settings.bedTempMin, max: settings.bedTempMax }
        : null,
      chamber_temp: settings.chamberTemp || null,
      print_speed: settings.printSpeed || null,
      cooling: settings.cooling ?? null,
      retraction: settings.retraction || null,
    },
    drying: settings.dryingTemp ? {
      temperature: settings.dryingTemp,
      time_hours: settings.dryingTime || null,
    } : null,
    generated: new Date().toISOString().split('T')[0],
    source: 'FilaScope',
  };

  return JSON.stringify(data, null, 2);
}

export function formatAsMarkdown(settings: PrintSettings): string {
  const lines = [
    `## ${settings.filamentName} - Print Settings`,
    '',
    `**Material:** ${settings.material}  `,
    `**Vendor:** ${settings.vendor}  `,
    settings.printerName ? `**Printer:** ${settings.printerName}  ` : null,
    '',
    '### Temperature Settings',
    '',
    '| Setting | Value | Range |',
    '|---------|-------|-------|',
    `| Nozzle Temp | ${settings.nozzleTemp}°C | ${settings.nozzleTempMin && settings.nozzleTempMax ? `${settings.nozzleTempMin}-${settings.nozzleTempMax}°C` : '—'} |`,
    `| Bed Temp | ${settings.bedTemp}°C | ${settings.bedTempMin && settings.bedTempMax ? `${settings.bedTempMin}-${settings.bedTempMax}°C` : '—'} |`,
    settings.chamberTemp ? `| Chamber Temp | ${settings.chamberTemp}°C | — |` : null,
    '',
    settings.printSpeed || settings.cooling !== undefined || settings.retraction ? '### Print Settings' : null,
    settings.printSpeed || settings.cooling !== undefined || settings.retraction ? '' : null,
    settings.printSpeed || settings.cooling !== undefined || settings.retraction ? '| Setting | Value |' : null,
    settings.printSpeed || settings.cooling !== undefined || settings.retraction ? '|---------|-------|' : null,
    settings.printSpeed ? `| Print Speed | ${settings.printSpeed} mm/s |` : null,
    settings.cooling !== undefined ? `| Cooling | ${settings.cooling}% |` : null,
    settings.retraction ? `| Retraction | ${settings.retraction}mm |` : null,
    '',
    settings.dryingTemp ? '### Drying Requirements' : null,
    settings.dryingTemp ? '' : null,
    settings.dryingTemp ? `- **Temperature:** ${settings.dryingTemp}°C` : null,
    settings.dryingTime ? `- **Duration:** ${settings.dryingTime} hours` : null,
    '',
    '---',
    '*Generated by [FilaScope](https://filascope.com)*',
  ];

  return lines.filter(Boolean).join('\n');
}

export function formatAsHTML(settings: PrintSettings): string {
  return `<div class="filascope-settings" style="font-family: system-ui, sans-serif; max-width: 400px; padding: 20px; border: 1px solid #333; border-radius: 8px; background: #1a1a1a; color: #fff;">
  <h3 style="margin: 0 0 16px 0; color: #00d4d4;">${settings.filamentName}</h3>
  <p style="margin: 0 0 4px 0; color: #888;"><strong>Material:</strong> ${settings.material}</p>
  <p style="margin: 0 0 4px 0; color: #888;"><strong>Vendor:</strong> ${settings.vendor}</p>
  ${settings.printerName ? `<p style="margin: 0 0 16px 0; color: #888;"><strong>Printer:</strong> ${settings.printerName}</p>` : ''}
  
  <table style="width: 100%; border-collapse: collapse; margin-top: 16px;">
    <thead>
      <tr style="border-bottom: 1px solid #333;">
        <th style="text-align: left; padding: 8px 0; color: #888;">Setting</th>
        <th style="text-align: right; padding: 8px 0; color: #888;">Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="padding: 8px 0;">Nozzle Temp</td>
        <td style="text-align: right; color: #00d4d4; font-weight: 600;">${settings.nozzleTemp}°C</td>
      </tr>
      <tr>
        <td style="padding: 8px 0;">Bed Temp</td>
        <td style="text-align: right; color: #00d4d4; font-weight: 600;">${settings.bedTemp}°C</td>
      </tr>
      ${settings.chamberTemp ? `<tr>
        <td style="padding: 8px 0;">Chamber Temp</td>
        <td style="text-align: right; color: #00d4d4; font-weight: 600;">${settings.chamberTemp}°C</td>
      </tr>` : ''}
      ${settings.printSpeed ? `<tr>
        <td style="padding: 8px 0;">Print Speed</td>
        <td style="text-align: right;">${settings.printSpeed} mm/s</td>
      </tr>` : ''}
      ${settings.cooling !== undefined ? `<tr>
        <td style="padding: 8px 0;">Cooling</td>
        <td style="text-align: right;">${settings.cooling}%</td>
      </tr>` : ''}
    </tbody>
  </table>
  
  <p style="margin: 16px 0 0 0; font-size: 12px; color: #666; text-align: center;">
    Generated by <a href="https://filascope.com" style="color: #00d4d4;">FilaScope</a>
  </p>
</div>`;
}

export function formatSettings(settings: PrintSettings, format: ExportFormat): string {
  switch (format) {
    case 'plain':
      return formatAsPlainText(settings);
    case 'json':
      return formatAsJSON(settings);
    case 'markdown':
      return formatAsMarkdown(settings);
    case 'html':
      return formatAsHTML(settings);
    default:
      return formatAsPlainText(settings);
  }
}

export const FORMAT_INFO: Record<ExportFormat, { label: string; description: string; icon: string }> = {
  plain: { label: 'Plain Text', description: 'Readable format', icon: 'FileText' },
  json: { label: 'JSON', description: 'For developers', icon: 'Braces' },
  markdown: { label: 'Markdown', description: 'For Reddit/Discord', icon: 'Hash' },
  html: { label: 'HTML', description: 'For blogs', icon: 'Code' },
};
