// Tier assignments and editorial data for slicer comparison

export type SlicerTier = 'top-pick' | 'popular' | 'other';
export type BadgeType = 'staff-pick' | 'popular' | 'pro-choice' | null;
export type PriceType = 'free' | 'freemium' | 'paid';

export interface SlicerTierInfo {
  name: string;
  tier: SlicerTier;
  badge: BadgeType;
  brand: string;
  priceType: PriceType;
  priceValue?: string;
  overallScore: number;
  topFeatures: string[];
  editorialQuote: string;
  platforms: string[];
  multiMaterial: boolean;
}

export const slicerTierData: Record<string, SlicerTierInfo> = {
  'Bambu Studio': {
    name: 'Bambu Studio',
    tier: 'top-pick',
    badge: 'staff-pick',
    brand: 'BAMBU LAB',
    priceType: 'free',
    overallScore: 9.2,
    topFeatures: ['Beginner-Friendly', 'Multi-Material Support', 'Cloud Printing', 'Active Updates'],
    editorialQuote: 'Best all-rounder for beginners and experienced users alike',
    platforms: ['Windows', 'Mac', 'Linux'],
    multiMaterial: true,
  },
  'PrusaSlicer': {
    name: 'PrusaSlicer',
    tier: 'top-pick',
    badge: 'popular',
    brand: 'PRUSA RESEARCH',
    priceType: 'free',
    overallScore: 8.8,
    topFeatures: ['Open Source', 'Highly Customizable', 'Excellent Documentation', 'Regular Updates'],
    editorialQuote: 'Powerful and flexible with massive community support',
    platforms: ['Windows', 'Mac', 'Linux'],
    multiMaterial: true,
  },
  'OrcaSlicer': {
    name: 'OrcaSlicer',
    tier: 'top-pick',
    badge: 'pro-choice',
    brand: 'COMMUNITY',
    priceType: 'free',
    overallScore: 9.0,
    topFeatures: ['Advanced Calibration', 'Multi-Printer Support', 'Fast Development', 'Feature-Rich'],
    editorialQuote: 'The power user\'s choice with cutting-edge features',
    platforms: ['Windows', 'Mac', 'Linux'],
    multiMaterial: true,
  },
  'UltiMaker Cura': {
    name: 'UltiMaker Cura',
    tier: 'popular',
    badge: null,
    brand: 'ULTIMAKER',
    priceType: 'free',
    overallScore: 8.5,
    topFeatures: ['Massive Printer Library', 'Plugin Ecosystem', 'Beginner-Friendly'],
    editorialQuote: 'Industry standard with the largest printer support',
    platforms: ['Windows', 'Mac', 'Linux'],
    multiMaterial: true,
  },
  'Simplify3D': {
    name: 'Simplify3D',
    tier: 'popular',
    badge: null,
    brand: 'SIMPLIFY3D',
    priceType: 'paid',
    priceValue: '$199',
    overallScore: 7.5,
    topFeatures: ['Process-Based Workflow', 'Advanced Controls', 'Professional Support'],
    editorialQuote: 'Premium option for professionals needing fine control',
    platforms: ['Windows', 'Mac', 'Linux'],
    multiMaterial: true,
  },
  'ideaMaker': {
    name: 'ideaMaker',
    tier: 'popular',
    badge: null,
    brand: 'RAISE3D',
    priceType: 'free',
    overallScore: 8.0,
    topFeatures: ['Intuitive Interface', 'Texture Support', 'Cloud Integration'],
    editorialQuote: 'Clean interface with powerful hidden depth',
    platforms: ['Windows', 'Mac'],
    multiMaterial: true,
  },
  'SuperSlicer': {
    name: 'SuperSlicer',
    tier: 'popular',
    badge: null,
    brand: 'COMMUNITY',
    priceType: 'free',
    overallScore: 8.2,
    topFeatures: ['Advanced Settings', 'Calibration Tools', 'PrusaSlicer Fork'],
    editorialQuote: 'Feature-packed fork for advanced users',
    platforms: ['Windows', 'Mac', 'Linux'],
    multiMaterial: true,
  },
  'Creality Print': {
    name: 'Creality Print',
    tier: 'popular',
    badge: null,
    brand: 'CREALITY',
    priceType: 'free',
    overallScore: 7.0,
    topFeatures: ['Creality Integration', 'Simple Interface', 'Cloud Printing'],
    editorialQuote: 'Best for Creality printer owners',
    platforms: ['Windows', 'Mac'],
    multiMaterial: false,
  },
  'Lychee Slicer': {
    name: 'Lychee Slicer',
    tier: 'popular',
    badge: null,
    brand: 'MANGO 3D',
    priceType: 'freemium',
    priceValue: '$50/yr Pro',
    overallScore: 8.5,
    topFeatures: ['Resin Optimized', 'Auto-Supports', 'Beautiful UI'],
    editorialQuote: 'The go-to choice for resin printing',
    platforms: ['Windows', 'Mac'],
    multiMaterial: false,
  },
  'ChiTuBox': {
    name: 'ChiTuBox',
    tier: 'other',
    badge: null,
    brand: 'CHITUBOX',
    priceType: 'freemium',
    priceValue: '$170/yr Pro',
    overallScore: 7.5,
    topFeatures: ['Resin Specialist', 'Wide Compatibility', 'Auto-Supports'],
    editorialQuote: 'Popular resin slicer with broad printer support',
    platforms: ['Windows', 'Mac', 'Linux'],
    multiMaterial: false,
  },
  'Slic3r': {
    name: 'Slic3r',
    tier: 'other',
    badge: null,
    brand: 'OPEN SOURCE',
    priceType: 'free',
    overallScore: 6.5,
    topFeatures: ['Open Source Pioneer', 'Lightweight', 'Customizable'],
    editorialQuote: 'The grandfather of modern slicers',
    platforms: ['Windows', 'Mac', 'Linux'],
    multiMaterial: false,
  },
  'KISSlicer': {
    name: 'KISSlicer',
    tier: 'other',
    badge: null,
    brand: 'KISSLICER',
    priceType: 'freemium',
    priceValue: '$42 Pro',
    overallScore: 6.0,
    topFeatures: ['Fast Slicing', 'Lightweight', 'Portable'],
    editorialQuote: 'Keep It Simple Slicer for quick jobs',
    platforms: ['Windows', 'Mac', 'Linux'],
    multiMaterial: true,
  },
  'MatterControl': {
    name: 'MatterControl',
    tier: 'other',
    badge: null,
    brand: 'MATTERHACKERS',
    priceType: 'free',
    overallScore: 6.5,
    topFeatures: ['All-in-One Suite', 'Design Tools', 'Print Management'],
    editorialQuote: 'Combined slicer and design platform',
    platforms: ['Windows', 'Mac', 'Linux'],
    multiMaterial: false,
  },
  'CraftWare': {
    name: 'CraftWare',
    tier: 'other',
    badge: null,
    brand: 'CRAFTUNIQUE',
    priceType: 'free',
    overallScore: 6.0,
    topFeatures: ['Support Painting', 'Simple Interface', 'Lightweight'],
    editorialQuote: 'Simple slicer with manual support placement',
    platforms: ['Windows', 'Mac'],
    multiMaterial: false,
  },
  'Kiri:Moto': {
    name: 'Kiri:Moto',
    tier: 'other',
    badge: null,
    brand: 'GRID.SPACE',
    priceType: 'free',
    overallScore: 7.0,
    topFeatures: ['Browser-Based', 'No Install', 'CNC Support'],
    editorialQuote: 'Unique browser-based slicer for quick access',
    platforms: ['Web'],
    multiMaterial: false,
  },
  '3DPrinterOS': {
    name: '3DPrinterOS',
    tier: 'other',
    badge: null,
    brand: '3DPRINTEROS',
    priceType: 'freemium',
    priceValue: '$9.99/mo',
    overallScore: 6.5,
    topFeatures: ['Cloud-Based', 'Fleet Management', 'Enterprise Ready'],
    editorialQuote: 'Cloud platform for managing multiple printers',
    platforms: ['Web'],
    multiMaterial: false,
  },
  'FlashPrint': {
    name: 'FlashPrint',
    tier: 'other',
    badge: null,
    brand: 'FLASHFORGE',
    priceType: 'free',
    overallScore: 7.0,
    topFeatures: ['FlashForge Integration', 'Simple UI', 'Reliable'],
    editorialQuote: 'Best paired with FlashForge printers',
    platforms: ['Windows', 'Mac'],
    multiMaterial: false,
  },
  'Anycubic Slicer': {
    name: 'Anycubic Slicer',
    tier: 'other',
    badge: null,
    brand: 'ANYCUBIC',
    priceType: 'free',
    overallScore: 6.5,
    topFeatures: ['Anycubic Integration', 'PrusaSlicer Based', 'Simple'],
    editorialQuote: 'Customized for Anycubic printer owners',
    platforms: ['Windows', 'Mac'],
    multiMaterial: false,
  },
  'VoxelDance Tango': {
    name: 'VoxelDance Tango',
    tier: 'other',
    badge: null,
    brand: 'VOXELDANCE',
    priceType: 'paid',
    priceValue: '$99',
    overallScore: 7.5,
    topFeatures: ['Resin Specialist', 'Advanced Features', 'Fast Engine'],
    editorialQuote: 'Professional resin slicer with advanced features',
    platforms: ['Windows'],
    multiMaterial: false,
  },
  'Repetier-Host': {
    name: 'Repetier-Host',
    tier: 'other',
    badge: null,
    brand: 'REPETIER',
    priceType: 'free',
    overallScore: 6.0,
    topFeatures: ['Multi-Slicer Support', 'Print Server', 'Monitoring'],
    editorialQuote: 'Host software that works with multiple slicers',
    platforms: ['Windows', 'Mac', 'Linux'],
    multiMaterial: false,
  },
};

export function getSlicersByTier(tier: SlicerTier): SlicerTierInfo[] {
  return Object.values(slicerTierData).filter(s => s.tier === tier);
}

export function getSlicerTierInfo(name: string): SlicerTierInfo | undefined {
  return slicerTierData[name];
}
