project_id = "cfqfavmhdbyjzejipiwa"

[functions.fetch-prices]
verify_jwt = true

[functions.fetch-printer-prices]
verify_jwt = true

[functions.estimate-weights]
verify_jwt = false

[functions.cleanup-images]
verify_jwt = true

[functions.scrape-images]
verify_jwt = true

[functions.discover-printer-models]
verify_jwt = true