project_id = "cfqfavmhdbyjzejipiwa"

[functions.scrape-filament-colors]
verify_jwt = true

[functions.scrape-filament-upcs]
verify_jwt = false

[functions.fetch-prices]
verify_jwt = true

[functions.fetch-printer-prices]
verify_jwt = true

[functions.ai-search-msrp]
verify_jwt = true

[functions.estimate-weights]
verify_jwt = true

[functions.cleanup-images]
verify_jwt = true

[functions.scrape-images]
verify_jwt = true

[functions.discover-printer-models]
verify_jwt = true

[functions.scrape-brand-nozzles]
verify_jwt = true

[functions.deep-scrape-printer]
verify_jwt = true

[functions.import-printers]
verify_jwt = true

[functions.fetch-accessory-prices]
verify_jwt = true

[functions.rescrape-nozzle-images]
verify_jwt = true

[functions.scrape-accessory-images]
verify_jwt = true

[functions.log-printer-prices]
verify_jwt = true

[functions.scrape-printer-images]
verify_jwt = true

[functions.enrich-printer-data]
verify_jwt = true

[functions.update-global-prices]
verify_jwt = true

[functions.scrape-overture-images]
verify_jwt = true

[functions.scrape-colorfabb-images]
verify_jwt = true

[functions.scrape-matterhackers-images]
verify_jwt = true

[functions.scrape-siraya-images]
verify_jwt = true

[functions.scrape-ninjatek-images]
verify_jwt = true

[functions.scrape-prusament-images]
verify_jwt = true

[functions.scrape-taulman-images]
verify_jwt = true

[functions.scrape-fillamentum-images]
verify_jwt = true

[functions.scrape-fillamentum-prices]
verify_jwt = true

[functions.scrape-paramount-prices]
verify_jwt = true

[functions.scrape-new-brand-images]
verify_jwt = true

[functions.find-amazon-products]
verify_jwt = true

[functions.sync-3dxtech-products]
verify_jwt = true

[functions.lookup-barcodes]
verify_jwt = false

[functions.scrape-overture-colors]
verify_jwt = true

[functions.populate-hex-colors]
verify_jwt = true

[functions.fix-fillamentum-images]
verify_jwt = true

[functions.scrape-3dxtech-tds]
verify_jwt = true

[functions.scrape-3dfuel-tds]
verify_jwt = true
