/**
 * Fillamentum Product Seed Data
 * Parsed from manufacturer CSV export - 203 products across ~20 product lines
 * Premium Czech filament manufacturer known for exceptional color consistency
 */

export interface FillamentumSeedProduct {
  material: string;        // CSV Material column (e.g., "PLA Extrafill", "Flexfill TPU")
  filamentName: string;    // Full product title from CSV
  productUrl: string;      // Direct Shopify product URL
  color: string | null;    // Extracted color name (null for single-color products)
  imageUrl: string | null; // Shopify CDN image URL (with fixed protocol)
  colorHex: string | null; // Hex code if provided in CSV (null if N/A or empty)
}

// Helper to fix image URLs from CSV (convert escaped slashes to proper https URLs)
function fixImageUrl(rawUrl: string | null): string | null {
  if (!rawUrl) return null;
  // Convert "\\/\\/" to "https://"
  return 'https:' + rawUrl.replace(/\\\//g, '/');
}

// Helper to normalize hex codes from CSV
function normalizeHex(hex: string | null | undefined): string | null {
  if (!hex || hex === 'N/A' || hex.trim() === '') return null;
  const cleaned = hex.trim();
  if (cleaned.startsWith('#') && cleaned.length >= 7) return cleaned;
  return null;
}

/**
 * Fillamentum Product Seed - 203 products parsed from manufacturer CSV
 * Excludes: samples (15m, 6m), bundles, LockPAd accessories
 */
export const FILLAMENTUM_PRODUCT_SEED: FillamentumSeedProduct[] = [
  // ============================================================================
  // PLA EXTRAFILL (~70 colors) - Flagship PLA line
  // ============================================================================
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Vertigo Galaxy"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-vertigo-galaxy', color: 'Vertigo Galaxy', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Vertigo_Galaxy_1_75.jpg?v=1695210522'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Signal Red"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-signal-red', color: 'Signal Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Signal_Red_1_75.jpg?v=1695210960'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Pearl Ruby Red"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-pearl-ruby-red', color: 'Pearl Ruby Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Pearl_Ruby_Red_1_75.jpg?v=1695210912'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Vertigo Jade"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-vertigo-jade', color: 'Vertigo Jade', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Vertigo_Jade_1_75.jpg?v=1695210542'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Natural"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-natural', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Natural_1_75.jpg?v=1695210884'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Vertigo Cherry"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-vertigo-cherry', color: 'Vertigo Cherry', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Vertigo_Cherry_1_75.jpg?v=1695210513'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Traffic Purple"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-traffic-purple', color: 'Traffic Purple', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Traffic_Purple_1_75.jpg?v=1695210975'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Pearl Night Blue"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-pearl-night-blue', color: 'Pearl Night Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Pearl_Night_Blue_1_75.jpg?v=1695210901'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Vertigo Mystique"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-vertigo-mystique', color: 'Vertigo Mystique', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Vertigo_Mystique_1_75.jpg?v=1695210548'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Lilac"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-lilac', color: 'Lilac', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Lilac_1_75.jpg?v=1695210769'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Purple Red"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-purple-red', color: 'Purple Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Purple_Red_1_75.jpg?v=1695210937'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Luminous Green"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-luminous-green', color: 'Luminous Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Luminous_Green_1_75.jpg?v=1695210773'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Turquoise Green"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-turquoise-green', color: 'Turquoise Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Turquoise_Green_1_75.jpg?v=1695210510'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Baby Blue"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-baby-blue', color: 'Baby Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Baby_Blue_1_75.jpg?v=1695210700'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Luminous Yellow"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-luminous-yellow', color: 'Luminous Yellow', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Luminous_Yellow_1_75.jpg?v=1695210816'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Peppered Mustard"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-peppered-mustard', color: 'Peppered Mustard', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Peppered_Mustard_1_75_foto.png?v=1695210919'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Volcanic Dust"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-volcanic-dust', color: 'Volcanic Dust', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/be001e98-7f14-4f23-9d3a-ed40d0b3d5f8.jpg?v=1695210556'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Witch Please!"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-witch-please', color: 'Witch Please!', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/01_903309f1-09dd-4940-86c2-bf870b1c8076.jpg?v=1760536198'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Traffic White" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-traffic-white-1kg', color: 'Traffic White', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_White_1KG__1.jpg?v=1740408168'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Traffic Black" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-traffic-black-1kg', color: 'Traffic Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Traffic_Black__1KG.jpg?v=1741094495'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Light Ivory" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-light-ivory-1kg', color: 'Light Ivory', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Light_Ivory_1KG.jpg?v=1741332676'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Melon Yellow" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-melon-yellow-1kg', color: 'Melon Yellow', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Melon_Yellow_1KG_1.jpg?v=1741081652'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Orange Orange" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-orange-orange-1kg', color: 'Orange Orange', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Orange_Orange_1KG_1.jpg?v=1741093449'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Chocolate Brown" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-chocolate-brown-1kg', color: 'Chocolate Brown', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum__Chocolate_brown_1KG.jpg?v=1742487469'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Green Grass" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-green-grass-1kg', color: 'Green Grass', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Green_Grass_1KG_1.jpg?v=1741081253'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Gold Happens" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-gold-happens-1kg', color: 'Gold Happens', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum__Gold_happens_1KG.jpg?v=1743080268'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Traffic Red" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-traffic-red-1kg', color: 'Traffic Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Traffic_Red__1KG_2.jpg?v=1741096049'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Cobalt Blue" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-cobalt-blue-1kg', color: 'Cobalt Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Cobalt_Blue_1KG.jpg?v=1746518078'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Iron Grey" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-iron-grey-1kg', color: 'Iron Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Iron_Grey_1KG.jpg?v=1744624733'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Electric Grey" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-electric-grey-1kg', color: 'Electric Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Eletric_Grey_1KG.png?v=1743415631'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Sky Blue" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-sky-blue-1kg', color: 'Sky Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Sky_Blue_1KG_1.jpg?v=1741093853'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Turquoise Blue" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-turquoise-blue-1kg', color: 'Turquoise Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_TurquoiseBlue_1KG.jpg?v=1741096495'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Vertigo Starlight" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-vertigo-starlight-1kg', color: 'Vertigo Starlight', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Vertigo_Starlight_1KG__1.jpg?v=1741167306'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Rapunzel Silver" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-rapunzel-silver-1kg', color: 'Rapunzel Silver', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum__Rapunzel_Silver_1KG.jpg?v=1743416906'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Baby Blue" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-baby-blue-1kg', color: 'Baby Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum__Baby_Blue_1KG.jpg?v=1743414952'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Metallic Grey" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-metallic-grey-1kg', color: 'Metallic Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Metallic_Grey_1KG.png?v=1756459083'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Vertigo Galaxy" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-vertigo-galaxy-1kg', color: 'Vertigo Galaxy', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Vertigo_Galaxy_1KG.jpg?v=1748326279'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Mukha" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-mukha-1kg', color: 'Mukha', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Mukha_1KG.jpg?v=1756742371'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Purple Red" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-purple-red-1kg', color: 'Purple Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Purple_Red_1KG.jpg?v=1745495815'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Mint" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-mint-1kg', color: 'Mint', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Mint_1KG.jpg?v=1748324018'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Traffic Yellow" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-traffic-yellow-1kg', color: 'Traffic Yellow', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Traffic_Yellow_1KG.jpg?v=1748325529'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Concrete Grey" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-concrete-grey-1kg', color: 'Concrete Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Concrete_Grey_1KG.jpg?v=1756458646'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Noble Blue" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-noble-blue-1kg', color: 'Noble Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum__Noble_blue_1KG.jpg?v=1743416793'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Vertigo Grey" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-vertigo-grey-1kg', color: 'Vertigo Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Vertitog_Grey_1KG.jpg?v=1744097627'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Everybody\'s Magenta" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-everybodys-magenta-1kg', color: 'Everybody\'s Magenta', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Metallic_Grey__1KG_copy.png?v=1756459610'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Turkey Egg" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-turkey-egg-1-kg-1-75-mm', color: 'Turkey Egg', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Turkey_Egg_1KG_1.jpg?v=1756742840'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Pearl Ruby Red" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-pearl-ruby-red-1kg', color: 'Pearl Ruby Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Purple_Ruby_Red_1KG.jpg?v=1756458247'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Natural" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-natural-1kg', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Natural_1KG.jpg?v=1756459315'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Lilac" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-lilac-copy', color: 'Lilac', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Lillac.jpg?v=1756756317'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Signal Red" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-signal-red-1kg', color: 'Signal Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum__Signal_Red_1KG.jpg?v=1752056986'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Cairo Gold"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-cairo-gold', color: 'Cairo Gold', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/CAIRO_GOLD_drop02_placopy.jpg?v=1764232503'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Marrakesh Red"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-marrakesh-red', color: 'Marrakesh Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/MARRAKESH_RED_drop02_pla_copy.jpg?v=1764232659'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Abu Dhabi Green"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-abu-dhabi-green', color: 'Abu Dhabi Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ABU_DHABI_GREEN_drop02_placopy.jpg?v=1764229243'), colorHex: null },
  { material: 'PLA Extrafill', filamentName: 'PLA Extrafill "Luminous Green" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-luminous-green-1kg', color: 'Luminous Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_LUMINOUSGREEN_1KG_98503c0f-c520-45e0-aae2-40effbef6564.jpg?v=1756458468'), colorHex: null },
  
  // ============================================================================
  // PLA CRYSTAL CLEAR (~10 colors) - Translucent PLA line
  // ============================================================================
  { material: 'PLA Crystal Clear', filamentName: 'PLA Crystal Clear "Iceland Blue"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-extrafill-crystal-clear-iceland-blue', color: 'Iceland Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Crystal_Clear_Iceland_Blue_1_75.jpg?v=1695210664'), colorHex: '#87CEEB80' },
  { material: 'PLA Crystal Clear', filamentName: 'PLA Crystal Clear "Smaragd Green"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-crystal-clear-smaragd-green', color: 'Smaragd Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Extrafill_Crystal_Clear_Smaragd_Green_1_75.jpg?v=1695210682'), colorHex: '#50C87880' },
  { material: 'PLA Crystal Clear', filamentName: 'PLA Crystal Clear "Amethyst Purple"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-crystal-clear-amethyst-purple', color: 'Amethyst Purple', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Crystal_Clear_Amethyst_Purple_1_75.jpg?v=1695210660'), colorHex: '#9966CC80' },
  { material: 'PLA Crystal Clear', filamentName: 'PLA Crystal Clear "Kiwi Green"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-crystal-clear-kiwi-green', color: 'Kiwi Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Crystal_Clear_Kiwi_Green_1_75.jpg?v=1695210670'), colorHex: '#8EE53F80' },
  { material: 'PLA Crystal Clear', filamentName: 'PLA Crystal Clear "Tangerine Orange"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-crystal-clear-tangerine-orange', color: 'Tangerine Orange', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PLA_Crystal_Clear_Tangerine_Orange_1_75_750g.jpg?v=1695210690'), colorHex: '#FF6F0080' },
  { material: 'PLA Crystal Clear', filamentName: 'PLA Crystal Clear "Iceland Blue" 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-crystal-clear-iceland-blue-1kg', color: 'Iceland Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_Fillamentum_Iceland_Blue_1KG.jpg?v=1756458043'), colorHex: '#87CEEB80' },
  { material: 'PLA Crystal Clear', filamentName: 'PLA Crystal Clear 1 KG', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/pla-crystal-clear-1kg', color: 'Clear', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/PLA_FIllamentun_Crystal_Cleasr_1KG.jpg?v=1749040878'), colorHex: '#FFFFFF00' },

  // ============================================================================
  // ASA EXTRAFILL (~15 colors) - Weather-resistant
  // ============================================================================
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Traffic Black"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-traffic-black', color: 'Traffic Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASA_TRAFFIC_BLACK_1.jpg?v=1750676528'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Traffic White"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-traffic-white', color: 'Traffic White', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ASA_Extrafill_Traffic_White_1_75.jpg?v=1653316143'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Anthracite Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-anthracite-grey', color: 'Anthracite Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASA_ANTHRACITE_GREY_1.jpg?v=1750676283'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Traffic Red"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-traffic-red', color: 'Traffic Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASA_fillamentum_Traffic_Red.jpg?v=1750676504'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Grey Blue"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-grey-blue', color: 'Grey Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASA_fillamentum_Grey_bluie.jpg?v=1750676324'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Green Grass"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-green-grass', color: 'Green Grass', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASA_GREEN_GRASS_2.jpg?v=1750676406'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Sky Blue"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-sky-blue', color: 'Sky Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASA_fillamentum_Sky_Blue.jpg?v=1750676448'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Metallic Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-metallic-grey', color: 'Metallic Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASA_Metallic_Grey.jpg?v=1756753372'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Traffic Yellow"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-traffic-yellow', color: 'Traffic Yellow', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASA_TRAFFIC_YELLOW_1.jpg?v=1750676472'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Natural"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-natural', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASA_NATURAL_1.jpg?v=1750676581'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Vertigo Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-vertigo-grey', color: 'Vertigo Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASA_VERTIGO_GREY_1.jpg?v=1750676197'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Dijon Mustard"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-dijon-mustard', color: 'Dijon Mustard', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ASA_Extrafill_Dijon_Mustard_1_75.jpg?v=1653315994'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "White Aluminium"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-white-aluminium', color: 'White Aluminium', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASA_fillamentum_White_Aluminium.jpg?v=1750676349'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Snow White"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-snow-white', color: 'Snow White', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASA_fillamentum_Snow_pink.jpg?v=1750676171'), colorHex: null },
  { material: 'ASA Extrafill', filamentName: 'ASA Extrafill "Vivid Pink"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa-extrafill-vivid-pink', color: 'Vivid Pink', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASA_fillamentum_Vivid_Piink.jpg?v=1750676225'), colorHex: null },

  // ============================================================================
  // ABS EXTRAFILL (~12 colors)
  // ============================================================================
  { material: 'ABS Extrafill', filamentName: 'ABS Extrafill "Traffic Black"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/abs-extrafill-traffic-black', color: 'Traffic Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ABS_Extrafill_Traffic_Black_1_75.jpg?v=1606719113'), colorHex: null },
  { material: 'ABS Extrafill', filamentName: 'ABS Extrafill "Traffic White"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/abs-extrafill-traffic-white', color: 'Traffic White', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ABS_Extrafill_Traffic_White_1_75.jpg?v=1606719205'), colorHex: null },
  { material: 'ABS Extrafill', filamentName: 'ABS Extrafill "Metallic Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/abs-extrafill-metallic-grey', color: 'Metallic Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ABS_Extrafill_Metallic_Grey_1_75.jpg?v=1606719167'), colorHex: null },
  { material: 'ABS Extrafill', filamentName: 'ABS Extrafill "Natural"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/abs-extrafill-natural', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ABS_Extrafill_Natural_1_75.jpg?v=1606719235'), colorHex: null },
  { material: 'ABS Extrafill', filamentName: 'ABS Extrafill "Cobalt Blue"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/abs-extrafill-cobalt-blue', color: 'Cobalt Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ABS_Extrafill_Cobalt_Blue_1_75.jpg?v=1606719043'), colorHex: null },
  { material: 'ABS Extrafill', filamentName: 'ABS Extrafill "Luminous Orange"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/abs-extrafill-luminous-orange', color: 'Luminous Orange', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ABS_Extrafill_Liuminous_Orange_1_75.jpg?v=1606718865'), colorHex: null },
  { material: 'ABS Extrafill', filamentName: 'ABS Extrafill "Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/abs-extrafill-transparent', color: 'Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ABS_Extrafill_Transparent_1_75.jpg?v=1606719274'), colorHex: '#F0F0F080' },
  { material: 'ABS Extrafill', filamentName: 'ABS Extrafill "Concrete Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/abs-extrafill-concrete-grey', color: 'Concrete Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ABS_Extrafill_Concrete_Grey_1_75.jpg?v=1606719140'), colorHex: null },
  { material: 'ABS Extrafill', filamentName: 'ABS Extrafill "Traffic Red"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/abs-extrafill-traffic-red', color: 'Traffic Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ABS_Extrafill_Traffic_Red_1_75.jpg?v=1606718895'), colorHex: null },
  { material: 'ABS Extrafill', filamentName: 'ABS Extrafill "Turquoise Green"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/abs-extrafill-turquoise-green', color: 'Turquoise Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ABS_Extrafill_Turquoise_Green_1_75.jpg?v=1606718961'), colorHex: null },
  { material: 'ABS Extrafill', filamentName: 'ABS Extrafill "Sky Blue"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/abs-extrafill-sky-blue', color: 'Sky Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ABS_Extrafill_Sky_Blue_1_75.jpg?v=1606719015'), colorHex: null },
  { material: 'ABS Extrafill', filamentName: 'ABS Extrafill "Signal Brown"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/abs-extrafill-signal-brown', color: 'Signal Brown', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ABS_Extrafill_Signal_Brown_1_75.jpg?v=1606719072'), colorHex: null },
  { material: 'ABS Extrafill', filamentName: 'ABS Extrafill "Traffic Yellow"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/abs-extrafill-traffic-yellow', color: 'Traffic Yellow', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/ABS_Extrafill_Trafic_Yellow_1_75.jpg?v=1606718833'), colorHex: null },

  // ============================================================================
  // PETG (~20 colors)
  // ============================================================================
  { material: 'PETG', filamentName: 'PETG "Wizard\'s Voodoo"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-wizards-voodoo', color: 'Wizard\'s Voodoo', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Wizzards_Voodo_750G_1.png?v=1678284247'), colorHex: null },
  { material: 'PETG', filamentName: 'PETG "Black Soul"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-black-soul', color: 'Black Soul', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Black_Soul_1KG.png?v=1675010124'), colorHex: null },
  { material: 'PETG', filamentName: 'PETG "Copper With Me"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-copper-with-me', color: 'Copper With Me', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Copper_With_Me_750G.png?v=1676894309'), colorHex: null },
  { material: 'PETG', filamentName: 'PETG "Greedy Dragon"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-greedy-dragon', color: 'Greedy Dragon', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Greedy_Dragon_750G_1.png?v=1676894334'), colorHex: null },
  { material: 'PETG', filamentName: 'PETG "Sea Wave"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-sea-wave', color: 'Sea Wave', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Sea_Wave_750G.png?v=1676894338'), colorHex: null },
  { material: 'PETG', filamentName: 'PETG "Red Hood Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-red-hood-transparent', color: 'Red Hood Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Red_Hood_1KG.png?v=1675012960'), colorHex: '#D32F2F80' },
  { material: 'PETG', filamentName: 'PETG "Ghost White"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-ghost-white', color: 'Ghost White', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Ghost_White_1KG.png?v=1674991002'), colorHex: null },
  { material: 'PETG', filamentName: 'PETG "Melon Yellow"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-melon-yellow', color: 'Melon Yellow', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Melon_Yello_1KG.png?v=1674993421'), colorHex: null },
  { material: 'PETG', filamentName: 'PETG "Deep Sea Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-deep-sea-transparent', color: 'Deep Sea Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Deep_Sea_Transp_1KG.png?v=1675013585'), colorHex: '#00487880' },
  { material: 'PETG', filamentName: 'PETG "Iced Green Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-iced-green-transparent', color: 'Iced Green Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Iced_Green_1KG.png?v=1675013782'), colorHex: '#69F0AE80' },
  { material: 'PETG', filamentName: 'PETG "Natural"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-natural-1', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Natural_1KG.png?v=1674990537'), colorHex: null },
  { material: 'PETG', filamentName: 'PETG "Gold Cloud"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-gold-cloud', color: 'Gold Cloud', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Gold_Cloud_750G_1.png?v=1676894330'), colorHex: null },
  { material: 'PETG', filamentName: 'PETG "Fresh Poison Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-fresh-poison-transparent', color: 'Fresh Poison Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Fresh_poison_1KG.png?v=1675013958'), colorHex: '#76FF0380' },
  { material: 'PETG', filamentName: 'PETG "Vertigo Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-vertigo-grey', color: 'Vertigo Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Vertigo_Grey_750G_1.png?v=1676894342'), colorHex: null },
  { material: 'PETG', filamentName: 'PETG "Koala Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-koala-grey', color: 'Koala Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Koala_Grey_1KG.png?v=1675009872'), colorHex: null },
  { material: 'PETG', filamentName: 'PETG "Neon Pink Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-neon-pink-transparent', color: 'Neon Pink Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Neon_Pink_1KG.png?v=1675013127'), colorHex: '#FF148080' },
  { material: 'PETG', filamentName: 'PETG "Calendula Orange"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-calendula-orange', color: 'Calendula Orange', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Calendula_Orange_1KG.png?v=1674993624'), colorHex: null },
  { material: 'PETG', filamentName: 'PETG "Aloe Green"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-aloe-green', color: 'Aloe Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Aloe_green_1KG.png?v=1676894364'), colorHex: null },
  { material: 'PETG', filamentName: 'PETG "Pink Lollipop Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-pink-lollipop-transparent', color: 'Pink Lollipop Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Pink_Lollipop_1KG.png?v=1675013314'), colorHex: '#F48FB180' },
  { material: 'PETG', filamentName: 'PETG "Lemon Yellow Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-lemon-yellow-transparent', color: 'Lemon Yellow Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Lemon_Yellow_1KG.png?v=1675012491'), colorHex: '#FFEB3B80' },
  { material: 'PETG', filamentName: 'PETG "Neon Yellow Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-neon-yellow-transparent', color: 'Neon Yellow Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Neon_Yellow_1KG.png?v=1675012207'), colorHex: '#FFFF0080' },
  { material: 'PETG', filamentName: 'PETG "Bunny Blue Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-bunny-blue-transparent', color: 'Bunny Blue Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Bunny_Blue_1KG.png?v=1675013462'), colorHex: '#81D4FA80' },
  { material: 'PETG', filamentName: 'PETG "Neon Orange Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/petg-neon-orange-transparent', color: 'Neon Orange Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Neon_Orange_1KG.png?v=1675012804'), colorHex: '#FF570080' },

  // ============================================================================
  // CPE HG100 (~25 colors) - Copolyester engineering material
  // ============================================================================
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Black Soul"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-black-soul', color: 'Black Soul', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Black_Soul_1_75.jpg?v=1653316309'), colorHex: null },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Vertigo Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-vertigo-grey', color: 'Vertigo Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Vertigo_Grey_1_75.jpg?v=1660133907'), colorHex: null },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Ghost White"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-ghost-white', color: 'Ghost White', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Ghost_White_1_75.jpg?v=1660134118'), colorHex: null },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Natural"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-natural', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Natural_1_75.jpg?v=1660133846'), colorHex: null },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Red Hood Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-red-hood-transparent', color: 'Red Hood Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Red_Hood_Transparent_1_75.jpg?v=1660133879'), colorHex: '#D32F2F80' },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Neon Orange Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-neon-orange-transparent', color: 'Neon Orange Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Neon_Orange_Transparent_1_75.jpg?v=1660133851'), colorHex: '#FF570080' },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Deep Sea Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-deep-sea-transparent', color: 'Deep Sea Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Deep_Sea_Transparent_1_75.jpg?v=1660133659'), colorHex: '#00487880' },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Grey Mouse Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-grey-mouse-transparent', color: 'Grey Mouse Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Grey_Mouse_Transparent_1_75_8e6e3624-d067-4022-8e79-2030870dd445.jpg?v=1660134113'), colorHex: '#9E9E9E80' },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Mistake Blue Metallic"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-mistake-blue-metallic', color: 'Mistake Blue Metallic', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Mistake_Blue_Metallic_1_75_fb2b17ed-7404-49cb-a278-912528bab026.jpg?v=1660133806'), colorHex: null },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Army Green"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-army-green', color: 'Army Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Army_Green_1_75_18201a86-6ca3-49e3-870b-370a2a9b38b9.jpg?v=1653316292'), colorHex: null },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Neon Yellow Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-neon-yellow-transparent', color: 'Neon Yellow Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Neon_Yellow_Transparent_1_75.jpg?v=1660133864'), colorHex: '#FFFF0080' },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Pistachio Green"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-pistachio-green', color: 'Pistachio Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Pistachio_Green_1_75_17a73e4c-42ac-4441-b025-3024c29c2fb4.jpg?v=1660133874'), colorHex: null },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Jungle Green Metallic"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-jungle-green-metallic', color: 'Jungle Green Metallic', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Jungle_Green_Metallic_1_75_5da61324-75cf-4758-9748-35656cc7efad.jpg?v=1660133790'), colorHex: null },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Iced Green Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-iced-green-transparent', color: 'Iced Green Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Iced_Green_Transparent_1_75.jpg?v=1660133756'), colorHex: '#69F0AE80' },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Morning Sun Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-morning-sun-transparent', color: 'Morning Sun Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Morning_Sun_Transparent_1_75.jpg?v=1660133816'), colorHex: '#FFB74D80' },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Caramel Brown Metallic"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-caramel-brown-metallic', color: 'Caramel Brown Metallic', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Caramel_Brown_Metallic_1_75_b0d8636c-b212-4c6c-b405-c2465fe9d7d7.jpg?v=1660133636'), colorHex: null },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Flash Yellow Metallic"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-flash-yellow-metallic', color: 'Flash Yellow Metallic', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Flash_Yellow_Metallic_1_75_3b68d7d8-c3c9-4a4b-9ca1-11cb8eb02082.jpg?v=1660133677'), colorHex: null },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "UFO Blue Metallic"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-ufo-blue-metallic', color: 'UFO Blue Metallic', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_UFO_Blue_Metallic_1_75_1682e574-e754-4967-9b90-6cfe4f751b0d.jpg?v=1660133888'), colorHex: null },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Lagoon Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-lagoon-transparent', color: 'Lagoon Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Lagoon_Transparent_1_75_cbf88150-0f46-4170-8d87-f392ec83819c.jpg?v=1660133796'), colorHex: '#00BCD480' },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Neon Pink Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-neon-pink-transparent', color: 'Neon Pink Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Neon_Pink_Transparent_1_75.jpg?v=1660133857'), colorHex: '#FF148080' },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Pink Blush Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-pink-blush-transparent', color: 'Pink Blush Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Pink_Blush_Transparent_1_75.jpg?v=1660133869'), colorHex: '#F8BBD080' },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Lemonade Translucent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-lemonade-translucent', color: 'Lemonade Translucent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Lemonade_Translucent_1_75_a228cec0-d976-4bee-97ae-f2171ef58bab.jpg?v=1660133801'), colorHex: '#FFF59D80' },
  { material: 'CPE HG100', filamentName: 'CPE HG100 "Flirty Plum"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-hg100-flirty-plum', color: 'Flirty Plum', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_HG100_Flirty_Plum_1_75_086c7e56-d891-4463-9f48-e1be3c06fe17.jpg?v=1660133693'), colorHex: null },

  // ============================================================================
  // FLEXFILL TPU 98A (~15 colors) - Flexible material
  // ============================================================================
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 98A "Traffic Black"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-98a-traffic-black', color: 'Traffic Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_98A_Traffic_Black_1_75.jpg?v=1606721462'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 98A "Traffic White"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-98a-traffic-white', color: 'Traffic White', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_98A_Traffic_White_1_75.jpg?v=1606721861'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 98A "Vertigo Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-98a-vertigo-grey', color: 'Vertigo Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_98A_Vertigo_Grey_1_75.jpg?v=1606721488'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 98A "Pistachio Green"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-98a-pistachio-green', color: 'Pistachio Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_98A_Pistachio_Green_1_75.jpg?v=1606721740'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 98A "Signal Yellow"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-98a-signal-yellow', color: 'Signal Yellow', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_98A_Signal_Yellow_1_75.jpg?v=1606721254'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 98A "Metallic Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-98a-metallic-grey', color: 'Metallic Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_98A_Metallic_Grey_1_75.jpg?v=1606721832'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 98A "Natural"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-98a-natural', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_98A_Natural_1_75.jpg?v=1606721885'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 98A "Signal Red"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-98a-signal-red', color: 'Signal Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_98A_Signal_Red_1_75.jpg?v=1606721334'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 98A "Sky Blue"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-98a-sky-blue', color: 'Sky Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_98A_Sky_Blue_1_75.jpg?v=1606721437'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 98A "Luminous Green"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-98a-luminous-green', color: 'Luminous Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_98A_Luminous_Green_1_75.jpg?v=1606721381'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 98A "Powder Beige"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-98a-powder-beige', color: 'Powder Beige', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_98A_Powder_Beige_1_75.jpg?v=1606721283'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 98A "Carrot Orange"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-98a-carrot-orange', color: 'Carrot Orange', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_98A_Carrot_Orage_1_75.jpg?v=1606721309'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 98A "Blue Transparent"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-98a-blue-transparent', color: 'Blue Transparent', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_98A_Blue_Transparent_1_75.jpg?v=1606721407'), colorHex: '#2196F380' },

  // ============================================================================
  // FLEXFILL TPU 92A (~8 colors) - Softer flexible material
  // ============================================================================
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 92A "Traffic Black"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-92a-traffic-black', color: 'Traffic Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_92A_Traffic_Black_1_75.jpg?v=1606722011'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 92A "Metallic Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-92a-metallic-grey', color: 'Metallic Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_92A_Metallic_Grey_1_75.jpg?v=1606722035'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 92A "Signal Red"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-92a-signal-red', color: 'Signal Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_92A_Signal_Red_1_75.jpg?v=1606721933'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 92A "Natural"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-92a-natural', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_92A_Natural_1_75.jpg?v=1606722062'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 92A "Signal Yellow"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-92a-signal-yellow', color: 'Signal Yellow', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_92A_Traffic_Yellow_1_75.jpg?v=1606721909'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 92A "Sky Blue"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-92a-sky-blue', color: 'Sky Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_92A_Sky_Blue_1_75.jpg?v=1606721985'), colorHex: null },
  { material: 'Flexfill TPU', filamentName: 'Flexfill TPU 92A "Luminous Green"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpu-92a-luminous-green', color: 'Luminous Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPU_92A_Luminous_Green_1_75.jpg?v=1606721957'), colorHex: null },

  // ============================================================================
  // FLEXFILL TPE 90A (~7 colors)
  // ============================================================================
  { material: 'Flexfill TPE', filamentName: 'Flexfill TPE 90A "Light Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpe-90a-light-grey', color: 'Light Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPE_90A_Light_Grey_1_75.jpg?v=1606721142'), colorHex: null },
  { material: 'Flexfill TPE', filamentName: 'Flexfill TPE 90A "Traffic Black"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpe-90a-traffic-black', color: 'Traffic Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPE_90A_Traffic_Black_1_75.jpg?v=1606721047'), colorHex: null },
  { material: 'Flexfill TPE', filamentName: 'Flexfill TPE 90A "Natural"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpe-90a-natural', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPE_90A_Natural_1_75.jpg?v=1606721168'), colorHex: null },
  { material: 'Flexfill TPE', filamentName: 'Flexfill TPE 90A "Sky Blue"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpe-90a-sky-blue', color: 'Sky Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPE_90A_Sky_Blue_1_75.jpg?v=1606721111'), colorHex: null },
  { material: 'Flexfill TPE', filamentName: 'Flexfill TPE 90A "Signal Red"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpe-90a-signal-red', color: 'Signal Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPE_90A_Signal_Red_1_75.jpg?v=1606721077'), colorHex: null },

  // ============================================================================
  // FLEXFILL TPE 96A (~5 colors)
  // ============================================================================
  { material: 'Flexfill TPE', filamentName: 'Flexfill TPE 96A "Traffic Black"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpe-96a-traffic-black', color: 'Traffic Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPE_96A_Traffic_Black_1_75.jpg?v=1606720910'), colorHex: null },
  { material: 'Flexfill TPE', filamentName: 'Flexfill TPE 96A "Sky Blue"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpe-96a-sky-blue', color: 'Sky Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPE_96A_Sky_Blue_1_75.jpg?v=1606720961'), colorHex: null },
  { material: 'Flexfill TPE', filamentName: 'Flexfill TPE 96A "Light Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpe-96a-light-grey', color: 'Light Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPE_96A_Light_Grey_1_75.jpg?v=1606720985'), colorHex: null },
  { material: 'Flexfill TPE', filamentName: 'Flexfill TPE 96A "Natural"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpe-96a-natural', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPE_96A_Natural_1_75.jpg?v=1606721020'), colorHex: null },
  { material: 'Flexfill TPE', filamentName: 'Flexfill TPE 96A "Signal Red"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/flexfill-tpe-96a-signal-red', color: 'Signal Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Flexfill_TPE_96A_Signal_Red_1_75.jpg?v=1606720936'), colorHex: null },

  // ============================================================================
  // NYLON FX256 (~6 colors)
  // ============================================================================
  { material: 'Nylon FX256', filamentName: 'Nylon FX256 "Natural"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/nylon-fx256-natural', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Nylon_FX256_Natural_1_75_mm.jpg?v=1621944842'), colorHex: null },
  { material: 'Nylon FX256', filamentName: 'Nylon FX256 "Traffic Black"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/nylon-fx256-traffic-black', color: 'Traffic Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Nylon_FX256_Traffic_Black_1_75.jpg?v=1606719690'), colorHex: null },
  { material: 'Nylon FX256', filamentName: 'Nylon FX256 "Vertigo Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/nylon-fx256-vertigo-grey', color: 'Vertigo Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Nylon_FX256_Vertigo_Grey_1_75.jpg?v=1606719729'), colorHex: null },
  { material: 'Nylon FX256', filamentName: 'Nylon FX256 "Sky Blue"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/nylon-fx256-sky-blue', color: 'Sky Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Nylon_FX256_Sky_Blue_1_75.jpg?v=1606719783'), colorHex: null },
  { material: 'Nylon FX256', filamentName: 'Nylon FX256 "Signal Red"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/nylon-fx256-signal-red', color: 'Signal Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Nylon_FX256_Signal_Red_1_75.jpg?v=1606719809'), colorHex: null },
  { material: 'Nylon FX256', filamentName: 'Nylon FX256 "Metallic Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/nylon-fx256-metallic-grey', color: 'Metallic Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Nylon_FX256_Metallic_Grey_1_75.jpg?v=1606719755'), colorHex: null },

  // ============================================================================
  // ENGINEERING MATERIALS - Nylon CF15, AF80, CPE CF112, ASA CF10, PP
  // ============================================================================
  { material: 'Nylon', filamentName: 'Nylon CF15 Carbon', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/nylon-cf15-carbon', color: 'Carbon Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Nylon_CF15_Carbon_1_75.jpg?v=1606719888'), colorHex: '#2D2D2D' },
  { material: 'Nylon', filamentName: 'Nylon AF80 Aramid', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/nylon-af80-aramid', color: 'Aramid Gold', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Nylon_AF80_Aramid_1_75.jpg?v=1606719951'), colorHex: '#D4A017' },
  { material: 'Unknown', filamentName: 'CPE CF112 Carbon', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/cpe-cf112-carbon', color: 'Carbon Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/CPE_CF112_Carbon_Natural_1_75.jpg?v=1606719599'), colorHex: '#2D2D2D' },
  { material: 'Unknown', filamentName: 'ASA CF10 Carbon', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/asa_cf10', color: 'Carbon Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/ASACF10.jpg?v=1749030426'), colorHex: '#2D2D2D' },
  { material: 'Unknown', filamentName: 'Polypropylene PP 2320', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/polypropylene-pp-2320', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/PP_2320_Natural_1_75.jpg?v=1606719525'), colorHex: '#F5F5F5' },

  // ============================================================================
  // TIMBERFILL (~8 colors) - Wood composite
  // ============================================================================
  { material: 'Timberfill', filamentName: 'Timberfill "Cinnamon"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/timberfill-cinnamon', color: 'Cinnamon', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Timberfill__Cinnamon_Antoni_Nosek_planter_02.jpg?v=1606720077'), colorHex: null },
  { material: 'Timberfill', filamentName: 'Timberfill "Light Wood Tone"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/timberfill-light-wood-tone', color: 'Light Wood Tone', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Timberfill__Light_Wood_Tone_Antoni_Nosek_planter_02.jpg?v=1606720021'), colorHex: null },
  { material: 'Timberfill', filamentName: 'Timberfill "Rosewood"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/timberfill-rosewood', color: 'Rosewood', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Timberfill__Rosewood_Antoni_Nosek_planter_02.jpg?v=1606720103'), colorHex: null },
  { material: 'Timberfill', filamentName: 'Timberfill "Champagne"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/timberfill-champagne', color: 'Champagne', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Timberfill__Champagne_Antoni_Nosek_planter_02.jpg?v=1606720051'), colorHex: null },
  { material: 'Timberfill', filamentName: 'Timberfill "Southern Pine"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/timberfill-southern-pine', color: 'Southern Pine', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Timberfill_Southern_Pine_1.75.png?v=1670446348'), colorHex: null },
  { material: 'Timberfill', filamentName: 'Timberfill "Redheart"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/timberfill-redheart', color: 'Redheart', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Timberfill_Redheart_1.75.png?v=1670446118'), colorHex: null },
  { material: 'Timberfill', filamentName: 'Timberfill "Terracotta"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/timberfill-terracotta', color: 'Terracotta', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Timberfill_Terracotta_1.75.png?v=1670446651'), colorHex: null },
  { material: 'Timberfill', filamentName: 'Timberfill "Charcoal"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/charcoal', color: 'Charcoal', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Timberfill_Charcoal_1.75.png?v=1670446473'), colorHex: null },

  // ============================================================================
  // HIPS EXTRAFILL (~5 colors) - Support material
  // ============================================================================
  { material: 'HIPS Extrafill', filamentName: 'HIPS Extrafill "Natural"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/hips-extrafill-natural', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/HIPS_Extrafill_Natural_1_75.jpg?v=1606718763'), colorHex: null },
  { material: 'HIPS Extrafill', filamentName: 'HIPS Extrafill "Traffic Black"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/hips-extrafill-traffic-black', color: 'Traffic Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/HIPS_Extrafill_Traffic_Black_1_75.jpg?v=1606718503'), colorHex: null },
  { material: 'HIPS Extrafill', filamentName: 'HIPS Extrafill "Sky Blue"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/hips-extrafill-sky-blue', color: 'Sky Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/HIPS_Extrafill_Sky_Blue_1_75.jpg?v=1606718631'), colorHex: null },
  { material: 'HIPS Extrafill', filamentName: 'HIPS Extrafill "Metallic Grey"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/hips-extrafill-metallic-grey', color: 'Metallic Grey', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/HIPS_Extrafill_Metallic_Grey_1_75.jpg?v=1606718664'), colorHex: null },
  { material: 'HIPS Extrafill', filamentName: 'HIPS Extrafill "Signal Red"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/hips-extrafill-signal-red', color: 'Signal Red', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/HIPS_Extrafill_Signal_Red_1_75.jpg?v=1606718560'), colorHex: null },

  // ============================================================================
  // VINYL 303 (~2 colors) - PVC filament
  // ============================================================================
  { material: 'Vinyl', filamentName: 'Vinyl 303 "Black"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/vinyl-303-black', color: 'Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Vinyl_303_Black_1_75.jpg?v=1606719359'), colorHex: null },
  { material: 'Vinyl', filamentName: 'Vinyl 303 "Natural"', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/vinyl-303-natural', color: 'Natural', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/Vinyl_303_Natural_1_75.jpg?v=1606719385'), colorHex: null },

  // ============================================================================
  // NONOILEN - Bio-based material (main product only, samples excluded)
  // ============================================================================
  { material: 'NonOilen', filamentName: 'NonOilen', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/nonoilen', color: 'Natural Green', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/products/NonOilen_ribbon_1_75.png?v=1617174826'), colorHex: '#C9D6B8' },

  // ============================================================================
  // FISHY FILAMENTS - Ocean plastic collaboration (main products only)
  // ============================================================================
  { material: 'Nylon', filamentName: '0rCA Nylon PA6 + CF10', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/orca', color: 'Ocean Black', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/0rca2_1.jpg?v=1696410913'), colorHex: '#1A1A1A' },
  { material: 'Nylon', filamentName: 'Porthcurno Nylon PA6', productUrl: 'https://shop.fillamentum.com/en-in/collections/3d-print-materials/products/porthcurno', color: 'Ocean Blue', imageUrl: fixImageUrl('//shop.fillamentum.com/cdn/shop/files/Hlavni_produktovka_Porthcurno.jpg?v=1696500495'), colorHex: '#1E3A5F' },
];

// Filter out samples and bundles from the seed
export const FILLAMENTUM_FILTERED_SEED = FILLAMENTUM_PRODUCT_SEED.filter(p => {
  const title = p.filamentName.toLowerCase();
  // Exclude samples
  if (/\d+\s*m\s*sample/i.test(title)) return false;
  // Exclude bundles
  if (/bundle/i.test(title)) return false;
  // Exclude LockPAd accessories
  if (/lockpad/i.test(title)) return false;
  return true;
});

// Export count for reference
export const FILLAMENTUM_SEED_COUNT = FILLAMENTUM_FILTERED_SEED.length;
