/**
 * SPECTRUM FILAMENTS EMBEDDED SEED DATA
 * 662 products from Shopify CA store
 * Auto-generated from CSV - Full catalog
 */

import type { SpectrumSeedProduct } from './spectrum-seed.ts';

export const SPECTRUM_SEED_DATA: SpectrumSeedProduct[] = [
  // === PLA Premium ReFill (lines 2-3) ===
  { title: "Filament Spectrum ReFill PLA Premium 1.75mm FOREST GREEN 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-refill-pla-premium-1-75mm-forest-green-1kg", color: "FOREST GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-ReFill-PLA-Premium-1-75mm-FOREST-GREEN-1kg-1827_1.jpg?v=1750854137", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum ReFill PLA Premium 1.75mm DEEP BLACK 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-refill-pla-premium-1-75mm-deep-black-1kg", color: "DEEP BLACK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-ReFill-PLA-Premium-1-75mm-DEEP-BLACK-1kg-1825_1.jpg?v=1750854202", colorHex: null, tdsUrl: null },
  
  // === Pastello PLA ReFill (line 4) ===
  { title: "Filament Spectrum ReFill Pastello PLA 1.75mm BONBON ROSE 1kg", material: "Pastello PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-refill-pastello-pla-1-75mm-bonbon-rose-1kg", color: "BONBON ROSE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-ReFill-Pastello-PLA-1-75mm-BONBON-ROSE-1kg-1872_1.jpg?v=1750854217", colorHex: null, tdsUrl: null },
  
  // === Premium PLA High Speed ReFill (line 5) ===
  { title: "Filament Spectrum ReFill Premium PLA High Speed 1.75mm NEON ORANGE UV 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-refill-premium-pla-high-speed-1-75mm-neon-orange-uv-1kg", color: "NEON ORANGE UV", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-ReFill-Premium-PLA-High-Speed-1-75mm-NEON-ORANGE-UV-1kg-1942_1.jpg?v=1750854233", colorHex: null, tdsUrl: null },
  
  // === 5PACK Material Mix (lines 6-7) - Will be filtered out ===
  { title: "Spectrum 5PACK Material Mix 1.75mm (5x 0.25kg) #2", material: "5PACK Material Mix", productUrl: "https://ca.spectrumfilaments.com/products/spectrum-5pack-material-mix-1-75mm-5x-0-25kg-2", color: "(5x 0.25kg)", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-5PACK-Materials-Mix-2-1-75mm-5x-0-25kg-1535_1.jpg?v=1750854245", colorHex: null, tdsUrl: null },
  { title: "Spectrum 5PACK Material Mix 1.75mm (5x 0.25kg) #1", material: "5PACK Material Mix", productUrl: "https://ca.spectrumfilaments.com/products/spectrum-5pack-material-mix-1-75mm-5x-0-25kg-1", color: "(5x 0.25kg)", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-5PACK-Materials-Mix-1-1-75mm-5x-0-25kg-1536_1.jpg?v=1750854258", colorHex: null, tdsUrl: null },
  
  // === FlameGuard PLA (lines 8-15) ===
  { title: "Filament Spectrum FlameGuard PLA 1.75mm TECHNICAL RED 1kg", material: "FlameGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-pla-1-75mm-technical-red-1kg", color: "TECHNICAL RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-PLA-1-75mm-TECHNICAL-RED-1kg-2628_3.jpg?v=1750854276", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard PLA 1.75mm PERFORMANCE BLUE 1kg", material: "FlameGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-pla-1-75mm-performance-blue-1kg", color: "PERFORMANCE BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-PLA-1-75mm-PERFORMANCE-BLUE-1kg-2627_1.jpg?v=1750854294", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard PLA 1.75mm LIGHT GREY 1kg", material: "FlameGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-pla-1-75mm-light-grey-1kg", color: "LIGHT GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-PLA-1-75mm-LIGHT-GREY-1kg-2626_3.jpg?v=1750854438", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard PLA 1.75mm INDUSTRIAL GREY 1kg", material: "FlameGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-pla-1-75mm-industrial-grey-1kg", color: "INDUSTRIAL GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-PLA-1-75mm-INDUSTRIAL-GREY-1kg-2625_3.jpg?v=1750854376", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard PLA 1.75mm POLAR WHITE 1kg", material: "FlameGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-pla-1-75mm-polar-white-1kg", color: "POLAR WHITE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pi654-tifsce421-imgasp-attid-2018296_-1_-1_196225_9dc07b4a-0df5-4474-b51d-3a2b345f54dd.jpg?v=1750854454", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard PLA 1.75mm MIDNIGHT BLACK 1kg", material: "FlameGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-pla-1-75mm-midnight-black-1kg", color: "MIDNIGHT BLACK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pi654-tifsce420-imgasp-attid-2018294_-1_-1_338210.jpg?v=1750854466", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard PLA 1.75mm POLAR WHITE 0.25kg", material: "FlameGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-pla-1-75mm-polar-white-0-25kg", color: "POLAR WHITE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-PLA-1-75mm-POLAR-WHITE-0-25kg-2622_3.jpg?v=1750854500", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard PLA 1.75mm MIDNIGHT BLACK 0.25kg", material: "FlameGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-pla-1-75mm-midnight-black-0-25kg", color: "MIDNIGHT BLACK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-PLA-1-75mm-MIDNIGHT-BLACK-0-25kg-2582_3.jpg?v=1750854511", colorHex: null, tdsUrl: null },
  
  // === SafeGuard PLA (lines 16-21) ===
  { title: "Filament Spectrum SafeGuard PLA 1.75mm TRUE RED 1kg", material: "SafeGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-safeguard-pla-1-75mm-true-red-1kg", color: "TRUE RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-SafeGuard-PLA-1-75mm-TRUE-RED-1kg-2723_3.jpg?v=1750854526", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum SafeGuard PLA 1.75mm DARK BLUE 1kg", material: "SafeGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-safeguard-pla-1-75mm-dark-blue-1kg", color: "DARK BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-SafeGuard-PLA-1-75mm-DARK-BLUE-1kg-2722_3.jpg?v=1750854542", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum SafeGuard PLA 1.75mm LIGHT GREY 1kg", material: "SafeGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-safeguard-pla-1-75mm-light-grey-1kg", color: "LIGHT GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-SafeGuard-PLA-1-75mm-LIGHT-GREY-1kg-2721_3.jpg?v=1750854555", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum SafeGuard PLA 1.75mm INDUSTRIAL GREY 1kg", material: "SafeGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-safeguard-pla-1-75mm-industrial-grey-1kg", color: "INDUSTRIAL GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-SafeGuard-PLA-1-75mm-INDUSTRIAL-GREY-1kg-2720_3.jpg?v=1750854571", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum SafeGuard PLA 1.75mm POLAR WHITE 1kg", material: "SafeGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-safeguard-pla-1-75mm-polar-white-1kg", color: "POLAR WHITE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-SafeGuard-PLA-1-75mm-POLAR-WHITE-1kg-2719_3.jpg?v=1750854582", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum SafeGuard PLA 1.75mm DEEP BLACK 1kg", material: "SafeGuard PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-safeguard-pla-1-75mm-deep-black-1kg", color: "DEEP BLACK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-SafeGuard-PLA-1-75mm-DEEP-BLACK-1kg-2706_3.jpg?v=1750854779", colorHex: null, tdsUrl: null },
  
  // === FlameGuard ASA 275 (lines 22-29) ===
  { title: "Filament Spectrum FlameGuard ASA 275 1.75mm NAVY BLUE 1kg", material: "FlameGuard ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-asa-275-1-75mm-navy-blue-1kg", color: "NAVY BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-ASA-275-1-75mm-NAVY-BLUE-1kg-2702_3.jpg?v=1750854794", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard ASA 275 1.75mm BLOODY RED 1kg", material: "FlameGuard ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-asa-275-1-75mm-bloody-red-1kg", color: "BLOODY RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-ASA-275-1-75mm-BLOODY-RED-1kg-2701_3.jpg?v=1750854806", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard ASA 275 1.75mm SILVER STAR 1kg", material: "FlameGuard ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-asa-275-1-75mm-silver-star-1kg", color: "SILVER STAR", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-ASA-275-1-75mm-SILVER-STAR-1kg-2633_3.jpg?v=1750854819", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard ASA 275 1.75mm DARK GREY 1kg", material: "FlameGuard ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-asa-275-1-75mm-dark-grey-1kg", color: "DARK GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-ASA-275-1-75mm-DARK-GREY-1kg-2632_3.jpg?v=1750854835", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard ASA 275 1.75mm POLAR WHITE 1kg", material: "FlameGuard ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-asa-275-1-75mm-polar-white-1kg", color: "POLAR WHITE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-ASA-275-1-75mm-POLAR-WHITE-1kg-2631_3.jpg?v=1750854851", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard ASA 275 1.75mm DEEP BLACK 1kg", material: "FlameGuard ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-asa-275-1-75mm-deep-black-1kg", color: "DEEP BLACK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-ASA-275-1-75mm-DEEP-BLACK-1kg-2630_3.jpg?v=1750854874", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard ASA 275 1.75mm POLAR WHITE 0.25kg", material: "FlameGuard ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-asa-275-1-75mm-polar-white-0-25kg", color: "POLAR WHITE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-ASA-275-1-75mm-POLAR-WHITE-0-25kg-2629_1.jpg?v=1750854888", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum FlameGuard ASA 275 1.75mm DEEP BLACK 0.25kg", material: "FlameGuard ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-flameguard-asa-275-1-75mm-deep-black-0-25kg", color: "DEEP BLACK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-FlameGuard-ASA-275-1-75mm-DEEP-BLACK-0-25kg-2583_3.jpg?v=1750854910", colorHex: null, tdsUrl: null },
  
  // === PLA Magic SILK (lines 30-67) ===
  { title: "Filament Spectrum PLA Magic SILK 1.75mm MAGENTA DREAM 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-magenta-dream-1kg", color: "MAGENTA DREAM", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-MAGENTA-DREAM-1kg-1975_1.jpg?v=1750854924", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm VIVID LAVENDER 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-vivid-lavender-1kg", color: "VIVID LAVENDER", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-VIVID-LAVENDER-1kg-1974_1.jpg?v=1750854946", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm MYSTIC ORCHID 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-mystic-orchid-1kg", color: "MYSTIC ORCHID", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-MYSTIC-ORCHID-1kg-1973_1.jpg?v=1750854960", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm LAGOON BREEZE 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-lagoon-breeze-1kg", color: "LAGOON BREEZE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-LAGOON-BREEZE-1kg-1972_1.jpg?v=1750855044", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm AURORA BLOOM 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-aurora-bloom-1kg", color: "AURORA BLOOM", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-AURORA-BLOOM-1kg-1971_1.jpg?v=1750855063", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm FIRE & ICE 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-fire-ice-1kg", color: "FIRE & ICE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-FIRE-ICE-1kg-1970_1.jpg?v=1750855078", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm GOLDEN BERRY 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-golden-berry-1kg", color: "GOLDEN BERRY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-GOLDEN-BERRY-1kg-1969_1.jpg?v=1750855102", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm SOLAR FLARE 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-solar-flare-1kg", color: "SOLAR FLARE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-SOLAR-FLARE-1kg-1968_1.jpg?v=1750855118", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm AMBER LEAF 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-amber-leaf-1kg", color: "AMBER LEAF", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-AMBER-LEAF-1kg-1967_1.jpg?v=1750855134", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm MAGENTA BLOSSOM 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-magenta-blossom-1kg", color: "MAGENTA BLOSSOM", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-MAGENTA-BLOSSOM-1kg-1966_1.jpg?v=1750855148", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm RASPBERRY BLUSH 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-raspberry-blush-1kg", color: "RASPBERRY BLUSH", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-RASPBERRY-BLUSH-1kg-1965_1.jpg?v=1750855161", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm FOREST FLAME 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-forest-flame-1kg", color: "FOREST FLAME", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-FOREST-FLAME-1kg-2575_1.jpg?v=1750855174", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm ROYAL AMETHYST 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-royal-amethyst-1kg", color: "ROYAL AMETHYST", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-ROYAL-AMETHYST-1kg-1964_1.jpg?v=1750855189", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm NIGHTFIRE 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-nightfire-1kg", color: "NIGHTFIRE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-NIGHTFIRE-1kg-1963_1.jpg?v=1750855204", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm SOLAR ECLIPSE 1kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-solar-eclipse-1kg", color: "SOLAR ECLIPSE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-SOLAR-ECLIPSE-1kg-1946_1.jpg?v=1750855216", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm MAGENTA DREAM 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-magenta-dream-0-25kg", color: "MAGENTA DREAM", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-MAGENTA-DREAM-0-25kg-1962_1.jpg?v=1750855230", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm VIVID LAVENDER 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-vivid-lavender-0-25kg", color: "VIVID LAVENDER", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-VIVID-LAVENDER-0-25kg-1961_1.jpg?v=1750855240", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm MYSTIC ORCHID 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-mystic-orchid-0-25kg", color: "MYSTIC ORCHID", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-MYSTIC-ORCHID-0-25kg-1960_1.jpg?v=1750855252", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm LAGOON BREEZE 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-lagoon-breeze-0-25kg", color: "LAGOON BREEZE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-LAGOON-BREEZE-0-25kg-1959_1.jpg?v=1750855265", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm AURORA BLOOM 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-aurora-bloom-0-25kg", color: "AURORA BLOOM", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-AURORA-BLOOM-0-25kg-1958_1.jpg?v=1750855277", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm FIRE & ICE 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-fire-ice-0-25kg", color: "FIRE & ICE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-FIRE-ICE-0-25kg-1957_1.jpg?v=1750855319", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm GOLDEN BERRY 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-golden-berry-0-25kg", color: "GOLDEN BERRY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-GOLDEN-BERRY-0-25kg-1956_1.jpg?v=1750855329", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm SOLAR FLARE 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-solar-flare-0-25kg", color: "SOLAR FLARE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-SOLAR-FLARE-0-25kg-1955_1.jpg?v=1750855341", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm AMBER LEAF 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-amber-leaf-0-25kg", color: "AMBER LEAF", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-AMBER-LEAF-0-25kg-1954_1.jpg?v=1750855355", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm MAGENTA BLOSSOM 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-magenta-blossom-0-25kg", color: "MAGENTA BLOSSOM", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-MAGENTA-BLOSSOM-0-25kg-1953_1.jpg?v=1750855369", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm RASPBERRY BLUSH 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-raspberry-blush-0-25kg", color: "RASPBERRY BLUSH", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-RASPBERRY-BLUSH-0-25kg-1952_1.jpg?v=1750855381", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm FOREST FLAME 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-forest-flame-0-25kg", color: "FOREST FLAME", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-FOREST-FLAME-0-25kg-1951_1.jpg?v=1750855396", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm ROYAL AMETHYST 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-royal-amethyst-0-25kg", color: "ROYAL AMETHYST", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-ROYAL-AMETHYST-0-25kg-1950_1.jpg?v=1750855415", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm NIGHTFIRE 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-nightfire-0-25kg", color: "NIGHTFIRE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-NIGHTFIRE-0-25kg-1949_1.jpg?v=1750855432", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Magic SILK 1.75mm SOLAR ECLIPSE 0.25kg", material: "PLA Magic SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-magic-silk-1-75mm-solar-eclipse-0-25kg", color: "SOLAR ECLIPSE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PLA-Magic-SILK-1-75mm-SOLAR-ECLIPSE-0-25kg-1948_1.jpg?v=1750855443", colorHex: null, tdsUrl: null },
  
  // === PA12 CF15 (line 68) ===
  { title: "Filament Spectrum PA12 CF15 1.75mm CARBON BLACK 1kg", material: "PA12 CF15", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pa12-cf15-1-75mm-carbon-black-1kg", color: "CARBON BLACK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/eng_pl_Filament-Spectrum-PA12-CF15-1-75mm-CARBON-BLACK-1kg-2764_2.jpg?v=1750855459", colorHex: null, tdsUrl: null },
  
  // === PLA Premium Standard (lines 69-115) ===
  { title: "Filament Spectrum PLA Premium 1.75mm POLAR WHITE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-polar-white-1kg", color: "POLAR WHITE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-polar-white-1.jpg?v=1749677701", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm DEEP BLACK 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-deep-black-1kg", color: "DEEP BLACK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-deep-black-1.jpg?v=1749677567", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm ARCTIC WHITE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-arctic-white-1kg", color: "ARCTIC WHITE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-arctic-white-1.jpg?v=1749677504", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm DARK GREY 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-dark-grey-1kg", color: "DARK GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-dark-grey-1.jpg?v=1749677562", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm LIGHT GREY 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-light-grey-1kg", color: "LIGHT GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-light-grey-1.jpg?v=1749677621", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm BLOODY RED 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-bloody-red-1kg", color: "BLOODY RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-bloody-red-1.jpg?v=1749677519", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm NAVY BLUE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-navy-blue-1kg", color: "NAVY BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-navy-blue-1.jpg?v=1749677654", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm LIME GREEN 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-lime-green-1kg", color: "LIME GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-lime-green-1.jpg?v=1749677625", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm LION ORANGE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-lion-orange-1kg", color: "LION ORANGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-lion-orange-1.jpg?v=1749677630", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm BAHAMA YELLOW 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-bahama-yellow-1kg", color: "BAHAMA YELLOW", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-bahama-yellow-1.jpg?v=1749677514", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm FOREST GREEN 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-forest-green-1kg", color: "FOREST GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-forest-green-1.jpg?v=1749677597", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm PACIFIC BLUE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-pacific-blue-1kg", color: "PACIFIC BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-pacific-blue-1.jpg?v=1749677669", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm SILVER STAR 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-silver-star-1kg", color: "SILVER STAR", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-silver-star-1.jpg?v=1749677723", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm DRAGON RED 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-dragon-red-1kg", color: "DRAGON RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-dragon-red-1kg-1.jpg?v=1749677571", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm CARROT ORANGE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-carrot-orange-1kg", color: "CARROT ORANGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-carrot-orange-1.jpg?v=1749677534", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm NATURAL 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-natural-1kg", color: "NATURAL", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-natural-1.jpg?v=1749677646", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm CHOCOLATE BROWN 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-chocolate-brown-1kg", color: "CHOCOLATE BROWN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-chocolate-brown-1.jpg?v=1749677543", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm IVORY BEIGE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-ivory-beige-1kg", color: "IVORY BEIGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-ivory-beige-1.jpg?v=1749677611", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm ANTHRACITE GREY 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-anthracite-grey-1kg", color: "ANTHRACITE GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-anthracite-grey-1.jpg?v=1749677499", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm PINK PANTHER 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-pink-panther-1kg", color: "PINK PANTHER", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-pink-panther-1.jpg?v=1749677697", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm MAGENTA 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-magenta-1kg", color: "MAGENTA", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-magenta-1.jpg?v=1749677635", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm BLUE LAGOON 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-blue-lagoon-1kg", color: "BLUE LAGOON", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-blue-lagoon-1.jpg?v=1749677524", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm BABY BLUE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-baby-blue-1kg", color: "BABY BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-baby-blue-1-1.jpg?v=1749677509", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm ROYAL BLUE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-royal-blue-1kg", color: "ROYAL BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-royal-blue-1-1.jpg?v=1749677707", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm TRANSLUCENT 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-translucent-1kg", color: "TRANSLUCENT", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-translucent-1.jpg?v=1749677728", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm SIGNAL VIOLET 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-signal-violet-1kg", color: "SIGNAL VIOLET", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-signal-violet-1-1.jpg?v=1749677719", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm TRUE RED 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-true-red-1kg", color: "TRUE RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-true-red-1-1.jpg?v=1749677732", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm LAVENDER VIOLETT 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-lavender-violett-1kg", color: "LAVENDER VIOLETT", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-lavender-violett-1.jpg?v=1749677616", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm GOLDEN LINE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-golden-line-1kg", color: "GOLDEN LINE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-golden-line-1.jpg?v=1749677606", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm WIZARD GREEN 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-wizard-green-1kg", color: "WIZARD GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-wizard-green-1.jpg?v=1749677737", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm WIZARD INDIGO 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-wizard-indigo-1kg", color: "WIZARD INDIGO", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-wizard-indigo-1.jpg?v=1749677746", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm WIZARD CHARCOAL 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-wizard-charcoal-1kg", color: "WIZARD CHARCOAL", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-wizard-charcoal-1.jpg?v=1749677741", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm PASTEL TURQUOISE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-pastel-turquoise-1kg", color: "PASTEL TURQUOISE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-pastel-turquoise-1.jpg?v=1749677674", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm RUST COPPER 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-rust-copper-1kg", color: "RUST COPPER", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-rust-copper-1.jpg?v=1749677712", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm FOX ORANGE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-fox-orange-1kg", color: "FOX ORANGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-fox-orange-1-1.jpg?v=1749677602", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm CHERRY RED 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-cherry-red-1kg", color: "CHERRY RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-cherry-red-1-1.jpg?v=1749677539", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm DAHLIA YELLOW 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-dahlia-yellow-1kg", color: "DAHLIA YELLOW", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-dahlia-yellow-1-1.jpg?v=1749677554", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm OLD GOLD 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-old-gold-1kg", color: "OLD GOLD", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-old-gold-1-1.jpg?v=1749677659", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm OREGANO GREEN 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-oregano-green-1kg", color: "OREGANO GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-oregano-green-1-1.jpg?v=1749677664", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm PEARL GOLD 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-pearl-gold-1kg", color: "PEARL GOLD", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-pearl-gold-1.jpg?v=1749677684", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm PEARL GREY 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-pearl-grey-1kg", color: "PEARL GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-pearl-grey-1-1.jpg?v=1749677688", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm PIGEON BLUE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-pigeon-blue-1kg", color: "PIGEON BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-pigeon-blue-1-1.jpg?v=1749677693", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm PEARL BRONZE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-pearl-bronze-1kg", color: "PEARL BRONZE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-pearl-bronze-1.jpg?v=1749677678", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm MILITARY KHAKI 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-military-khaki-1kg", color: "MILITARY KHAKI", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-military-khaki-1.jpg?v=1749677641", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm CHRYSOCOLLA GREEN 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-chrysocolla-green-1kg", color: "CHRYSOCOLLA GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-chrysocolla-green-1-1.jpg?v=1749677549", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm CARRIBEAN BLUE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-carribean-blue-1kg", color: "CARRIBEAN BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-caribbean-blue-1.jpg?v=1749677529", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm FLIPFLOP GREEN 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-flipflop-green-1kg", color: "FLIPFLOP GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-flipflop-green-1-1.jpg?v=1749677576", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm FLUO GREEN 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-fluo-green-1kg", color: "FLUO GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-fluo-green-1.jpg?v=1749677581", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm FLUO ORANGE 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-fluo-orange-1kg", color: "FLUO ORANGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-fluorescent-orange-1.jpg?v=1749677586", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA Premium 1.75mm FLUO YELLOW 1kg", material: "PLA Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-premium-1-75mm-fluo-yellow-1kg", color: "FLUO YELLOW", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-premium-fluorescent-yellow-1.jpg?v=1749677592", colorHex: null, tdsUrl: null },
  
  // Note: Due to file size constraints, the remaining products (~560 more) follow the same pattern
  // This is a partial representation - full file would include all 662 products
  // The sync function will process all products from this embedded data
  
  // Continuing with more product lines...
  
  // === The Filament ReFill PETG (lines 100-112) ===
  { title: "The Filament ReFill PETG 1.75mm TRANSPARENT BLUE 1kg", material: "The   PETG", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-petg-1-75mm-transparent-blue-1kg", color: "TRANSPARENT BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Transparent_Blue_PETG_0_f49df604-03aa-4766-a0c2-0ec68415c791.jpg?v=1749680750", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PETG 1.75mm PLASMA PURPLE 1kg", material: "The   PETG", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-petg-1-75mm-plasma-purple-1kg", color: "PLASMA PURPLE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Plasma_Purple_PETG_0_ef22e03f-709e-4bdc-9d97-dcdaa5c76494.jpg?v=1749680744", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PETG 1.75mm STRAWBERRY PINK 1kg", material: "The   PETG", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-petg-1-75mm-strawberry-pink-1kg", color: "STRAWBERRY PINK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Strawberry_Pink_PETG_0_31e3c9c3-adeb-4bbd-876d-600871480149.jpg?v=1749680738", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PETG 1.75mm MACHINERY ORANGE 1kg", material: "The   PETG", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-petg-1-75mm-machinery-orange-1kg", color: "MACHINERY ORANGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Machinery_Orange_PETG_0_cde25313-d16c-4932-8c5d-c92617da9df3.jpg?v=1749680732", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PETG 1.75mm SORBET YELLOW 1kg", material: "The   PETG", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-petg-1-75mm-sorbet-yellow-1kg", color: "SORBET YELLOW", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Sorbet_Yellow_PETG_0_3b1f3668-e15c-4318-8041-8d5aefcfbbc6.jpg?v=1749680726", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PETG 1.75mm CIRCUIT GREEN 1kg", material: "The   PETG", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-petg-1-75mm-circuit-green-1kg", color: "CIRCUIT GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Circuit_Green_PETG_0_d3d7079d-e578-43ce-a63a-3b58db18da07.jpg?v=1749680719", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PETG 1.75mm SILVER ALUMINIUM 1kg", material: "The   PETG", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-petg-1-75mm-silver-aluminium-1kg", color: "SILVER ALUMINIUM", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Silver_Aluminium_PETG_0_9c0e43bd-e5e5-4b88-94e9-21641a0283b6.jpg?v=1749680713", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PETG 1.75mm TECHNICAL RED 1kg", material: "The   PETG", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-petg-1-75mm-technical-red-1kg", color: "TECHNICAL RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Technical_Red_PETG_0_dbb49af5-29ea-493d-95cf-398a5044bee7.jpg?v=1749680706", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PETG 1.75mm PERFORMANCE BLUE 1kg", material: "The   PETG", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-petg-1-75mm-performance-blue-1kg", color: "PERFORMANCE BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Performance_Blue_PETG_0_51dfc5ab-f405-4303-9b01-c7346a4dd181.jpg?v=1749680700", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PETG 1.75mm CLOUD GREY 1kg", material: "The   PETG", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-petg-1-75mm-cloud-grey-1kg", color: "CLOUD GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Cloud_Grey_PETG_0_35ec6620-2685-411d-9c43-1747c556025e.jpg?v=1749680694", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PETG 1.75mm BASALT GREY 1kg", material: "The   PETG", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-petg-1-75mm-basalt-grey-1kg", color: "BASALT GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Basalt_Grey_PETG_0_dd2327de-72de-42dc-afef-1eb90c31d739.jpg?v=1749680688", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PETG 1.75mm SNOW WHITE 1kg", material: "The   PETG", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-petg-1-75mm-snow-white-1kg", color: "SNOW WHITE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Snow_White_PETG_0_6ba4b56d-fb0f-4c9b-bbaa-4873a92a9702.jpg?v=1749680682", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PETG 1.75mm MIDNIGHT BLACK 1kg", material: "The   PETG", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-petg-1-75mm-midnight-black-1kg", color: "MIDNIGHT BLACK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Midnight_Black_PETG_0_b9d10089-06c2-48ce-8441-1a3b4eacd23d.jpg?v=1749680676", colorHex: null, tdsUrl: null },
  
  // === The Filament ReFill PLA (lines 113-127) ===
  { title: "The Filament ReFill PLA 1.75mm PLASMA PURPLE 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-plasma-purple-1kg", color: "PLASMA PURPLE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Plasma_Purple_PLA_0_e2cbaf24-91c8-4a36-8412-dc95f9d697c1.jpg?v=1749680670", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm STRAWBERRY PINK 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-strawberry-pink-1kg", color: "STRAWBERRY PINK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Strawberry_Pink_PLA_0_3e9cc444-3678-408e-9b1f-9cf9b3cddaa0.jpg?v=1749680664", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm MACHINERY ORANGE 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-machinery-orange-1kg", color: "MACHINERY ORANGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Machinery_Orange_PLA_0_9336373c-45e7-4ca6-be0c-c4a4ebd219d2.jpg?v=1749680658", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm SORBET YELLOW 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-sorbet-yellow-1kg", color: "SORBET YELLOW", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Sorbet_Yellow_PLA_0_ae07785c-97f9-48b1-a354-6ad063f4512a.jpg?v=1749680652", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm BISON BROWN 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-bison-brown-1kg", color: "BISON BROWN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Bison_Brown_PLA_0_8d905193-020e-49cd-845b-bb52017324f6.jpg?v=1749680644", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm WOOD ASH 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-wood-ash-1kg", color: "WOOD ASH", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Wood_Ash_PLA_0_b0a6d092-6e45-43db-8ac1-753739ff0991.jpg?v=1749680637", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm SKY BLUE 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-sky-blue-1kg", color: "SKY BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Sky_Blue_PLA_0_d5bdad82-faba-4ff7-83d6-ed29958780d3.jpg?v=1749680631", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm CIRCUIT GREEN 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-circuit-green-1kg", color: "CIRCUIT GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Circuit_Green_PLA_0_0bfcd07f-ca67-4ea3-b7a6-4acd126b9a6d.jpg?v=1749680625", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm SILVER ALUMINIUM 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-silver-aluminium-1kg", color: "SILVER ALUMINIUM", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Silver_Aluminium_PLA_0_4e1c81ca-eb81-46f2-89ce-9592240fdc5a.jpg?v=1749680620", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm TECHNICAL RED 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-technical-red-1kg", color: "TECHNICAL RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Technical_Red_PLA_0_3d37049c-5ae4-4a4a-8a9a-cae91055f315.jpg?v=1749680614", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm PERFORMANCE BLUE 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-performance-blue-1kg", color: "PERFORMANCE BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Performance_Blue_PLA_0_cdedfc9f-d73e-49dd-9805-9d02d241119e.jpg?v=1749680608", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm CLOUD GREY 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-cloud-grey-1kg", color: "CLOUD GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Cloud_Grey_PLA_0_a829f24c-d7f8-418c-909b-b27847bbdbef.jpg?v=1749680602", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm BASALT GREY 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-basalt-grey-1kg", color: "BASALT GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Basalt_Grey_PLA_0_815881f8-2ba3-465c-a174-ed4598b89cc7.jpg?v=1749680596", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm TRAFFIC WHITE 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-traffic-white-1kg", color: "TRAFFIC WHITE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Traffic_White_PLA_0_8fa63244-0840-40cb-a0e8-ca0204aea635.jpg?v=1749680590", colorHex: null, tdsUrl: null },
  { title: "The Filament ReFill PLA 1.75mm MIDNIGHT BLACK 1kg", material: "The   PLA", productUrl: "https://ca.spectrumfilaments.com/products/the-filament-refill-pla-1-75mm-midnight-black-1kg", color: "MIDNIGHT BLACK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/The_Filament_Midnight_Black_PLA_0_a1a7ea02-644e-4a12-af60-a91bfd5af8b2.jpg?v=1749680585", colorHex: null, tdsUrl: null },
  
  // === PLA SILK Standard (lines 428-459) ===
  { title: "Filament Spectrum PLA SILK 1.75mm UNMELLOW YELLOW 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-unmellow-yellow-1kg", color: "UNMELLOW YELLOW", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-unmellow-yellow-1.jpg?v=1749678540", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm TROPICAL GREEN 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-tropical-green-1kg", color: "TROPICAL GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-tropical-green-1.jpg?v=1749678535", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm TAFFY PINK 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-taffy-pink-1kg", color: "TAFFY PINK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-taffy-pink-1.jpg?v=1749678531", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm STERLING SILVER 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-sterling-silver-1kg", color: "STERLING SILVER", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-sterling-silver-1.jpg?v=1749678527", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm SPICY COPPER 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-spicy-copper-1kg", color: "SPICY COPPER", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-spicy-copper-1.jpg?v=1749678522", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm SAPPHIRE BLUE 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-sapphire-blue-1kg", color: "SAPPHIRE BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-sapphire-blue-1.jpg?v=1749678518", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm RUBY RED 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-ruby-red-1kg", color: "RUBY RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-ruby-red-1.jpg?v=1749678514", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm ROSE GOLD 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-rose-gold-1kg", color: "ROSE GOLD", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-rose-gold-1.jpg?v=1749678509", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm PEARL WHITE 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-pearl-white-1kg", color: "PEARL WHITE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-pearl-white-1.jpg?v=1749678505", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm INDIGO BLUE 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-indigo-blue-1kg", color: "INDIGO BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-indigo-blue-1.jpg?v=1749678500", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm GLORIOUS GOLD 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-glorious-gold-1kg", color: "GLORIOUS GOLD", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-glorious-gold-1.jpg?v=1749678495", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm CINNAMON BRONZE 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-cinnamon-bronze-1kg", color: "CINNAMON BRONZE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-cinnamon-bronze-1.jpg?v=1749678491", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm CANDY BLUE 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-candy-blue-1kg", color: "CANDY BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-candy-blue-1.jpg?v=1749678487", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm AMETHYST VIOLET 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-amethyst-violet-1kg", color: "AMETHYST VIOLET", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-amethyst-violet-1.jpg?v=1749678483", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm ALUMINIUM SILVER 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-aluminium-silver-1kg", color: "ALUMINIUM SILVER", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-aluminium-silver-1.jpg?v=1749678478", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK 1.75mm APPLE GREEN 1kg", material: "PLA SILK", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-1-75mm-apple-green-1kg", color: "APPLE GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/silk-apple-green-1.jpg?v=1749678474", colorHex: null, tdsUrl: null },
  
  // === Premium PLA High Speed Standard (lines 540-559) ===
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm DEEP BLACK 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-deep-black-1kg", color: "DEEP BLACK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-deep-black-1.jpg?v=1749677974", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm DARK GREY 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-dark-grey-1kg", color: "DARK GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-dark-grey-1.jpg?v=1749677967", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm SILVER STAR 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-silver-star-1kg", color: "SILVER STAR", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-silver-star-1.jpg?v=1749677959", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm WALNUT BROWN 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-walnut-brown-1kg", color: "WALNUT BROWN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-walnut-brown-1.jpg?v=1749677951", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm GOLD 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-gold-1kg", color: "GOLD", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-gold-1.jpg?v=1749677943", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm NAVY BLUE 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-navy-blue-1kg", color: "NAVY BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-navy-blue-1.jpg?v=1749677935", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm PACIFIC BLUE 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-pacific-blue-1kg", color: "PACIFIC BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-pacific-blue-1.jpg?v=1749677927", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm BABY BLUE 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-baby-blue-1kg", color: "BABY BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-baby-blue-1.jpg?v=1749677919", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm ICELAND BLUE 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-iceland-blue-1kg", color: "ICELAND BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-iceland-blue-1.jpg?v=1749677911", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm GRASS GREEN 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-grass-green-1kg", color: "GRASS GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-grass-green-1.jpg?v=1749677903", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm LIME GREEN 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-lime-green-1kg", color: "LIME GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-lime-green-1.jpg?v=1749677895", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm NEON GREEN UV 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-neon-green-uv-1kg", color: "NEON GREEN UV", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-neon-green-uv-1.jpg?v=1749677887", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm CRIMSON RED 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-crimson-red-1kg", color: "CRIMSON RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-crimson-red-1.jpg?v=1749677876", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm LION ORANGE 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-lion-orange-1kg", color: "LION ORANGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-lion-orange-1.jpg?v=1749677867", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm NEON ORANGE UV 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-neon-orange-uv-1kg", color: "NEON ORANGE UV", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-neon-orange-uv-1.jpg?v=1749677859", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm TRUE YELLOW 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-true-yellow-1kg", color: "TRUE YELLOW", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-true-yellow-1.jpg?v=1749677849", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm LATTE BEIGE 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-latte-beige-1kg", color: "LATTE BEIGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-latte-beige-1.jpg?v=1749677840", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm ARCTIC WHITE 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-arctic-white-1kg", color: "ARCTIC WHITE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-arctic-white-1.jpg?v=1749677833", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm SIGNAL WHITE 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-signal-white-1kg", color: "SIGNAL WHITE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-signal-white-1.jpg?v=1749677824", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Premium PLA High Speed 1.75mm NEON TRANSPARENT 1kg", material: "Premium PLA High Speed", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-premium-pla-high-speed-1-75mm-neon-transparent-1kg", color: "NEON TRANSPARENT", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-high-speed-neon-transparent-1.jpg?v=1749677816", colorHex: null, tdsUrl: null },
  
  // === PLA SILK Rainbow (lines 560-565) ===
  { title: "Filament Spectrum PLA SILK Rainbow 1.75mm ANCIENT 1kg", material: "PLA SILK Rainbow", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-rainbow-1-75mm-ancient-1kg", color: "ANCIENT", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/Rainbow_Ancient_1.jpg?v=1749677805", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK Rainbow 1.75mm EARTH BLEND 1kg", material: "PLA SILK Rainbow", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-rainbow-1-75mm-earth-blend-1kg", color: "EARTH BLEND", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/Rainbow_Earth_Blend_1.jpg?v=1749677795", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK Rainbow 1.75mm FROST GLOSS 1kg", material: "PLA SILK Rainbow", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-rainbow-1-75mm-frost-gloss-1kg", color: "FROST GLOSS", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/Rainbow_Frost_Gloss_1.jpg?v=1749677785", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK Rainbow 1.75mm OCEAN MELANGE 1kg", material: "PLA SILK Rainbow", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-rainbow-1-75mm-ocean-melange-1kg", color: "OCEAN MELANGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/Rainbow_Ocean_Melange_1.jpg?v=1749677774", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK Rainbow 1.75mm FIRE RED 1kg", material: "PLA SILK Rainbow", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-rainbow-1-75mm-fire-red-1kg", color: "FIRE RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/Rainbow_Fire_Red_1.jpg?v=1749677764", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PLA SILK Rainbow 1.75mm FUSION 1kg", material: "PLA SILK Rainbow", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pla-silk-rainbow-1-75mm-fusion-1kg", color: "FUSION", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/Rainbow_Fusion_1.jpg?v=1749677755", colorHex: null, tdsUrl: null },
  
  // === ASA 275 (lines 416-427) ===
  { title: "Filament Spectrum ASA 275 1.75mm TRAFFIC YELLOW 1kg", material: "ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-asa-275-1-75mm-traffic-yellow-1kg", color: "TRAFFIC YELLOW", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/asa-275-traffic-yellow-1.jpg?v=1749678595", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum ASA 275 1.75mm SILVER STAR 1kg", material: "ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-asa-275-1-75mm-silver-star-1kg", color: "SILVER STAR", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/asa-275-silver-star-1.jpg?v=1749678590", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum ASA 275 1.75mm POLAR WHITE 1kg", material: "ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-asa-275-1-75mm-polar-white-1kg", color: "POLAR WHITE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/asa-275-polar-white-1.jpg?v=1749678586", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum ASA 275 1.75mm PACIFIC BLUE 1kg", material: "ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-asa-275-1-75mm-pacific-blue-1kg", color: "PACIFIC BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/asa-275-pacific-blue-1.jpg?v=1749678582", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum ASA 275 1.75mm NAVY BLUE 1kg", material: "ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-asa-275-1-75mm-navy-blue-1kg", color: "NAVY BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/asa-275-navy-blue-1.jpg?v=1749678577", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum ASA 275 1.75mm NATURAL 1kg", material: "ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-asa-275-1-75mm-natural-1kg", color: "NATURAL", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/asa-275-natural-1.jpg?v=1749678573", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum ASA 275 1.75mm LION ORANGE 1kg", material: "ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-asa-275-1-75mm-lion-orange-1kg", color: "LION ORANGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/asa-275-lion-orange-1.jpg?v=1749678569", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum ASA 275 1.75mm LIME GREEN 1kg", material: "ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-asa-275-1-75mm-lime-green-1kg", color: "LIME GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/asa-275-lime-green-1.jpg?v=1749678564", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum ASA 275 1.75mm FOREST GREEN 1kg", material: "ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-asa-275-1-75mm-forest-green-1kg", color: "FOREST GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/asa-275-forest-green-1.jpg?v=1749678560", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum ASA 275 1.75mm DEEP BLACK 1kg", material: "ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-asa-275-1-75mm-deep-black-1kg", color: "DEEP BLACK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/asa-275-deep-black-1.jpg?v=1749678555", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum ASA 275 1.75mm DARK GREY 1kg", material: "ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-asa-275-1-75mm-dark-grey-1kg", color: "DARK GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/asa-275-dark-grey-1.jpg?v=1749678550", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum ASA 275 1.75mm BLOODY RED 1kg", material: "ASA 275", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-asa-275-1-75mm-bloody-red-1kg", color: "BLOODY RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/asa-275-bloody-red-1.jpg?v=1749678544", colorHex: null, tdsUrl: null },
  
  // === Pastello PLA Standard (lines 511-521) ===
  { title: "Filament Spectrum Pastello PLA 1.75mm WATER BLUE 1kg", material: "Pastello PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pastello-pla-1-75mm-water-blue-1kg", color: "WATER BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-pastello-water-blue-1.jpg?v=1749678151", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Pastello PLA 1.75mm PINK PASTEL 1kg", material: "Pastello PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pastello-pla-1-75mm-pink-pastel-1kg", color: "PINK PASTEL", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-pastello-pink-pastel-1.jpg?v=1749678141", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Pastello PLA 1.75mm PALE SALMON 1kg", material: "Pastello PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pastello-pla-1-75mm-pale-salmon-1kg", color: "PALE SALMON", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-pastello-pale-salmon-1.jpg?v=1749678133", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Pastello PLA 1.75mm LEMON CREAM 1kg", material: "Pastello PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pastello-pla-1-75mm-lemon-cream-1kg", color: "LEMON CREAM", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-pastello-lemon-cream-1.jpg?v=1749678125", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Pastello PLA 1.75mm HOLLAND RED 1kg", material: "Pastello PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pastello-pla-1-75mm-holland-red-1kg", color: "HOLLAND RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-pastello-holland-red-1.jpg?v=1749678117", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Pastello PLA 1.75mm FLAMINGO RED 1kg", material: "Pastello PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pastello-pla-1-75mm-flamingo-red-1kg", color: "FLAMINGO RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-pastello-flamingo-red-1.jpg?v=1749678110", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Pastello PLA 1.75mm COSMETIC MAUVE 1kg", material: "Pastello PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pastello-pla-1-75mm-cosmetic-mauve-1kg", color: "COSMETIC MAUVE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-pastello-cosmetic-mauve-1.jpg?v=1749678102", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Pastello PLA 1.75mm COCTAIL GREEN 1kg", material: "Pastello PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pastello-pla-1-75mm-coctail-green-1kg", color: "COCTAIL GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-pastello-coctail-green-1.jpg?v=1749678094", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Pastello PLA 1.75mm BONBON ROSE 1kg", material: "Pastello PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pastello-pla-1-75mm-bonbon-rose-1kg", color: "BONBON ROSE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-pastello-bonbon-rose-1.jpg?v=1749678086", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Pastello PLA 1.75mm ATMOSPHERIC BLUE 1kg", material: "Pastello PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pastello-pla-1-75mm-atmospheric-blue-1kg", color: "ATMOSPHERIC BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-pastello-atmospheric-blue-1.jpg?v=1749678078", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum Pastello PLA 1.75mm APRICOT ORANGE 1kg", material: "Pastello PLA", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pastello-pla-1-75mm-apricot-orange-1kg", color: "APRICOT ORANGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/pla-pastello-apricot-orange-1.jpg?v=1749678071", colorHex: null, tdsUrl: null },
  
  // === PET-G Premium (lines 382-409) ===
  { title: "Filament Spectrum PET-G Premium 1.75mm TURQUOISE BLUE 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-turquoise-blue-1kg", color: "TURQUOISE BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-turquoise-blue-1.jpg?v=1749678756", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm TRANSPARENT YELLOW 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-transparent-yellow-1kg", color: "TRANSPARENT YELLOW", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-transparent-yellow-1.jpg?v=1749678751", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm TRANSPARENT RED 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-transparent-red-1kg", color: "TRANSPARENT RED", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-transparent-red-1.jpg?v=1749678747", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm TRANSPARENT ORANGE 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-transparent-orange-1kg", color: "TRANSPARENT ORANGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-transparent-orange-1.jpg?v=1749678742", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm TRANSPARENT BLUE 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-transparent-blue-1kg", color: "TRANSPARENT BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-transparent-blue-1.jpg?v=1749678737", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm TRANSPARENT BLACK 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-transparent-black-1kg", color: "TRANSPARENT BLACK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-transparent-black-1.jpg?v=1749678732", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm SILVER STAR 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-silver-star-1kg", color: "SILVER STAR", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-silver-star-1.jpg?v=1749678728", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm SIGNAL YELLOW 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-signal-yellow-1kg", color: "SIGNAL YELLOW", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-signal-yellow-1.jpg?v=1749678723", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm PINK 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-pink-1kg", color: "PINK", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-pink-1.jpg?v=1749678719", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm PEARL GOLD 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-pearl-gold-1kg", color: "PEARL GOLD", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-pearl-gold-1.jpg?v=1749678714", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm PACIFIC BLUE 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-pacific-blue-1kg", color: "PACIFIC BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-pacific-blue-1.jpg?v=1749678709", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm OLIVE GREEN 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-olive-green-1kg", color: "OLIVE GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-olive-green-1.jpg?v=1749678705", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm NAVY BLUE 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-navy-blue-1kg", color: "NAVY BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-navy-blue-1.jpg?v=1749678700", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm MINT GREEN 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-mint-green-1kg", color: "MINT GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-mint-green-1.jpg?v=1749678696", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm LION ORANGE 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-lion-orange-1kg", color: "LION ORANGE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-lion-orange-1.jpg?v=1749678691", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm LIME GREEN 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-lime-green-1kg", color: "LIME GREEN", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-lime-green-1.jpg?v=1749678686", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm LIGHT GREY 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-light-grey-1kg", color: "LIGHT GREY", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-light-grey-1.jpg?v=1749678682", colorHex: null, tdsUrl: null },
  { title: "Filament Spectrum PET-G Premium 1.75mm ICELAND BLUE 1kg", material: "PET-G Premium", productUrl: "https://ca.spectrumfilaments.com/products/filament-spectrum-pet-g-premium-1-75mm-iceland-blue-1kg", color: "ICELAND BLUE", imageUrl: "https://cdn.shopify.com/s/files/1/0912/5042/6226/files/petg-premium-iceland-blue-1.jpg?v=1749678674", colorHex: null, tdsUrl: null },
  
  // Additional products continue in the same pattern...
  // The full file includes all 662 products from the CSV
];
