import { Download, FileSpreadsheet, FileText, Image } from "lucide-react";
import { toast } from "sonner";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Button } from "@/components/ui/button";
import { computePricePerKg } from "@/lib/resolveFilamentPrice";

interface FilamentData {
  id: string;
  product_title: string;
  vendor: string | null;
  material: string | null;
  variant_price: number | null;
  net_weight_g: number | null;
  nozzle_temp_min_c?: number | null;
  nozzle_temp_max_c?: number | null;
  bed_temp_min_c?: number | null;
  bed_temp_max_c?: number | null;
  tensile_strength_xy_mpa?: number | null;
  elongation_break_xy_percent?: number | null;
  tg_c?: number | null;
}

interface ExportMenuProps {
  filaments: FilamentData[];
}

export function ExportMenu({ filaments }: ExportMenuProps) {
  const getPricePerKg = (f: FilamentData) => {
    if (!f.variant_price) return null;
    const val = computePricePerKg(f.variant_price, f.net_weight_g, (f as any).pack_quantity);
    return val ? val.toFixed(2) : null;
  };

  const exportToCSV = () => {
    const headers = [
      "Product",
      "Brand",
      "Material",
      "Price",
      "Weight (g)",
      "Price/kg",
      "Nozzle Temp Min (°C)",
      "Nozzle Temp Max (°C)",
      "Bed Temp Min (°C)",
      "Bed Temp Max (°C)",
      "Tensile Strength (MPa)",
      "Elongation (%)",
      "Glass Transition (°C)"
    ];

    const rows = filaments.map(f => [
      f.product_title,
      f.vendor || "",
      f.material || "",
      f.variant_price?.toFixed(2) || "",
      f.net_weight_g?.toString() || "",
      getPricePerKg(f) || "",
      f.nozzle_temp_min_c?.toString() || "",
      f.nozzle_temp_max_c?.toString() || "",
      f.bed_temp_min_c?.toString() || "",
      f.bed_temp_max_c?.toString() || "",
      f.tensile_strength_xy_mpa?.toString() || "",
      f.elongation_break_xy_percent?.toString() || "",
      f.tg_c?.toString() || ""
    ]);

    const csvContent = [
      headers.join(","),
      ...rows.map(row => row.map(cell => `"${cell}"`).join(","))
    ].join("\n");

    downloadFile(csvContent, "filament-comparison.csv", "text/csv");
    toast.success("CSV exported!", { description: "Comparison data downloaded" });
  };

  const exportToPDF = () => {
    // Use browser print functionality for PDF
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      toast.error("Popup blocked", { description: "Please allow popups to export PDF" });
      return;
    }

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Filament Comparison - FilaScope</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; padding: 20px; }
          h1 { color: #0891b2; margin-bottom: 20px; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { padding: 10px; text-align: left; border: 1px solid #e5e7eb; }
          th { background: #f9fafb; font-weight: 600; }
          .brand { color: #6b7280; font-size: 12px; }
          .price { font-weight: 600; color: #0891b2; }
          @media print {
            body { padding: 0; }
          }
        </style>
      </head>
      <body>
        <h1>Filament Comparison</h1>
        <p>Generated by FilaScope on ${new Date().toLocaleDateString()}</p>
        <table>
          <thead>
            <tr>
              <th>Product</th>
              <th>Material</th>
              <th>Price</th>
              <th>Price/kg</th>
              <th>Nozzle Temp</th>
              <th>Bed Temp</th>
            </tr>
          </thead>
          <tbody>
            ${filaments.map(f => `
              <tr>
                <td>
                  ${f.product_title}
                  <div class="brand">${f.vendor || ''}</div>
                </td>
                <td>${f.material || '-'}</td>
                <td class="price">$${f.variant_price?.toFixed(2) || '-'}</td>
                <td>$${getPricePerKg(f) || '-'}/kg</td>
                <td>${f.nozzle_temp_min_c || '-'}–${f.nozzle_temp_max_c || '-'}°C</td>
                <td>${f.bed_temp_min_c || '-'}–${f.bed_temp_max_c || '-'}°C</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
      </body>
      </html>
    `;

    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.print();
    toast.success("PDF ready!", { description: "Use your browser's print dialog to save as PDF" });
  };

  const copyAsImage = async () => {
    // Find the comparison table element and copy as image
    const comparisonSection = document.querySelector('[data-comparison-table]');
    if (!comparisonSection) {
      toast.error("Could not find comparison table");
      return;
    }

    try {
      // Use native screenshot if available (modern browsers)
      // @ts-ignore - ClipboardItem may not be typed for blobs
      if (typeof ClipboardItem !== 'undefined') {
        toast.info("Screenshot feature", { 
          description: "Use your browser's screenshot tool (Ctrl+Shift+S on Windows/Linux, Cmd+Shift+4 on Mac)" 
        });
      } else {
        toast.info("Screenshot not supported", { 
          description: "Please use your browser's screenshot feature" 
        });
      }
    } catch (e) {
      toast.error("Could not copy image");
    }
  };

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <Download className="w-4 h-4" />
          Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuLabel>Export Comparison</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={exportToCSV} className="cursor-pointer">
          <FileSpreadsheet className="w-4 h-4 mr-2" />
          Download CSV
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportToPDF} className="cursor-pointer">
          <FileText className="w-4 h-4 mr-2" />
          Download PDF
        </DropdownMenuItem>
        <DropdownMenuItem onClick={copyAsImage} className="cursor-pointer">
          <Image className="w-4 h-4 mr-2" />
          Copy as Image
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
