import { useState, useCallback, useRef, useEffect } from 'react';
import { supabase } from '@/integrations/supabase/client';
import {
  classifyProduct,
  extractFilamentsFromProduct,
  diffAgainstDatabase,
  type ScrapingConfig,
  type ExtractedFilament,
  type DiffResult,
} from '@/lib/catalog-sync-core';

// ============================================================
// Types
// ============================================================

export type Phase = 'select' | 'scanning' | 'processing' | 'delta' | 'importing' | 'complete';

export type SyncItem = {
  id: string;
  job_id: string;
  status: string;
  is_new: boolean;
  extracted_data: Record<string, unknown>;
  admin_override_data: Record<string, unknown> | null;
  display_name: string | null;
  color_name: string | null;
  color_hex: string | null;
  color_family: string | null;
  material_type: string | null;
  finish_type: string | null;
  image_url: string | null;
  variant_image_url: string | null;
  price_usd: number | null;
  price_eur: number | null;
  price_cad: number | null;
  price_gbp: number | null;
  price_aud: number | null;
  variant_sku: string | null;
  product_handle: string | null;
  available_regions: string[] | null;
  existing_filament_id: string | null;
  inserted_filament_id: string | null;
  price_diff: Record<string, unknown> | null;
  error_message: string | null;
  created_at: string | null;
};

export type SyncJob = {
  id: string;
  brand_id: string;
  config_id: string | null;
  status: string;
  total_store_products: number | null;
  filament_products_found: number | null;
  skipped_products: number | null;
  new_count: number | null;
  changed_count: number | null;
  matched_count: number | null;
  error_count: number | null;
  imported_count: number | null;
  post_import_results: Record<string, unknown> | null;
  started_at: string | null;
  completed_at: string | null;
  created_at: string | null;
  warnings: string[] | null;
};

export interface DeltaStats {
  totalDiscovered: number;
  inDatabase: number;
  newCount: number;
  changedCount: number;
  matchedCount: number;
  errorCount: number;
}

export interface ImportError {
  itemId: string;
  displayName: string;
  severity: 'critical' | 'warning' | 'info';
  message: string;
  explanation: string;
  resolution: string;
  resolutionType: 'auto-retry-update' | 'auto-retry-insert' | 'auto-retry-price-history' | 'manual' | 'none';
  existingFilamentId?: string;
  syncItemId?: string;
}

export interface ImportResult {
  imported: number;
  updatedPrices: number;
  errors: number;
  errorDetails: ImportError[];
  priceHistoryCount: number;
  avgQualityScore: number;
  urlsBroken: string[];
}

// ============================================================
// Client-Side Shopify Fetch (CORS-enabled stores)
// ============================================================

/**
 * Fetch all products from a Shopify store via /products.json.
 * Works client-side because Shopify stores return `access-control-allow-origin: *`.
 * Paginates up to maxPages to handle large catalogs.
 */
async function fetchShopifyCatalog(
  baseUrl: string,
  maxPages = 10,
  onProgress?: (msg: string) => void,
): Promise<{ products: any[]; totalFetched: number }> {
  const cleanBase = baseUrl.replace(/\/$/, '');
  const allProducts: any[] = [];
  let page = 1;

  while (page <= maxPages) {
    const pageUrl = `${cleanBase}/products.json?limit=250&page=${page}`;
    onProgress?.(`Fetching page ${page}...`);

    const response = await fetch(pageUrl, {
      headers: { Accept: 'application/json' },
    });

    if (!response.ok) {
      if (page === 1) throw new Error(`Store returned HTTP ${response.status}`);
      break;
    }

    const data = await response.json();
    const products = data?.products;
    if (!products || !Array.isArray(products) || products.length === 0) break;

    allProducts.push(...products);

    if (products.length < 250) break;
    page++;
    // Small delay between pages
    await new Promise(r => setTimeout(r, 200));
  }

  return { products: allProducts, totalFetched: allProducts.length };
}

// ============================================================
// Pre-Fetched JSON Loader (for stores with no CORS or Shopify API)
// ============================================================

/**
 * Fetch products from a pre-fetched JSON file served from /data/.
 * Used for stores like Bambu Lab that:
 * - Don't expose /products.json (Next.js frontend blocks it)
 * - Don't have CORS headers (so no browser-side fetch)
 * - Need server-side scraping of JSON-LD data
 *
 * The JSON file is generated by scripts/fetch-bambu-products.cjs and
 * copied to public/data/ before the dev server starts.
 */
async function fetchFromPrefetchedJson(
  jsonPath: string,
  onProgress?: (msg: string) => void,
): Promise<{ products: any[]; totalFetched: number; failed: string[] }> {
  onProgress?.(`Loading pre-fetched product data...`);

  const response = await fetch(jsonPath);
  if (!response.ok) {
    throw new Error(`Failed to load pre-fetched data: HTTP ${response.status}. Run the brand's pre-fetch script first (e.g., scripts/fetch-<brand>-products.cjs).`);
  }

  const data = await response.json();
  const products = data?.products || [];
  const failed = (data?.failed || []).map((f: any) => f.handle || f);

  onProgress?.(`Loaded ${products.length} products from pre-fetched data`);

  if (failed.length > 0) {
    console.warn(`[prefetched] ${failed.length} products were not available:`, failed);
  }

  return { products, totalFetched: products.length, failed };
}

// ============================================================
// Per-Handle Whitelist Fetch (for stores without CORS)
// ============================================================

/**
 * CORS proxy URL template — uses allorigins.win /get endpoint which wraps response
 * in {contents: "...", status: {...}}. More reliable than /raw from browsers.
 */
const CORS_PROXY_GET = 'https://api.allorigins.win/get?url=';

/**
 * Anycubic product handle whitelist — 19 official filament product lines.
 * Each entry has the handle and the base URL (some products are CA-only).
 */
const ANYCUBIC_HANDLES: Array<{ handle: string; baseUrl: string; material: string }> = [
  // Core PLA
  { handle: 'pla-basic-refill', baseUrl: 'https://store.anycubic.com', material: 'PLA+' },
  { handle: 'pla-filament', baseUrl: 'https://store.anycubic.com', material: 'PLA+' },
  { handle: 'pla-plus-filament', baseUrl: 'https://store.anycubic.com', material: 'PLA+' },
  { handle: 'pla-plus-refill', baseUrl: 'https://store.anycubic.com', material: 'PLA+' },
  { handle: 'high-speed-pla-filament', baseUrl: 'https://store.anycubic.com', material: 'PLA+' },
  // Specialty PLA
  { handle: 'silk-pla-filament', baseUrl: 'https://store.anycubic.com', material: 'PLA' },
  { handle: 'pla-silk-dual-tri-color-filament', baseUrl: 'https://store.anycubic.com', material: 'PLA' },
  { handle: 'pla-basic-special-color-filament', baseUrl: 'https://store.anycubic.com', material: 'PLA+' },
  { handle: 'pla-glow', baseUrl: 'https://store.anycubic.com', material: 'PLA-Glow' },
  { handle: 'pla-marble', baseUrl: 'https://store.anycubic.com', material: 'PLA' },
  { handle: 'pla-galaxy', baseUrl: 'https://store.anycubic.com', material: 'PLA+' },
  { handle: 'matte-pla-filament', baseUrl: 'https://store.anycubic.com', material: 'PLA' },
  { handle: 'pla-metal-filament', baseUrl: 'https://store.anycubic.com', material: 'PLA' },
  // PETG
  { handle: 'petg-filament', baseUrl: 'https://store.anycubic.com', material: 'PETG' },
  { handle: 'petg-filament-translucent', baseUrl: 'https://store.anycubic.com', material: 'PETG' },
  // Engineering
  { handle: 'abs-filament', baseUrl: 'https://store.anycubic.com', material: 'ABS' },
  { handle: 'asa-filament', baseUrl: 'https://store.anycubic.com', material: 'ASA' },
  { handle: 'pc-filament', baseUrl: 'https://store.anycubic.com', material: 'PC' },
  { handle: 'tpu-filament', baseUrl: 'https://store.anycubic.com', material: 'TPU' },
];

/**
 * Fetch a single product via CORS proxy (/get endpoint) with retry.
 * The /get endpoint wraps the response as {contents: "...", status: {...}}.
 */
async function fetchProductViaProxy(
  baseUrl: string,
  handle: string,
  maxRetries = 2,
): Promise<any | null> {
  const productUrl = `${baseUrl}/products/${handle}.json`;
  const proxyUrl = `${CORS_PROXY_GET}${encodeURIComponent(productUrl)}`;

  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      const res = await fetch(proxyUrl, {
        headers: { Accept: 'application/json' },
      });

      if (!res.ok) {
        console.warn(`[proxy] ${handle}: HTTP ${res.status} (attempt ${attempt + 1})`);
        if (attempt < maxRetries) {
          await new Promise(r => setTimeout(r, 1500 * (attempt + 1)));
          continue;
        }
        return null;
      }

      const wrapper = await res.json();

      // /get endpoint wraps response in {contents: "...", status: {...}}
      if (wrapper?.contents) {
        const data = JSON.parse(wrapper.contents);
        if (data?.product) return data.product;
      }

      // Fallback: direct JSON (in case proxy returns raw)
      if (wrapper?.product) return wrapper.product;

      console.warn(`[proxy] ${handle}: no product in response`);
      return null;
    } catch (err) {
      console.warn(`[proxy] ${handle}: fetch error (attempt ${attempt + 1}):`, err);
      if (attempt < maxRetries) {
        await new Promise(r => setTimeout(r, 1500 * (attempt + 1)));
      }
    }
  }

  return null;
}

/**
 * Fetch products using a curated whitelist of handles via CORS proxy.
 * Used for stores like Anycubic that don't have CORS on their Shopify endpoints.
 */
async function fetchViaHandleWhitelist(
  handles: Array<{ handle: string; baseUrl: string }>,
  onProgress?: (msg: string) => void,
): Promise<{ products: any[]; totalFetched: number; failed: string[] }> {
  const allProducts: any[] = [];
  const failed: string[] = [];

  for (let i = 0; i < handles.length; i++) {
    const { handle, baseUrl } = handles[i];
    onProgress?.(`Fetching ${handle} (${i + 1}/${handles.length})...`);

    const product = await fetchProductViaProxy(baseUrl, handle);
    if (product) {
      allProducts.push(product);
    } else {
      failed.push(handle);
    }

    // Rate limit: 500ms between requests to be respectful
    if (i < handles.length - 1) {
      await new Promise(r => setTimeout(r, 500));
    }
  }

  return { products: allProducts, totalFetched: allProducts.length, failed };
}

// ============================================================
// Auto-Config Creation for Known Brands
// ============================================================

/**
 * Built-in configs for brands that need special handling.
 * These are auto-created in brand_scraping_configs when the brand is selected.
 */
const KNOWN_BRAND_CONFIGS: Record<string, {
  brand_name: string;
  platform: string;
  base_url: string;
  scrape_method: string;
  adapter_key: string;
  catalog_strategy: string;
  regional_url_pattern: Record<string, string>;
  variant_mapping: Record<string, any>;
}> = {
  anycubic: {
    brand_name: 'Anycubic',
    platform: 'shopify',
    base_url: 'https://store.anycubic.com',
    scrape_method: 'per_handle_whitelist',
    adapter_key: 'anycubic',
    catalog_strategy: 'per-handle-whitelist',
    regional_url_pattern: {
      US: 'https://store.anycubic.com',
      CA: 'https://ca.anycubic.com',
      UK: 'https://uk.anycubic.com',
      EU: 'https://eu.anycubic.com',
      AU: 'https://www.anycubic.au',
    },
    variant_mapping: {
      region_option: 'option3',
      color_option: 'option1',
      size_option: 'option2',
      region_map: { US: 'US', EU: 'EU', UK: 'UK', Other: 'US' },
      price_currency_map: { US: 'USD', EU: 'EUR', UK: 'GBP', Other: 'USD' },
    },
  },
  'bambu-lab': {
    brand_name: 'Bambu Lab',
    platform: 'shopify-jsonld',
    base_url: 'https://ca.store.bambulab.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'bambu-lab',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://us.store.bambulab.com',
      CA: 'https://ca.store.bambulab.com',
      EU: 'https://eu.store.bambulab.com',
      UK: 'https://uk.store.bambulab.com',
      AU: 'https://au.store.bambulab.com',
    },
    variant_mapping: {
      color_option: 'option1',
      size_option: 'option2',
      spool_type_option: 'option3',
      source_currency: 'CAD',
    },
  },
  '3d-fuel': {
    brand_name: '3D-Fuel',
    platform: 'shopify',
    base_url: 'https://www.3dfuel.com',
    scrape_method: 'prefetched_json',
    adapter_key: '3d-fuel',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://www.3dfuel.com',
    },
    variant_mapping: {
      material_option: 'option1',
      size_option: 'option2',
      color_option: 'option3',
    },
  },
  '3dhojor': {
    brand_name: '3DHOJOR',
    platform: 'shopify',
    base_url: 'https://3dhojor.com',
    scrape_method: 'prefetched_json',
    adapter_key: '3dhojor',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://3dhojor.com',
    },
    variant_mapping: {
      region_option: 'option1',
      size_option: 'option2',
      color_option: 'option3',
    },
  },
  '3dxtech': {
    brand_name: '3DXTech',
    platform: 'shopify',
    base_url: 'https://www.3dxtech.com',
    scrape_method: 'prefetched_json',
    adapter_key: '3dxtech',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://www.3dxtech.com',
    },
    variant_mapping: {
      color_option: 'option1',
      diameter_option: 'option2',
      size_option: 'option3',
    },
  },
  'amolen': {
    brand_name: 'Amolen',
    platform: 'shopify',
    base_url: 'https://www.amolen.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'amolen',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://www.amolen.com',
    },
    variant_mapping: {
      // Option order varies: most are "Color | Delivery Option", some are "Delivery Option | Color"
      // detectOptionPositions() auto-detects from option names (no hardcoded positions needed)
      region_map: {
        'U.S. to U.S.': 'US',
        'China to U.S. & Worldwide': 'US',
        'EU to EU': 'EU',
      },
    },
  },
  'atomic-filament': {
    brand_name: 'Atomic Filament',
    platform: 'shopify',
    base_url: 'https://atomicfilament.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'atomic-filament',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://atomicfilament.com',
    },
    variant_mapping: {
      color_from_title: true,
    },
  },
  'azurefilm': {
    brand_name: 'AzureFilm',
    platform: 'woocommerce',
    base_url: 'https://azurefilm.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'azurefilm',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      EU: 'https://azurefilm.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'EUR',
    },
  },
  'colorfabb': {
    brand_name: 'colorFabb',
    platform: 'magento',
    base_url: 'https://colorfabb.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'colorfabb',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      EU: 'https://colorfabb.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'EUR',
    },
  },
  'creality': {
    brand_name: 'Creality',
    platform: 'custom',
    base_url: 'https://store.creality.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'creality',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://store.creality.com',
    },
    variant_mapping: {
      color_option: 'option1',
    },
  },
  'duramic-3d': {
    brand_name: 'Duramic 3D',
    platform: 'shopify',
    base_url: 'https://duramic3d.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'duramic-3d',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://duramic3d.com',
    },
    variant_mapping: {
      color_option: 'option1',
    },
  },
  'elegoo': {
    brand_name: 'Elegoo',
    platform: 'shopify',
    base_url: 'https://us.elegoo.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'elegoo',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://us.elegoo.com',
    },
    variant_mapping: {
      color_option: 'option1',
    },
  },
  'eryone': {
    brand_name: 'Eryone',
    platform: 'shopify',
    base_url: 'https://eryone3d.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'eryone',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://eryone3d.com',
    },
    variant_mapping: {
      color_from_title: true,
      source_currency: 'USD',
    },
  },
  'esun': {
    brand_name: 'eSun',
    platform: 'ueeshop',
    base_url: 'https://esun3dstore.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'esun',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://esun3dstore.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'USD',
    },
  },
  'extrudr': {
    brand_name: 'Extrudr',
    platform: 'saleor',
    base_url: 'https://www.extrudr.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'extrudr',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      EU: 'https://www.extrudr.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'EUR',
    },
  },
  'fiberlogy': {
    brand_name: 'Fiberlogy',
    platform: 'shoper',
    base_url: 'https://fiberlogy.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'fiberlogy',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      EU: 'https://fiberlogy.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'EUR',
    },
  },
  'fillamentum': {
    brand_name: 'Fillamentum',
    platform: 'shopify',
    base_url: 'https://shop.fillamentum.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'fillamentum',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      EU: 'https://shop.fillamentum.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'EUR',
    },
  },
  'flsun': {
    brand_name: 'FLSUN',
    platform: 'shopify',
    base_url: 'https://us.store.flsun3d.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'flsun',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://us.store.flsun3d.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'USD',
    },
  },
  'formfutura': {
    brand_name: 'FormFutura',
    platform: 'odoo',
    base_url: 'https://www.formfutura.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'formfutura',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      EU: 'https://www.formfutura.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'EUR',
    },
  },
  'fusion-filaments': {
    brand_name: 'Fusion Filaments',
    platform: 'odoo',
    base_url: 'https://www.fusionfilaments.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'fusion-filaments',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://www.fusionfilaments.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'USD',
    },
  },
  'geeetech': {
    brand_name: 'Geeetech',
    platform: 'custom',
    base_url: 'https://www.geeetech.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'geeetech',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://www.geeetech.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'USD',
    },
  },
  'gizmo-dorks': {
    brand_name: 'Gizmo Dorks',
    platform: 'bigcommerce',
    base_url: 'https://gizmodorks.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'gizmo-dorks',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://gizmodorks.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'USD',
    },
  },
  'hatchbox': {
    brand_name: 'Hatchbox',
    platform: 'shopify',
    base_url: 'https://www.hatchbox3d.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'hatchbox',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://www.hatchbox3d.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'USD',
    },
  },
  'ic3d-printers': {
    brand_name: 'IC3D Printers',
    platform: 'custom',
    base_url: 'https://www.ic3dprinters.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'ic3d-printers',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://www.ic3dprinters.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'USD',
    },
  },
  'kingroon': {
    brand_name: 'Kingroon',
    platform: 'shopify',
    base_url: 'https://kingroon.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'kingroon',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://kingroon.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'USD',
    },
  },
  'matter3d': {
    brand_name: 'Matter3D',
    platform: 'shopify',
    base_url: 'https://matter3d.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'matter3d',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://matter3d.com',
    },
    variant_mapping: {
      // Option order varies: some products have Color=option1/Size=option2,
      // others have Size=option1/Color=option2
      // detectOptionPositions() auto-detects from option names
      source_currency: 'USD',
    },
  },
  'ninjatek': {
    brand_name: 'NinjaTek',
    platform: 'woocommerce',
    base_url: 'https://ninjatek.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'ninjatek',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://ninjatek.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'USD',
    },
  },
  'numakers': {
    brand_name: 'Numakers',
    platform: 'shopify',
    base_url: 'https://numakers.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'numakers',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://numakers.com',
    },
    variant_mapping: {
      // Numakers uses Diameter=option1, Weight=option2, Color=option3
      color_option: 'option3',
      source_currency: 'USD',
    },
  },
  'overture': {
    brand_name: 'Overture',
    platform: 'shopify',
    base_url: 'https://overture3d.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'overture',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://overture3d.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'USD',
    },
  },
  'paramount-3d': {
    brand_name: 'Paramount 3D',
    platform: 'wix',
    base_url: 'https://www.paramount-3d.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'paramount-3d',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://www.paramount-3d.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'USD',
    },
  },
  'polymaker': {
    brand_name: 'Polymaker',
    platform: 'shopify',
    base_url: 'https://us.polymaker.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'polymaker',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://us.polymaker.com',
      EU: 'https://eu.polymaker.com',
    },
    variant_mapping: {
      // Polymaker uses: option1=Diameter/Packaging, option2=Weight, option3=Color
      color_option: 'option3',
      source_currency: 'USD',
    },
  },
  'proto-pasta': {
    brand_name: 'Proto-Pasta',
    platform: 'shopify',
    base_url: 'https://www.proto-pasta.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'proto-pasta',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://www.proto-pasta.com',
    },
    variant_mapping: {
      // Proto-Pasta: color is in the product title, option1=Diameter, option2=Size
      color_from_title: true,
      source_currency: 'USD',
    },
  },
  'prusament': {
    brand_name: 'Prusament',
    platform: 'custom',
    base_url: 'https://www.prusa3d.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'prusament',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      EU: 'https://www.prusa3d.com',
      US: 'https://www.prusa3d.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'EUR',
    },
  },
  'push-plastic': {
    brand_name: 'Push Plastic',
    platform: 'shopify',
    base_url: 'https://www.pushplastic.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'push-plastic',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://www.pushplastic.com',
    },
    variant_mapping: {
      // Push Plastic: option1=Filament Color (simple single-option structure)
      color_option: 'option1',
      source_currency: 'USD',
    },
  },
  'qidi': {
    brand_name: 'QIDI',
    platform: 'shopify',
    base_url: 'https://us.qidi3d.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'qidi',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://us.qidi3d.com',
    },
    variant_mapping: {
      // QIDI: option1=Weight, option2=Color (with HEX codes like "Black HEX Code #070809")
      color_option: 'option2',
      source_currency: 'USD',
    },
  },
  'recreus': {
    brand_name: 'Recreus',
    platform: 'shopify',
    base_url: 'https://recreus.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'recreus',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      EU: 'https://recreus.com',
    },
    variant_mapping: {
      // Recreus: option1=Color (Spanish names), option2=Peso (weight). EUR store.
      color_option: 'option1',
      source_currency: 'EUR',
    },
  },
  'siraya-tech': {
    brand_name: 'Siraya Tech',
    platform: 'shopify',
    base_url: 'https://siraya.tech',
    scrape_method: 'shopify_products_json',
    adapter_key: 'siraya-tech',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://siraya.tech',
    },
    variant_mapping: {
      // Siraya Tech: option positions vary — auto-detect finds "Color" by name
      // Some products: o1=Ship to, o2=Size, o3=Color; others: o1=Ship to, o2=Color, o3=Size
      color_option: 'option3',
      source_currency: 'USD',
    },
  },
  'sovol': {
    brand_name: 'Sovol',
    platform: 'shopify',
    base_url: 'https://www.sovol3d.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'sovol',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      US: 'https://www.sovol3d.com',
    },
    variant_mapping: {
      // Sovol: option1=Ship from, option2=Sovol Filament Color, option3=Weight
      color_option: 'option2',
      source_currency: 'USD',
    },
  },
  'spectrum-filaments': {
    brand_name: 'Spectrum Filaments',
    platform: 'shopify',
    base_url: 'https://ca.spectrumfilaments.com',
    scrape_method: 'shopify_products_json',
    adapter_key: 'spectrum-filaments',
    catalog_strategy: 'products-json',
    regional_url_pattern: {
      CA: 'https://ca.spectrumfilaments.com',
      EU: 'https://shop.spectrumfilaments.com',
    },
    variant_mapping: {
      // Spectrum CA: flat products (1 product per color), color in title. Prices in CAD.
      color_from_title: true,
      source_currency: 'CAD',
    },
  },
  'treed-filaments': {
    brand_name: 'TreeD Filaments',
    platform: 'custom',
    base_url: 'https://treed-filaments.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'treed-filaments',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      EU: 'https://treed-filaments.com',
    },
    variant_mapping: {
      color_option: 'option1',
      source_currency: 'EUR',
    },
  },
  'ultimaker': {
    brand_name: 'UltiMaker',
    platform: 'magento',
    base_url: 'https://store.ultimaker.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'ultimaker',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://store.ultimaker.com',
    },
    variant_mapping: {
      // Curated catalog: option1=Color. Includes 2.85mm (S Series) and 1.75mm (Method/Sketch).
      color_option: 'option1',
      source_currency: 'USD',
    },
  },
  'voxelpla': {
    brand_name: 'VoxelPLA',
    platform: 'shopify',
    base_url: 'https://voxelpla.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'voxelpla',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://voxelpla.com',
    },
    variant_mapping: {
      // VoxelPLA: flat products (1 product per color), color in title. No CORS.
      color_from_title: true,
      source_currency: 'USD',
    },
  },
  'ziro': {
    brand_name: 'Ziro',
    platform: 'shopify',
    base_url: 'https://ziro3d.com',
    scrape_method: 'prefetched_json',
    adapter_key: 'ziro',
    catalog_strategy: 'prefetched-json',
    regional_url_pattern: {
      US: 'https://ziro3d.com',
    },
    variant_mapping: {
      // Ziro: flat products (1 product per color), color in title. No CORS.
      color_from_title: true,
      source_currency: 'USD',
    },
  },
};

/**
 * Ensure a brand_scraping_configs entry exists for a known brand.
 * Returns the config ID (existing or newly created).
 */
async function ensureBrandConfig(
  supabaseClient: any,
  brandId: string,
  brandSlug: string,
): Promise<string | null> {
  // Check if config already exists
  const { data: existing } = await supabaseClient
    .from('brand_scraping_configs')
    .select('id')
    .eq('brand_id', brandId)
    .maybeSingle();

  if (existing) return existing.id;

  // Check if we have a built-in config for this brand
  const builtIn = KNOWN_BRAND_CONFIGS[brandSlug];
  if (!builtIn) return null;

  // Create the config
  const { data: created, error: createErr } = await supabaseClient
    .from('brand_scraping_configs')
    .insert({
      brand_id: brandId,
      brand_name: builtIn.brand_name,
      platform: builtIn.platform,
      base_url: builtIn.base_url,
      scrape_method: builtIn.scrape_method,
      adapter_key: builtIn.adapter_key,
      catalog_strategy: builtIn.catalog_strategy,
      regional_url_pattern: builtIn.regional_url_pattern,
      variant_mapping: builtIn.variant_mapping,
      is_active: true,
    })
    .select('id')
    .single();

  if (createErr) {
    console.error('[ensureBrandConfig] Failed to create config:', createErr.message);
    return null;
  }

  console.log(`[ensureBrandConfig] Created config for ${brandSlug}: ${created.id}`);
  return created.id;
}

/**
 * Slim down products by truncating body_html (saves memory).
 */
function slimProducts(products: any[]): any[] {
  return products.map(p => ({
    ...p,
    body_html: (p.body_html || '').slice(0, 3000),
  }));
}

// ============================================================
// Hook
// ============================================================

export function useCatalogSync() {
  const [phase, setPhase] = useState<Phase>('select');
  const [jobId, setJobId] = useState<string | null>(null);
  const [scanJob, setScanJob] = useState<SyncJob | null>(null);
  const [items, setItems] = useState<SyncItem[]>([]);
  const [importResult, setImportResult] = useState<ImportResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [importing, setImporting] = useState(false);
  const [scanStatusMessage, setScanStatusMessage] = useState<string>('');
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  // Cleanup polling on unmount
  useEffect(() => {
    return () => {
      if (pollRef.current) clearInterval(pollRef.current);
    };
  }, []);

  // Derived stats
  const deltaStats: DeltaStats = {
    totalDiscovered: items.length,
    inDatabase: items.filter(i => i.status === 'matched' || i.status === 'price_changed').length
      + (scanJob?.matched_count ?? 0) - items.filter(i => i.status === 'matched').length,
    newCount: items.filter(i => i.status === 'new').length,
    changedCount: items.filter(i => i.status === 'price_changed').length,
    matchedCount: items.filter(i => i.status === 'matched').length,
    errorCount: items.filter(i => i.status === 'error').length,
  };

  // Recalculate inDatabase from the job stats + matched items
  if (scanJob) {
    deltaStats.inDatabase = (scanJob.matched_count ?? 0) + (scanJob.changed_count ?? 0);
  }

  // ── Start Scan (Client-Side: Fetch → Classify → Extract → Diff → Store) ──
  //
  // This runs entirely in the browser, bypassing edge functions.
  // Shopify stores have CORS enabled on /products.json.
  // When Supabase edge function deployment is restored, this can switch back
  // to the edge function approach (sync-brand-catalog + process-brand-sync).

  const startScan = useCallback(async (brandId: string, configId: string) => {
    setError(null);
    setItems([]);
    setScanJob(null);
    setImportResult(null);
    setPhase('scanning');
    setScanStatusMessage('Loading configuration...');

    try {
      // ── Load brand ──
      const { data: brandData, error: brandErr } = await supabase
        .from('automated_brands')
        .select('brand_name, brand_slug')
        .eq('id', brandId)
        .maybeSingle();

      if (brandErr || !brandData) throw new Error(`Brand not found: ${brandId}`);

      // ── Ensure config exists (auto-create for known brands) ──
      let actualConfigId = configId;
      if (!actualConfigId || actualConfigId === 'auto') {
        const autoId = await ensureBrandConfig(supabase, brandId, brandData.brand_slug);
        if (!autoId) throw new Error(`No scraping config for brand: ${brandData.brand_name}`);
        actualConfigId = autoId;
      }

      // ── Load config ──
      const { data: configData, error: configErr } = await supabase
        .from('brand_scraping_configs')
        .select('*')
        .eq('id', actualConfigId)
        .maybeSingle();

      if (configErr || !configData) throw new Error(`Config not found: ${actualConfigId}`);

      const config = configData as unknown as ScrapingConfig;

      // ── Get current user ID ──
      const { data: { user } } = await supabase.auth.getUser();

      // ── Create job ──
      setScanStatusMessage('Creating sync job...');
      const { data: jobData, error: jobErr } = await supabase
        .from('brand_sync_jobs')
        .insert({
          brand_id: brandId,
          config_id: actualConfigId,
          status: 'syncing',
          admin_user_id: user?.id ?? null,
          started_at: new Date().toISOString(),
        })
        .select('id')
        .single();

      if (jobErr || !jobData) throw new Error(`Failed to create job: ${jobErr?.message}`);
      const currentJobId = jobData.id;
      setJobId(currentJobId);

      // ── Fetch products from store (strategy-dependent) ──
      const catalogStrategy = config.catalog_strategy || config.scrape_method || 'products-json';
      let allProducts: any[];

      if (catalogStrategy === 'prefetched-json' || catalogStrategy === 'prefetched_json') {
        // Load from pre-fetched JSON file (e.g., Bambu Lab — no CORS, no Shopify API)
        const brandSlug = brandData.brand_slug;

        // Map brand slugs to their pre-fetched JSON filenames
        const PREFETCH_PATHS: Record<string, string> = {
          'bambu-lab': '/data/bambu-products.json',
          '3d-fuel': '/data/3dfuel-products.json',
          '3dhojor': '/data/3dhojor-products.json',
          '3dxtech': '/data/3dxtech-products.json',
          'azurefilm': '/data/azurefilm-products.json',
          'colorfabb': '/data/colorfabb-products.json',
          'creality': '/data/creality-products.json',
          'esun': '/data/esun-products.json',
          'extrudr': '/data/extrudr-products.json',
          'fiberlogy': '/data/fiberlogy-products.json',
          'formfutura': '/data/formfutura-products.json',
          'fusion-filaments': '/data/fusion-filaments-products.json',
          'geeetech': '/data/geeetech-products.json',
          'gizmo-dorks': '/data/gizmo-dorks-products.json',
          'ic3d-printers': '/data/ic3d-printers-products.json',
          'ninjatek': '/data/ninjatek-products.json',
          'paramount-3d': '/data/paramount-3d-products.json',
          'prusament': '/data/prusament-products.json',
          'treed-filaments': '/data/treed-filaments-products.json',
          'ultimaker': '/data/ultimaker-products.json',
          'voxelpla': '/data/voxelpla-products.json',
          'ziro': '/data/ziro-products.json',
        };
        const actualPath = PREFETCH_PATHS[brandSlug] || `/data/${brandSlug}-products.json`;

        setScanStatusMessage('Loading pre-fetched product data...');
        const result = await fetchFromPrefetchedJson(
          actualPath,
          (msg) => setScanStatusMessage(msg),
        );

        if (result.failed.length > 0) {
          console.warn(`[scan] ${result.failed.length} products not available:`, result.failed);
        }

        allProducts = result.products;
      } else if (catalogStrategy === 'per-handle-whitelist' || catalogStrategy === 'per_handle_whitelist') {
        // Use curated whitelist with CORS proxy
        const brandSlug = brandData.brand_slug;
        const handles = brandSlug === 'anycubic' ? ANYCUBIC_HANDLES : [];

        if (handles.length === 0) {
          throw new Error(`No product whitelist defined for brand: ${brandData.brand_name}`);
        }

        setScanStatusMessage(`Fetching ${handles.length} products via proxy...`);
        const result = await fetchViaHandleWhitelist(
          handles,
          (msg) => setScanStatusMessage(msg),
        );

        if (result.failed.length > 0) {
          console.warn(`[scan] Failed to fetch ${result.failed.length} handles:`, result.failed);
        }

        allProducts = result.products;
      } else {
        // Default: standard Shopify /products.json
        setScanStatusMessage('Fetching products from store...');
        const result = await fetchShopifyCatalog(
          config.base_url,
          10,
          (msg) => setScanStatusMessage(msg),
        );
        allProducts = result.products;
      }

      if (allProducts.length === 0) throw new Error('No products found in store');

      // Update job with product count
      await supabase.from('brand_sync_jobs').update({
        total_store_products: allProducts.length,
      }).eq('id', currentJobId);

      setScanStatusMessage(`Fetched ${allProducts.length} products. Classifying...`);
      setPhase('processing');

      // ── Classify products ──
      const slimmed = slimProducts(allProducts);
      const filamentProducts: any[] = [];
      const skipReasons: Record<string, number> = {};

      for (const product of slimmed) {
        const cls = classifyProduct(product);
        if (cls.isFilament) {
          filamentProducts.push(product);
        } else {
          skipReasons[cls.reason] = (skipReasons[cls.reason] || 0) + 1;
        }
      }

      setScanStatusMessage(
        `Found ${filamentProducts.length} filament products. Extracting variants...`,
      );

      // ── Extract filaments ──
      const allFilaments: ExtractedFilament[] = [];
      const extractionErrors: { handle: string; error: string }[] = [];
      const warnings: string[] = [];

      for (const product of filamentProducts) {
        try {
          const result = extractFilamentsFromProduct(product, config);
          allFilaments.push(...result.filaments);
          warnings.push(...result.warnings);
        } catch (err: unknown) {
          const h = product.handle || product.title || 'unknown';
          extractionErrors.push({
            handle: h,
            error: err instanceof Error ? err.message : 'Unknown extraction error',
          });
        }
      }

      // ── Post-process: Currency correction for non-USD stores ──
      // Pre-fetched data from Bambu Lab CA store has prices in CAD, not USD.
      // The generic extraction pipeline assigns them to price_usd by default.
      // Move them to the correct currency field.
      const sourceCurrency = config.variant_mapping?.source_currency;
      if (sourceCurrency && sourceCurrency !== 'USD') {
        for (const fil of allFilaments) {
          if (fil.price_usd !== null && fil.price_usd > 0) {
            if (sourceCurrency === 'CAD') {
              fil.price_cad = fil.price_usd;
              fil.price_usd = null;
              // Fix available_regions: replace "US" with "CA"
              fil.available_regions = fil.available_regions
                .map(r => r === 'US' ? 'CA' : r)
                .filter((r, i, a) => a.indexOf(r) === i);
            } else if (sourceCurrency === 'EUR') {
              fil.price_eur = fil.price_usd;
              fil.price_usd = null;
              fil.available_regions = fil.available_regions
                .map(r => r === 'US' ? 'EU' : r)
                .filter((r, i, a) => a.indexOf(r) === i);
            } else if (sourceCurrency === 'GBP') {
              fil.price_gbp = fil.price_usd;
              fil.price_usd = null;
              fil.available_regions = fil.available_regions
                .map(r => r === 'US' ? 'UK' : r)
                .filter((r, i, a) => a.indexOf(r) === i);
            } else if (sourceCurrency === 'AUD') {
              fil.price_aud = fil.price_usd;
              fil.price_usd = null;
              fil.available_regions = fil.available_regions
                .map(r => r === 'US' ? 'AU' : r)
                .filter((r, i, a) => a.indexOf(r) === i);
            }
          }
        }
        console.log(`[scan] Corrected ${allFilaments.length} filaments from USD → ${sourceCurrency}`);
      }

      // ── Post-process: Set regional URLs for known brands ──
      const regionalUrls = config.regional_url_pattern;
      if (regionalUrls) {
        for (const fil of allFilaments) {
          if (fil.product_handle) {
            if (regionalUrls['US']) fil.product_url_us = `${regionalUrls['US']}/products/${fil.product_handle}`;
            if (regionalUrls['EU']) fil.product_url_eu = `${regionalUrls['EU']}/products/${fil.product_handle}`;
            if (regionalUrls['UK']) fil.product_url_uk = `${regionalUrls['UK']}/products/${fil.product_handle}`;
            if (regionalUrls['CA']) fil.product_url_ca = `${regionalUrls['CA']}/products/${fil.product_handle}`;
            if (regionalUrls['AU']) fil.product_url_au = `${regionalUrls['AU']}/products/${fil.product_handle}`;
            // Default product_url to the source base URL
            fil.product_url = `${config.base_url}/products/${fil.product_handle}`;
          }
        }
      }

      setScanStatusMessage(
        `Extracted ${allFilaments.length} filament variants. Comparing with database...`,
      );

      // ── Diff against database ──
      const diffResults = await diffAgainstDatabase(supabase, allFilaments, brandId, brandData.brand_name);
      const newCount = diffResults.filter(r => r.status === 'new').length;
      const changedCount = diffResults.filter(r => r.status === 'price_changed').length;
      const matchedCount = diffResults.filter(r => r.status === 'matched').length;

      // ── Store items in brand_sync_items ──
      setScanStatusMessage('Saving results...');

      const itemsToInsert: any[] = diffResults.map(r => ({
        job_id: currentJobId,
        status: r.status,
        extracted_data: r.filament as any,
        display_name: r.filament.display_name,
        color_name: r.filament.color_family || r.filament.display_name.split(' - ').pop() || null,
        material_type: r.filament.material,
        color_hex: r.filament.color_hex,
        color_family: r.filament.color_family,
        finish_type: r.filament.finish_type,
        image_url: r.filament.featured_image,
        variant_image_url: r.filament.variant_image,
        price_usd: r.filament.price_usd,
        price_eur: r.filament.price_eur,
        price_gbp: r.filament.price_gbp,
        price_cad: r.filament.price_cad,
        price_aud: r.filament.price_aud,
        variant_sku: r.filament.variant_sku,
        product_handle: r.filament.product_handle,
        available_regions: r.filament.available_regions,
        is_new: r.status === 'new',
        existing_filament_id: r.existingId,
        price_diff: r.priceDiff as unknown as Record<string, unknown> | null,
        error_message: null,
      }));

      // Add extraction errors
      for (const err of extractionErrors) {
        itemsToInsert.push({
          job_id: currentJobId,
          status: 'error',
          extracted_data: { handle: err.handle } as Record<string, unknown>,
          display_name: err.handle,
          color_name: null,
          material_type: null,
          color_hex: null,
          color_family: null,
          finish_type: null,
          image_url: null,
          variant_image_url: null,
          price_usd: null,
          price_eur: null,
          price_gbp: null,
          price_cad: null,
          price_aud: null,
          variant_sku: null,
          product_handle: null,
          available_regions: null,
          is_new: false,
          existing_filament_id: null,
          price_diff: null,
          error_message: err.error,
        });
      }

      // Batch insert (100 at a time)
      for (let i = 0; i < itemsToInsert.length; i += 100) {
        const batch = itemsToInsert.slice(i, i + 100);
        const { error: insertErr } = await supabase.from('brand_sync_items').insert(batch);
        if (insertErr) console.error(`Insert batch ${i} error:`, insertErr.message);
      }

      // ── Update job ──
      await supabase.from('brand_sync_jobs').update({
        status: 'completed',
        completed_at: new Date().toISOString(),
        filament_products_found: filamentProducts.length,
        skipped_products: allProducts.length - filamentProducts.length,
        skip_reasons: skipReasons,
        new_count: newCount,
        changed_count: changedCount,
        matched_count: matchedCount,
        error_count: extractionErrors.length,
        warnings: warnings.length > 0 ? warnings : null,
        errors: extractionErrors.length > 0 ? extractionErrors : null,
      }).eq('id', currentJobId);

      // ── Build job summary ──
      setScanJob({
        id: currentJobId,
        brand_id: brandId,
        config_id: configId,
        status: 'completed',
        total_store_products: allProducts.length,
        filament_products_found: filamentProducts.length,
        skipped_products: allProducts.length - filamentProducts.length,
        new_count: newCount,
        changed_count: changedCount,
        matched_count: matchedCount,
        error_count: extractionErrors.length,
        imported_count: null,
        post_import_results: null,
        started_at: null,
        completed_at: new Date().toISOString(),
        created_at: null,
        warnings: warnings.length > 0 ? warnings : null,
      } as SyncJob);

      await loadItems(currentJobId);
      setPhase('delta');
    } catch (err: any) {
      const msg = err.message || 'Scan failed';
      console.error('[useCatalogSync] Scan error:', msg);
      setError(msg);
      setPhase('select');
    }
  }, []);

  // ── Load Items ──

  const loadItems = async (jId: string) => {
    const { data, error: loadErr } = await supabase
      .from('brand_sync_items')
      .select('*')
      .eq('job_id', jId)
      .order('status', { ascending: true })
      .order('display_name', { ascending: true });

    if (loadErr) {
      console.error('Failed to load sync items:', loadErr);
      return;
    }
    setItems((data || []) as SyncItem[]);
  };

  // ── Start Import (Client-Side) ──
  //
  // Runs the full import pipeline in-browser, bypassing the edge function.
  // Steps:
  //   1. Load eligible items from brand_sync_items
  //   2. INSERT new filaments / UPDATE prices on existing ones
  //   3. Record price history per region
  //   4. Compute data quality scores
  //   5. Update job with post-import results

  // ── Error classifier for import errors ──
  function classifyImportError(
    displayName: string,
    itemId: string,
    rawMessage: string,
    context: 'insert' | 'update' | 'price-history',
    existingFilamentId?: string,
  ): ImportError {
    const lower = rawMessage.toLowerCase();

    // Network errors (fetch failures, timeouts)
    if (lower.includes('failed to fetch') || lower.includes('networkerror') || lower.includes('load failed') || lower.includes('timeout')) {
      return {
        itemId, displayName,
        severity: 'critical',
        message: rawMessage,
        explanation: 'Network error — the request to the database failed. This is usually a transient connectivity issue.',
        resolution: context === 'update' ? 'Retry the price update.' : 'Retry the import.',
        resolutionType: context === 'update' ? 'auto-retry-update' : context === 'insert' ? 'auto-retry-insert' : 'auto-retry-price-history',
        existingFilamentId,
        syncItemId: itemId,
      };
    }

    if (context === 'price-history') {
      return {
        itemId, displayName,
        severity: 'warning',
        message: rawMessage,
        explanation: 'Price history records could not be saved. The filament was imported but historical pricing is missing.',
        resolution: 'Re-run the scan to regenerate price history records.',
        resolutionType: 'auto-retry-price-history',
      };
    }

    if (lower.includes('duplicate key') || lower.includes('unique constraint') || lower.includes('unique_')) {
      return {
        itemId, displayName,
        severity: 'critical',
        message: rawMessage,
        explanation: 'A filament with this SKU or product handle already exists in the database.',
        resolution: 'Retry as a price update instead of a new insert.',
        resolutionType: context === 'insert' ? 'auto-retry-update' : 'auto-retry-update',
        existingFilamentId,
        syncItemId: itemId,
      };
    }

    if (lower.includes('not-null') || lower.includes('null value') || lower.includes('violates not')) {
      return {
        itemId, displayName,
        severity: 'critical',
        message: rawMessage,
        explanation: 'A required field (e.g., vendor, material, display_name) is missing from the extracted data.',
        resolution: 'Go back to Review Delta, find this filament, and add the missing field via admin override.',
        resolutionType: 'manual',
        syncItemId: itemId,
      };
    }

    if (lower.includes('check constraint') || lower.includes('violates check')) {
      return {
        itemId, displayName,
        severity: 'critical',
        message: rawMessage,
        explanation: 'A field value is outside the valid range (e.g., negative price, temperature out of bounds).',
        resolution: 'Check the extracted prices and temperatures — the source data may be malformed.',
        resolutionType: 'manual',
        syncItemId: itemId,
      };
    }

    // Generic fallback
    return {
      itemId, displayName,
      severity: 'critical',
      message: rawMessage,
      explanation: context === 'update'
        ? 'The price update on this existing filament was rejected by the database.'
        : 'The database rejected this filament insert.',
      resolution: context === 'update'
        ? 'Retry the price update.'
        : 'Check Supabase logs for the full error, or retry the import.',
      resolutionType: context === 'update' ? 'auto-retry-update' : 'manual',
      existingFilamentId,
      syncItemId: itemId,
    };
  }

  const startImport = useCallback(async (
    itemIds: string[],
    brandId: string,
    brandName: string,
    brandSlug: string
  ) => {
    if (!jobId || itemIds.length === 0) return;
    setError(null);
    setImporting(true);
    setPhase('importing');

    try {
      console.log(`[import] Starting client-side import: ${itemIds.length} items for ${brandName}`);

      // ── STEP 1: Load eligible items ──
      const eligibleItems: any[] = [];
      const BATCH_SIZE = 50;
      for (let i = 0; i < itemIds.length; i += BATCH_SIZE) {
        const batch = itemIds.slice(i, i + BATCH_SIZE);
        const { data, error: batchErr } = await supabase
          .from('brand_sync_items')
          .select('*')
          .eq('job_id', jobId)
          .in('id', batch)
          .in('status', ['new', 'price_changed']);

        if (batchErr) throw new Error(`Failed to load items batch ${i}: ${batchErr.message}`);
        if (data) eligibleItems.push(...data);
      }

      if (eligibleItems.length === 0) {
        setImportResult({
          imported: 0, updatedPrices: 0, errors: 0, errorDetails: [],
          priceHistoryCount: 0, avgQualityScore: 0, urlsBroken: [],
        });
        setPhase('complete');
        return;
      }

      console.log(`[import] Loaded ${eligibleItems.length} eligible items`);

      // ── STEP 2: Insert / Update Filaments ──
      let insertedCount = 0;
      let updatedPrices = 0;
      let errorCount = 0;
      const insertedFilaments: Array<{ id: string; itemId: string; data: Record<string, any> }> = [];
      const importErrorDetails: ImportError[] = [];

      for (const item of eligibleItems) {
        const extracted = (item.extracted_data || {}) as Record<string, any>;
        const overrides = (item.admin_override_data || {}) as Record<string, any>;
        const merged = { ...extracted, ...overrides };

        try {
          if (item.status === 'price_changed' && item.existing_filament_id) {
            // UPDATE existing filament prices + backfill null enrichment fields
            const priceUpdate: Record<string, any> = {
              updated_at: new Date().toISOString(),
              last_scraped_at: new Date().toISOString(),
            };
            if (merged.price_usd != null) priceUpdate.variant_price = merged.price_usd;
            if (merged.price_eur != null) priceUpdate.price_eur = merged.price_eur;
            if (merged.price_gbp != null) priceUpdate.price_gbp = merged.price_gbp;
            if (merged.price_cad != null) priceUpdate.price_cad = merged.price_cad;
            if (merged.price_aud != null) priceUpdate.price_aud = merged.price_aud;
            if (merged.price_jpy != null) priceUpdate.price_jpy = merged.price_jpy;
            if (merged.price_cny != null) priceUpdate.price_cny = merged.price_cny;
            if (merged.variant_available != null) priceUpdate.variant_available = merged.variant_available;

            // Backfill enrichment fields (only set if we have new data — won't overwrite existing values
            // because Supabase COALESCE is not available via .update(), so we use a separate query)
            const enrichmentFields: [string, any][] = [
              ['tg_c', merged.tg_c], ['drying_temp_c', merged.drying_temp_c],
              ['drying_time_hours', merged.drying_time_hours],
              ['moisture_sensitivity_level', merged.moisture_sensitivity_level],
              ['is_nozzle_abrasive', merged.is_nozzle_abrasive],
              ['recommended_nozzle_type', merged.recommended_nozzle_type],
              ['fan_min_percent', merged.fan_min_percent], ['fan_max_percent', merged.fan_max_percent],
              ['density_g_cm3', merged.density_g_cm3],
              ['nozzle_temp_sweetspot_c', merged.nozzle_temp_sweetspot_c],
              ['use_case_tags', merged.use_case_tags],
              ['food_contact_rating', merged.food_contact_rating],
              ['retraction_length_mm', merged.retraction_length_mm],
              ['retraction_speed_mms', merged.retraction_speed_mms],
              ['tds_url', merged.tds_url],
              // Mechanical properties
              ['tensile_strength_xy_mpa', merged.tensile_strength_xy_mpa],
              ['elongation_break_xy_percent', merged.elongation_break_xy_percent],
              ['flexural_strength_mpa', merged.flexural_strength_mpa],
              ['impact_strength_kj_m2', merged.impact_strength_kj_m2],
              ['shore_hardness_d', merged.shore_hardness_d],
              ['hardness_shore_a', merged.hardness_shore_a],
              // Thermal properties
              ['melt_temp_c', merged.melt_temp_c],
              ['hdt_045_mpa_c', merged.hdt_045_mpa_c],
              ['vicat_softening_temp_c', merged.vicat_softening_temp_c],
              ['water_absorption_percent', merged.water_absorption_percent],
              // Product line grouping
              ['product_line_id', merged.product_line_id],
            ];
            for (const [field, value] of enrichmentFields) {
              if (value != null) priceUpdate[field] = value;
            }

            const { error: updateErr } = await supabase
              .from('filaments')
              .update(priceUpdate)
              .eq('id', item.existing_filament_id);

            if (updateErr) throw new Error(`Update failed: ${updateErr.message}`);

            // Mark sync item as imported
            await supabase
              .from('brand_sync_items')
              .update({ status: 'imported', inserted_filament_id: item.existing_filament_id })
              .eq('id', item.id);

            insertedFilaments.push({ id: item.existing_filament_id, itemId: item.id, data: merged });
            updatedPrices++;
            console.log(`[import] ✏️ Updated prices: ${item.display_name}`);
          } else {
            // INSERT new filament
            const { data: filament, error: insertErr } = await supabase
              .from('filaments')
              .insert({
                vendor: merged.vendor ?? brandName,
                brand_id: brandId,
                material: merged.material ?? item.material_type,
                product_title: merged.product_title ?? item.display_name,
                display_name: merged.display_name ?? item.display_name,
                color_family: merged.color_family ?? item.color_family,
                color_hex: merged.color_hex ?? item.color_hex,
                featured_image: merged.featured_image ?? item.image_url,
                variant_image: merged.variant_image ?? item.variant_image_url,
                nozzle_temp_min_c: merged.nozzle_temp_min_c,
                nozzle_temp_max_c: merged.nozzle_temp_max_c,
                bed_temp_min_c: merged.bed_temp_min_c,
                bed_temp_max_c: merged.bed_temp_max_c,
                diameter_nominal_mm: merged.diameter_nominal_mm ?? 1.75,
                diameter_is_assumed: merged.diameter_nominal_mm == null,
                net_weight_g: merged.net_weight_g,
                product_url: merged.product_url ?? merged.product_url_us,
                product_url_eu: merged.product_url_eu,
                product_url_uk: merged.product_url_uk,
                product_url_ca: merged.product_url_ca,
                product_url_au: merged.product_url_au,
                product_url_jp: merged.product_url_jp,
                variant_price: merged.price_usd,
                price_eur: merged.price_eur,
                price_gbp: merged.price_gbp,
                price_cad: merged.price_cad,
                price_aud: merged.price_aud,
                price_jpy: merged.price_jpy,
                price_cny: merged.price_cny,
                product_handle: merged.product_handle ?? item.product_handle,
                variant_sku: merged.variant_sku ?? item.variant_sku,
                finish_type: merged.finish_type ?? item.finish_type,
                spool_material: merged.spool_material,
                spool_outer_d_mm: merged.spool_outer_d_mm,
                spool_width_mm: merged.spool_width_mm,
                pack_quantity: merged.pack_quantity ?? 1,
                print_speed_max_mms: merged.print_speed_max_mms,
                high_speed_capable: merged.high_speed_capable,
                drying_temp_c: merged.drying_temp_c,
                drying_time_hours: merged.drying_time_hours,
                td: merged.td_value ?? merged.td,
                variant_available: merged.variant_available ?? true,
                available_regions: merged.available_regions ?? item.available_regions,
                // Enrichment fields
                tg_c: merged.tg_c,
                moisture_sensitivity_level: merged.moisture_sensitivity_level,
                is_nozzle_abrasive: merged.is_nozzle_abrasive,
                recommended_nozzle_type: merged.recommended_nozzle_type,
                fan_min_percent: merged.fan_min_percent,
                fan_max_percent: merged.fan_max_percent,
                density_g_cm3: merged.density_g_cm3,
                nozzle_temp_sweetspot_c: merged.nozzle_temp_sweetspot_c,
                use_case_tags: merged.use_case_tags,
                food_contact_rating: merged.food_contact_rating,
                retraction_length_mm: merged.retraction_length_mm,
                retraction_speed_mms: merged.retraction_speed_mms,
                spool_ams_fit: merged.spool_ams_fit,
                tds_url: merged.tds_url,
                // Mechanical properties
                tensile_strength_xy_mpa: merged.tensile_strength_xy_mpa,
                elongation_break_xy_percent: merged.elongation_break_xy_percent,
                flexural_strength_mpa: merged.flexural_strength_mpa,
                impact_strength_kj_m2: merged.impact_strength_kj_m2,
                shore_hardness_d: merged.shore_hardness_d,
                hardness_shore_a: merged.hardness_shore_a,
                // Thermal properties
                melt_temp_c: merged.melt_temp_c,
                hdt_045_mpa_c: merged.hdt_045_mpa_c,
                vicat_softening_temp_c: merged.vicat_softening_temp_c,
                water_absorption_percent: merged.water_absorption_percent,
                // Product line grouping
                product_line_id: merged.product_line_id,
                sync_source: 'catalog-sync-client',
                auto_created: true,
              })
              .select('id')
              .single();

            if (insertErr) throw new Error(`Insert failed: ${insertErr.message}`);

            // Mark sync item as imported
            await supabase
              .from('brand_sync_items')
              .update({ status: 'imported', inserted_filament_id: filament?.id })
              .eq('id', item.id);

            insertedFilaments.push({ id: filament!.id, itemId: item.id, data: merged });
            insertedCount++;
            console.log(`[import] ✅ Inserted: ${item.display_name} → ${filament!.id}`);
          }
        } catch (err: any) {
          errorCount++;
          const classified = classifyImportError(
            item.display_name,
            item.id,
            err.message,
            item.status === 'price_changed' ? 'update' : 'insert',
            item.existing_filament_id || undefined,
          );
          importErrorDetails.push(classified);
          console.error(`[import] ❌ [${classified.severity}] ${item.display_name}: ${err.message}`);

          await supabase
            .from('brand_sync_items')
            .update({ status: 'error', error_message: err.message })
            .eq('id', item.id);
        }
      }

      console.log(`[import] Done: ${insertedCount} inserted, ${updatedPrices} updated, ${errorCount} errors`);

      // ── STEP 3: Price History ──
      let priceHistoryCount = 0;
      const postErrors: string[] = [];

      try {
        const regionMap = [
          { field: 'price_usd', altField: 'variant_price', region: 'US' },
          { field: 'price_cad', region: 'CA' },
          { field: 'price_eur', region: 'EU' },
          { field: 'price_gbp', region: 'UK' },
          { field: 'price_aud', region: 'AU' },
          { field: 'price_jpy', region: 'JP' },
          { field: 'price_cny', region: 'CN' },
        ];

        const priceRows: Array<{ filament_id: string; price: number; region: string; source: string }> = [];

        for (const fil of insertedFilaments) {
          for (const { field, altField, region } of regionMap) {
            const price = fil.data[field] ?? (altField ? fil.data[altField] : null);
            if (price != null && price > 0) {
              priceRows.push({
                filament_id: fil.id,
                price,
                region,
                source: 'catalog_sync_import',
              });
            }
          }
        }

        if (priceRows.length > 0) {
          for (let i = 0; i < priceRows.length; i += 200) {
            const chunk = priceRows.slice(i, i + 200);
            const { error: phErr } = await supabase.from('price_history').insert(chunk);
            if (phErr) {
              postErrors.push(`Price history batch ${i}: ${phErr.message}`);
              importErrorDetails.push(classifyImportError(
                `Price history batch ${Math.floor(i / 200) + 1}`,
                '',
                phErr.message,
                'price-history',
              ));
            } else {
              priceHistoryCount += chunk.length;
            }
          }
        }
        console.log(`[import] 📊 ${priceHistoryCount} price history records created`);
      } catch (e: any) {
        postErrors.push(`Price history: ${e.message}`);
        importErrorDetails.push(classifyImportError(
          'Price history',
          '',
          e.message,
          'price-history',
        ));
      }

      // ── STEP 4: Data Quality Scores ──
      let totalQuality = 0;
      for (const fil of insertedFilaments) {
        let score = 0;
        const d = fil.data;
        // Core fields (80 points max)
        if (d.display_name) score += 12;
        if (d.color_hex && d.color_hex !== '#808080') score += 12;
        if (d.color_family) score += 8;
        if (d.material) score += 8;
        if (d.price_usd || d.variant_price) score += 12;
        if (d.featured_image) score += 8;
        if (d.nozzle_temp_min_c || d.nozzle_temp_max_c) score += 8;
        if (d.variant_sku) score += 4;
        if (d.product_url || d.product_url_us) score += 4;
        if (d.net_weight_g) score += 4;
        // Enrichment fields (20 points max)
        if (d.drying_temp_c) score += 3;
        if (d.tg_c) score += 3;
        if (d.density_g_cm3) score += 3;
        if (d.moisture_sensitivity_level) score += 3;
        if (d.fan_min_percent != null || d.fan_max_percent != null) score += 3;
        if (d.use_case_tags?.length > 0) score += 3;
        if (d.is_nozzle_abrasive != null) score += 2;
        if (d.tensile_strength_xy_mpa) score += 1;
        if (d.impact_strength_kj_m2) score += 1;
        if (d.melt_temp_c) score += 1;
        totalQuality += Math.min(score, 100);
      }
      const avgQuality = insertedFilaments.length > 0
        ? Math.round(totalQuality / insertedFilaments.length)
        : 0;

      // ── STEP 5: Update Job ──
      const postImportResults = {
        price_history_count: priceHistoryCount,
        urls_validated: 0, // Skip URL validation client-side (CORS limitations)
        urls_broken: [] as string[],
        avg_quality_score: avgQuality,
        errors: postErrors,
        completed_at: new Date().toISOString(),
      };

      await supabase
        .from('brand_sync_jobs')
        .update({
          imported_count: insertedCount + updatedPrices,
          post_import_results: postImportResults,
        })
        .eq('id', jobId);

      console.log(`[import] ✅ Job ${jobId} updated with post-import results`);

      setImportResult({
        imported: insertedCount,
        updatedPrices,
        errors: errorCount,
        errorDetails: importErrorDetails,
        priceHistoryCount,
        avgQualityScore: avgQuality,
        urlsBroken: [],
      });

      setPhase('complete');
    } catch (err: any) {
      const msg = err.message || 'Import failed';
      console.error('[import] Fatal error:', msg);
      setError(msg);
      // Stay on importing phase so user can retry
    } finally {
      setImporting(false);
    }
  }, [jobId]);

  // ── Reset ──

  // ── Retry a failed import item ──
  const retryFailedItem = useCallback(async (errorItem: ImportError): Promise<boolean> => {
    try {
      if (errorItem.resolutionType === 'auto-retry-update') {
        // Try to find the existing filament by product_handle match and update its prices
        const { data: syncItem } = await supabase
          .from('brand_sync_items')
          .select('*')
          .eq('id', errorItem.syncItemId)
          .single();

        if (!syncItem) return false;

        const extracted = (syncItem.extracted_data || {}) as Record<string, any>;
        const overrides = (syncItem.admin_override_data || {}) as Record<string, any>;
        const merged = { ...extracted, ...overrides };

        // Find existing filament by handle or SKU
        let existingId = errorItem.existingFilamentId || syncItem.existing_filament_id;
        if (!existingId) {
          const { data: existing } = await supabase
            .from('filaments')
            .select('id')
            .eq('product_handle', syncItem.product_handle)
            .limit(1)
            .maybeSingle();
          existingId = existing?.id;
        }

        if (existingId) {
          // UPDATE existing
          const priceUpdate: Record<string, any> = {
            updated_at: new Date().toISOString(),
            last_scraped_at: new Date().toISOString(),
          };
          if (merged.price_usd != null) priceUpdate.variant_price = merged.price_usd;
          if (merged.price_eur != null) priceUpdate.price_eur = merged.price_eur;
          if (merged.price_gbp != null) priceUpdate.price_gbp = merged.price_gbp;
          if (merged.price_cad != null) priceUpdate.price_cad = merged.price_cad;
          if (merged.price_aud != null) priceUpdate.price_aud = merged.price_aud;
          if (merged.price_jpy != null) priceUpdate.price_jpy = merged.price_jpy;
          if (merged.price_cny != null) priceUpdate.price_cny = merged.price_cny;
          if (merged.variant_available != null) priceUpdate.variant_available = merged.variant_available;

          const { error: updateErr } = await supabase
            .from('filaments')
            .update(priceUpdate)
            .eq('id', existingId);

          if (updateErr) return false;

          await supabase
            .from('brand_sync_items')
            .update({ status: 'imported', error_message: null, inserted_filament_id: existingId })
            .eq('id', errorItem.syncItemId);

          console.log(`[retry] ✅ Updated prices for: ${errorItem.displayName}`);
        } else {
          // No existing filament found — cannot retry as update
          return false;
        }
      } else if (errorItem.resolutionType === 'auto-retry-insert') {
        // Re-attempt the insert
        const { data: syncItem } = await supabase
          .from('brand_sync_items')
          .select('*')
          .eq('id', errorItem.syncItemId)
          .single();

        if (!syncItem) return false;

        const extracted = (syncItem.extracted_data || {}) as Record<string, any>;
        const overrides = (syncItem.admin_override_data || {}) as Record<string, any>;
        const merged = { ...extracted, ...overrides };

        const { data: filament, error: insertErr } = await supabase
          .from('filaments')
          .insert({
            vendor: merged.vendor,
            brand_id: merged.brand_id,
            material: merged.material ?? syncItem.material_type,
            product_title: merged.product_title ?? syncItem.display_name,
            display_name: merged.display_name ?? syncItem.display_name,
            color_family: merged.color_family ?? syncItem.color_family,
            color_hex: merged.color_hex ?? syncItem.color_hex,
            featured_image: merged.featured_image ?? syncItem.image_url,
            variant_image: merged.variant_image ?? syncItem.variant_image_url,
            diameter_nominal_mm: merged.diameter_nominal_mm ?? 1.75,
            variant_price: merged.price_usd,
            price_eur: merged.price_eur,
            product_handle: merged.product_handle ?? syncItem.product_handle,
            variant_sku: merged.variant_sku ?? syncItem.variant_sku,
            variant_available: merged.variant_available ?? true,
            sync_source: 'catalog-sync-retry',
            auto_created: true,
          })
          .select('id')
          .single();

        if (insertErr) return false;

        await supabase
          .from('brand_sync_items')
          .update({ status: 'imported', error_message: null, inserted_filament_id: filament?.id })
          .eq('id', errorItem.syncItemId);

        console.log(`[retry] ✅ Inserted: ${errorItem.displayName}`);
      } else {
        return false;
      }

      // Update local state: remove the fixed error from importResult
      setImportResult(prev => {
        if (!prev) return prev;
        const newDetails = prev.errorDetails.filter(e => e.itemId !== errorItem.itemId || e.message !== errorItem.message);
        const removedCritical = errorItem.severity === 'critical' ? 1 : 0;
        return {
          ...prev,
          errors: Math.max(0, prev.errors - removedCritical),
          errorDetails: newDetails,
          updatedPrices: errorItem.resolutionType === 'auto-retry-update'
            ? prev.updatedPrices + 1
            : prev.updatedPrices,
          imported: errorItem.resolutionType === 'auto-retry-insert'
            ? prev.imported + 1
            : prev.imported,
        };
      });

      return true;
    } catch (e) {
      console.error(`[retry] Failed:`, e);
      return false;
    }
  }, []);

  const reset = useCallback(() => {
    if (pollRef.current) clearInterval(pollRef.current);
    setPhase('select');
    setJobId(null);
    setScanJob(null);
    setItems([]);
    setImportResult(null);
    setError(null);
    setImporting(false);
  }, []);

  return {
    phase,
    jobId,
    scanJob,
    items,
    deltaStats,
    importResult,
    error,
    importing,
    scanStatusMessage,
    startScan,
    startImport,
    retryFailedItem,
    reset,
  };
}
