export interface BrandConfig {
  vendor: string;
  platform: "shopify" | "woocommerce" | "bigcommerce" | "amazon" | "firecrawl";
  baseUrl: string;
  apiEndpoint?: string;
  collectionHandle?: string;
  amazonStoreUrl?: string; // Amazon store URL for Amazon-only brands
  currency: string;
  exchangeRate: number; // To USD
  productsPerPage: number;
  requestDelay: number; // ms between requests
  timeout: number; // request timeout ms
  userAgent: string;
  productCount?: number;
}

const DEFAULT_USER_AGENT = "Mozilla/5.0 (compatible; FilaScope/1.0; +https://filascope.com)";

export const BRAND_CONFIGS: Record<string, BrandConfig> = {
  Hatchbox: {
    vendor: "Hatchbox",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 20,
    requestDelay: 2000, // Amazon needs slower rate
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 177,
  },
  Prusament: {
    vendor: "Prusament",
    platform: "shopify",
    baseUrl: "https://www.prusa3d.com",
    apiEndpoint: "https://www.prusa3d.com/product/prusament",
    collectionHandle: "prusament",
    currency: "EUR",
    exchangeRate: 1.08, // EUR to USD
    productsPerPage: 50,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 49,
  },
  "Overture 3D": {
    vendor: "Overture 3D",
    platform: "woocommerce",
    baseUrl: "https://overture3d.com",
    apiEndpoint: "https://overture3d.com/wp-json/wc/store/v1/products",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 100,
    requestDelay: 1000,
    timeout: 15000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 135,
  },
  "3D-Fuel": {
    vendor: "3D-Fuel",
    platform: "shopify",
    baseUrl: "https://www.3dfuel.com",
    apiEndpoint: "https://www.3dfuel.com/products.json",
    collectionHandle: "filament",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 78,
  },
  "3DXTech": {
    vendor: "3DXTech",
    platform: "bigcommerce",
    baseUrl: "https://www.3dxtech.com",
    apiEndpoint: "https://www.3dxtech.com/filament/",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 36,
    requestDelay: 1000,
    timeout: 15000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 198,
  },
  Fillamentum: {
    vendor: "Fillamentum",
    platform: "shopify",
    baseUrl: "https://fillamentum.com",
    apiEndpoint: "https://fillamentum.com/products.json",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 190,
  },
  Matter3D: {
    vendor: "Matter3D",
    platform: "shopify",
    baseUrl: "https://www.matter3d.com",
    apiEndpoint: "https://www.matter3d.com/products.json",
    currency: "CAD",
    exchangeRate: 0.74,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 102,
  },
  Sunlu: {
    vendor: "Sunlu",
    platform: "shopify",
    // Note: store.sunlu.com is the correct storefront, not www.sunlu.com
    baseUrl: "https://store.sunlu.com",
    apiEndpoint: "https://store.sunlu.com/products.json",
    collectionHandle: "3d-printer-filament",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 55,
  },
  Polymaker: {
    vendor: "Polymaker",
    platform: "shopify",
    baseUrl: "https://us.polymaker.com",
    apiEndpoint: "https://us.polymaker.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 46,
  },
  "Bambu Lab": {
    vendor: "Bambu Lab",
    platform: "shopify",
    baseUrl: "https://us.store.bambulab.com",
    apiEndpoint: "https://us.store.bambulab.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 29,
  },
  Amolen: {
    vendor: "Amolen",
    platform: "shopify",
    baseUrl: "https://amolen.com",
    apiEndpoint: "https://amolen.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 26,
  },
  "Siraya Tech": {
    vendor: "Siraya Tech",
    platform: "shopify",
    baseUrl: "https://siraya.tech",
    apiEndpoint: "https://siraya.tech/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 19,
  },
  eSun: {
    vendor: "eSun",
    platform: "shopify",
    baseUrl: "https://www.esun3dstore.com",
    apiEndpoint: "https://www.esun3dstore.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 18,
  },
  Eryone: {
    vendor: "Eryone",
    platform: "shopify",
    baseUrl: "https://eryone3d.com",
    apiEndpoint: "https://eryone3d.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 17,
  },
  "Atomic Filament": {
    vendor: "Atomic Filament",
    platform: "shopify",
    baseUrl: "https://atomicfilament.com",
    apiEndpoint: "https://atomicfilament.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 16,
  },
  "Proto-Pasta": {
    vendor: "Proto-Pasta",
    platform: "shopify",
    baseUrl: "https://www.proto-pasta.com",
    apiEndpoint: "https://www.proto-pasta.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 15,
  },
  VoxelPLA: {
    vendor: "VoxelPLA",
    platform: "shopify",
    baseUrl: "https://voxelpla.com",
    apiEndpoint: "https://voxelpla.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 8,
  },
  NinjaTek: {
    vendor: "NinjaTek",
    platform: "woocommerce", // Fixed: Was shopify, but NinjaTek uses WooCommerce
    baseUrl: "https://ninjatek.com",
    apiEndpoint: "https://ninjatek.com/wp-json/wc/store/v1/products",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 100,
    requestDelay: 1000,
    timeout: 15000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 8,
  },
  ColorFabb: {
    vendor: "ColorFabb",
    platform: "shopify",
    baseUrl: "https://colorfabb.com",
    apiEndpoint: "https://colorfabb.com/products.json",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 32,
  },
  Fiberlogy: {
    vendor: "Fiberlogy",
    platform: "shopify",
    baseUrl: "https://fiberlogy.com",
    apiEndpoint: "https://fiberlogy.com/products.json",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 15,
  },
  Ultimaker: {
    vendor: "Ultimaker",
    platform: "shopify",
    baseUrl: "https://store.ultimaker.com",
    apiEndpoint: "https://store.ultimaker.com/products.json",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 14,
  },
  "Printed Solid": {
    vendor: "Printed Solid",
    platform: "shopify",
    baseUrl: "https://www.printedsolid.com",
    apiEndpoint: "https://www.printedsolid.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 10,
  },
  "Push Plastic": {
    vendor: "Push Plastic",
    platform: "shopify",
    baseUrl: "https://www.pushplastic.com",
    apiEndpoint: "https://www.pushplastic.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 80,
  },
  "Fusion Filaments": {
    vendor: "Fusion Filaments",
    platform: "firecrawl", // Odoo platform - use Firecrawl HTML scraping
    baseUrl: "https://www.fusionfilaments.com/shop",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 40,
  },
  // Amazon-based brands (use amazon_link_us column)
  Ziro: {
    vendor: "Ziro",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 15,
  },
  "Paramount 3D": {
    vendor: "Paramount 3D",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 12,
  },
  Inland: {
    vendor: "Inland",
    platform: "amazon", // Switched to Amazon - Microcenter site too complex to scrape
    baseUrl: "https://www.amazon.com",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 50,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 16,
  },
  // Shopify via reseller (3DmakerWorld)
  Taulman3D: {
    vendor: "Taulman3D",
    platform: "shopify",
    baseUrl: "https://3dmakerworld.com",
    apiEndpoint: "https://3dmakerworld.com/products.json",
    collectionHandle: "taulman",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 6,
  },
  // Firecrawl-based scrapers (custom platforms)
  FormFutura: {
    vendor: "FormFutura",
    platform: "firecrawl",
    baseUrl: "https://www.formfutura.com/shop/product/3d-printing-filament",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 79,
  },
  MatterHackers: {
    vendor: "MatterHackers",
    platform: "firecrawl",
    baseUrl: "https://www.matterhackers.com",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 37,
  },
  // ============================================================================
  // NEW DISCOVERY BRANDS (Shopify Wave 2)
  // ============================================================================
  Recreus: {
    vendor: "Recreus",
    platform: "shopify",
    baseUrl: "https://recreus.com",
    apiEndpoint: "https://recreus.com/products.json",
    collectionHandle: "filaflex", // Fixed: Use filaflex collection for TPU filaments
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 45,
  },
  "TreeD Filaments": {
    vendor: "TreeD Filaments",
    platform: "firecrawl", // WooCommerce API disabled - use Firecrawl
    baseUrl: "https://treedfilaments.com/shop/",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 70,
  },
  Extrudr: {
    vendor: "Extrudr",
    platform: "firecrawl",
    baseUrl: "https://www.extrudr.com/en/inlt/",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 90,
  },
  "Spectrum Filaments": {
    vendor: "Spectrum Filaments",
    platform: "firecrawl",
    baseUrl: "https://shop.spectrumfilaments.com/en/",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 85,
  },
  "Devil Design": {
    vendor: "Devil Design",
    platform: "firecrawl",
    baseUrl: "https://devildesign.com/en/shop/",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 95,
  },
  "Rigid.ink": {
    vendor: "Rigid.ink",
    platform: "firecrawl",
    baseUrl: "https://rigid.ink/collections/all",
    currency: "GBP",
    exchangeRate: 1.27,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 50,
  },
  // ============================================================================
  // FIRECRAWL BRANDS - Custom E-Commerce Platforms
  // ============================================================================
  GEEETECH: {
    vendor: "GEEETECH",
    platform: "firecrawl",
    baseUrl: "https://www.geeetech.com/filament-c-83.html",
    apiEndpoint: "",
    currency: "USD",
    exchangeRate: 1.0,
    productsPerPage: 100,
    requestDelay: 1500,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 100,
  },
  // ============================================================================
  // AMAZON WAVE 2 - Discovery Brands
  // ============================================================================
  TECBEARS: {
    vendor: "TECBEARS",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    amazonStoreUrl: "https://www.amazon.com/stores/TECBEARS/page/A86FC7C4-D19A-4F4D-B7B9-E7FBF9E0F7FA",
    currency: "USD",
    exchangeRate: 1.0,
    productsPerPage: 50,
    requestDelay: 2000,
    timeout: 30000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 100,
  },
  TTYT3D: {
    vendor: "TTYT3D",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    apiEndpoint: "",
    currency: "USD",
    exchangeRate: 1.0,
    productsPerPage: 50,
    requestDelay: 2000,
    timeout: 15000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 35,
  },
  "3D Solutech": {
    vendor: "3D Solutech",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    apiEndpoint: "",
    currency: "USD",
    exchangeRate: 1.0,
    productsPerPage: 50,
    requestDelay: 2000,
    timeout: 15000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 70,
  },
  "Gizmo Dorks": {
    vendor: "Gizmo Dorks",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    apiEndpoint: "",
    currency: "USD",
    exchangeRate: 1.0,
    productsPerPage: 50,
    requestDelay: 2000,
    timeout: 15000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 60,
  },
  PRILINE: {
    vendor: "PRILINE",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    apiEndpoint: "",
    currency: "USD",
    exchangeRate: 1.0,
    productsPerPage: 50,
    requestDelay: 2000,
    timeout: 15000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 50,
  },
  Elegoo: {
    vendor: "Elegoo",
    platform: "shopify",
    baseUrl: "https://us.elegoo.com",
    apiEndpoint: "https://us.elegoo.com/products.json",
    collectionHandle: "filaments",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 20,
  },
  // ============================================================================
  // GROUP 1: MAJOR MANUFACTURERS - NEW ADDITIONS
  // ============================================================================
  Creality: {
    vendor: "Creality",
    platform: "firecrawl", // Custom Vue.js frontend blocks JSON API - use Firecrawl
    baseUrl: "https://store.creality.com/collections/filament",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 19,
  },
  Anycubic: {
    vendor: "Anycubic",
    platform: "shopify",
    baseUrl: "https://store.anycubic.com",
    apiEndpoint: "https://store.anycubic.com/products.json",
    collectionHandle: "all", // Changed from "filament" - filament collection doesn't exist
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 30,
  },
  Flashforge: {
    vendor: "Flashforge",
    platform: "shopify",
    baseUrl: "https://www.flashforgeshop.com",
    apiEndpoint: "https://www.flashforgeshop.com/products.json",
    collectionHandle: "filament",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 25,
  },
  // ============================================================================
  // GROUP 2: SPECIALTY & AMAZON - NEW ADDITIONS
  // ============================================================================
  "Amazon Basics": {
    vendor: "Amazon Basics",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    apiEndpoint: "",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 50,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 50,
  },
  Kingroon: {
    vendor: "Kingroon",
    platform: "shopify",
    baseUrl: "https://kingroon.com",
    apiEndpoint: "https://kingroon.com/products.json",
    collectionHandle: "3d-printer-filament", // Fixed: Correct collection with 40+ products
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 40,
  },
  "IIID Max": {
    vendor: "IIID Max",
    platform: "shopify",
    baseUrl: "https://iiidmax.com",
    apiEndpoint: "https://iiidmax.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 50,
  },
  SainSmart: {
    vendor: "SainSmart",
    platform: "shopify",
    baseUrl: "https://www.sainsmart.com",
    apiEndpoint: "https://www.sainsmart.com/products.json",
    // No collectionHandle - use general products.json, scraper will filter for filament products
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 80,
  },
  "IC3D Printers": {
    vendor: "IC3D Printers",
    platform: "firecrawl", // Fixed: WooCommerce Store API disabled, needs HTML scraping
    baseUrl: "https://www.ic3dprinters.com/shop/",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 50,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 50,
  },
  Jayo: {
    vendor: "Jayo",
    platform: "shopify",
    baseUrl: "https://jayo3d.com",
    apiEndpoint: "https://jayo3d.com/products.json",
    collectionHandle: "filament",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 100,
  },
  "3DHOJOR": {
    vendor: "3DHOJOR",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    apiEndpoint: "",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 50,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 30,
  },
  "Duramic 3D": {
    vendor: "Duramic 3D",
    platform: "shopify",
    baseUrl: "https://duramic3d.com",
    apiEndpoint: "https://duramic3d.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 60,
  },
  // ============================================================================
  // GROUP 3: INTERNATIONAL & NICHE - NEW ADDITIONS
  // ============================================================================
  Dikale: {
    vendor: "Dikale",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    apiEndpoint: "",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 50,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 20,
  },
  Sovol: {
    vendor: "Sovol",
    platform: "shopify",
    baseUrl: "https://www.sovol3d.com",
    apiEndpoint: "https://www.sovol3d.com/products.json",
    collectionHandle: "sovol-filaments",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 17,
  },
  Yousu: {
    vendor: "Yousu",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    apiEndpoint: "",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 50,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 25,
  },
  Numakers: {
    vendor: "Numakers",
    platform: "shopify",
    baseUrl: "https://numakers.com",
    apiEndpoint: "https://numakers.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 30,
  },
  AzureFilm: {
    vendor: "AzureFilm",
    platform: "woocommerce", // Changed to WooCommerce - azurefilm.com is WooCommerce
    baseUrl: "https://azurefilm.com",
    apiEndpoint: "https://azurefilm.com/wp-json/wc/store/v1/products",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 100,
    requestDelay: 1000,
    timeout: 15000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 100,
  },
  Giantarm: {
    vendor: "Giantarm",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    apiEndpoint: "",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 50,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 40,
  },
  GST3D: {
    vendor: "GST3D",
    platform: "shopify",
    baseUrl: "https://gst3d.eu",
    apiEndpoint: "https://gst3d.eu/products.json",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 40,
  },
  "Filaments.ca": {
    vendor: "Filaments.ca",
    platform: "shopify",
    baseUrl: "https://filaments.ca",
    apiEndpoint: "https://filaments.ca/products.json",
    // Shopify multi-currency returns USD to US-based requests (where edge function runs)
    currency: "USD",
    exchangeRate: 1.0,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 200,
  },
  "Recycling Fabrik": {
    vendor: "Recycling Fabrik",
    platform: "shopify",
    baseUrl: "https://recyclingfabrik.com",
    apiEndpoint: "https://recyclingfabrik.com/products.json",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 25,
  },
};

export function getBrandConfig(vendor: string): BrandConfig | null {
  return BRAND_CONFIGS[vendor] || null;
}

export function getAllBrandSlugs(): string[] {
  return Object.keys(BRAND_CONFIGS);
}
