export interface BrandConfig {
  vendor: string;
  platform: "shopify" | "woocommerce" | "bigcommerce" | "amazon" | "firecrawl";
  baseUrl: string;
  apiEndpoint?: string;
  collectionHandle?: string;
  currency: string;
  exchangeRate: number; // To USD
  productsPerPage: number;
  requestDelay: number; // ms between requests
  timeout: number; // request timeout ms
  userAgent: string;
  productCount?: number;
}

const DEFAULT_USER_AGENT = "Mozilla/5.0 (compatible; FilaScope/1.0; +https://filascope.com)";

export const BRAND_CONFIGS: Record<string, BrandConfig> = {
  Hatchbox: {
    vendor: "Hatchbox",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 20,
    requestDelay: 2000, // Amazon needs slower rate
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 177,
  },
  Prusament: {
    vendor: "Prusament",
    platform: "shopify",
    baseUrl: "https://www.prusa3d.com",
    apiEndpoint: "https://www.prusa3d.com/product/prusament",
    collectionHandle: "prusament",
    currency: "EUR",
    exchangeRate: 1.08, // EUR to USD
    productsPerPage: 50,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 49,
  },
  "Overture 3D": {
    vendor: "Overture 3D",
    platform: "woocommerce",
    baseUrl: "https://overture3d.com",
    apiEndpoint: "https://overture3d.com/wp-json/wc/store/v1/products",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 100,
    requestDelay: 1000,
    timeout: 15000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 135,
  },
  "3D-Fuel": {
    vendor: "3D-Fuel",
    platform: "shopify",
    baseUrl: "https://www.3dfuel.com",
    apiEndpoint: "https://www.3dfuel.com/products.json",
    collectionHandle: "filament",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 78,
  },
  "3DXTech": {
    vendor: "3DXTech",
    platform: "bigcommerce",
    baseUrl: "https://www.3dxtech.com",
    apiEndpoint: "https://www.3dxtech.com/filament/",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 36,
    requestDelay: 1000,
    timeout: 15000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 198,
  },
  Fillamentum: {
    vendor: "Fillamentum",
    platform: "shopify",
    baseUrl: "https://fillamentum.com",
    apiEndpoint: "https://fillamentum.com/products.json",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 190,
  },
  Matter3D: {
    vendor: "Matter3D",
    platform: "shopify",
    baseUrl: "https://www.matter3d.com",
    apiEndpoint: "https://www.matter3d.com/products.json",
    currency: "CAD",
    exchangeRate: 0.74,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 102,
  },
  Sunlu: {
    vendor: "Sunlu",
    platform: "shopify",
    baseUrl: "https://www.sunlu.com",
    apiEndpoint: "https://www.sunlu.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 84,
  },
  Polymaker: {
    vendor: "Polymaker",
    platform: "shopify",
    baseUrl: "https://us.polymaker.com",
    apiEndpoint: "https://us.polymaker.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 46,
  },
  "Bambu Lab": {
    vendor: "Bambu Lab",
    platform: "shopify",
    baseUrl: "https://us.store.bambulab.com",
    apiEndpoint: "https://us.store.bambulab.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 29,
  },
  Amolen: {
    vendor: "Amolen",
    platform: "shopify",
    baseUrl: "https://amolen.com",
    apiEndpoint: "https://amolen.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 26,
  },
  "Siraya Tech": {
    vendor: "Siraya Tech",
    platform: "shopify",
    baseUrl: "https://siraya.tech",
    apiEndpoint: "https://siraya.tech/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 19,
  },
  eSun: {
    vendor: "eSun",
    platform: "shopify",
    baseUrl: "https://www.esun3d.com",
    apiEndpoint: "https://www.esun3d.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 18,
  },
  Eryone: {
    vendor: "Eryone",
    platform: "shopify",
    baseUrl: "https://eryone3d.com",
    apiEndpoint: "https://eryone3d.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 17,
  },
  "Atomic Filament": {
    vendor: "Atomic Filament",
    platform: "shopify",
    baseUrl: "https://atomicfilament.com",
    apiEndpoint: "https://atomicfilament.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 16,
  },
  "Proto-Pasta": {
    vendor: "Proto-Pasta",
    platform: "shopify",
    baseUrl: "https://www.proto-pasta.com",
    apiEndpoint: "https://www.proto-pasta.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 15,
  },
  VoxelPLA: {
    vendor: "VoxelPLA",
    platform: "shopify",
    baseUrl: "https://voxelpla.com",
    apiEndpoint: "https://voxelpla.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 8,
  },
  NinjaTek: {
    vendor: "NinjaTek",
    platform: "shopify",
    baseUrl: "https://ninjatek.com",
    apiEndpoint: "https://ninjatek.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 6,
  },
  ColorFabb: {
    vendor: "ColorFabb",
    platform: "shopify",
    baseUrl: "https://colorfabb.com",
    apiEndpoint: "https://colorfabb.com/products.json",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 32,
  },
  Fiberlogy: {
    vendor: "Fiberlogy",
    platform: "shopify",
    baseUrl: "https://fiberlogy.com",
    apiEndpoint: "https://fiberlogy.com/products.json",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 15,
  },
  Ultimaker: {
    vendor: "Ultimaker",
    platform: "shopify",
    baseUrl: "https://store.ultimaker.com",
    apiEndpoint: "https://store.ultimaker.com/products.json",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 14,
  },
  "Printed Solid": {
    vendor: "Printed Solid",
    platform: "shopify",
    baseUrl: "https://www.printedsolid.com",
    apiEndpoint: "https://www.printedsolid.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 10,
  },
  "Push Plastic": {
    vendor: "Push Plastic",
    platform: "shopify",
    baseUrl: "https://www.pushplastic.com",
    apiEndpoint: "https://www.pushplastic.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 80,
  },
  "Fusion Filaments": {
    vendor: "Fusion Filaments",
    platform: "shopify",
    baseUrl: "https://fusionfilaments.com",
    apiEndpoint: "https://fusionfilaments.com/products.json",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 40,
  },
  // Amazon-based brands (use amazon_link_us column)
  Ziro: {
    vendor: "Ziro",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 15,
  },
  "Paramount 3D": {
    vendor: "Paramount 3D",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 12,
  },
  Inland: {
    vendor: "Inland",
    platform: "amazon",
    baseUrl: "https://www.amazon.com",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 16,
  },
  // Shopify via reseller (3DmakerWorld)
  Taulman3D: {
    vendor: "Taulman3D",
    platform: "shopify",
    baseUrl: "https://3dmakerworld.com",
    apiEndpoint: "https://3dmakerworld.com/products.json",
    collectionHandle: "taulman",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 250,
    requestDelay: 500,
    timeout: 10000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 6,
  },
  // Firecrawl-based scrapers (custom platforms)
  FormFutura: {
    vendor: "FormFutura",
    platform: "firecrawl",
    baseUrl: "https://www.formfutura.com",
    currency: "EUR",
    exchangeRate: 1.08,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 19,
  },
  MatterHackers: {
    vendor: "MatterHackers",
    platform: "firecrawl",
    baseUrl: "https://www.matterhackers.com",
    currency: "USD",
    exchangeRate: 1,
    productsPerPage: 20,
    requestDelay: 2000,
    timeout: 20000,
    userAgent: DEFAULT_USER_AGENT,
    productCount: 37,
  },
};

export function getBrandConfig(vendor: string): BrandConfig | null {
  return BRAND_CONFIGS[vendor] || null;
}

export function getAllBrandSlugs(): string[] {
  return Object.keys(BRAND_CONFIGS);
}
