import { useState } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Download, FileText, FileSpreadsheet, Printer, Loader2, Database } from 'lucide-react';
import { toast } from 'sonner';
import { formatAsPlainText, formatAsMarkdown, type PrintSettings } from '@/lib/settingsFormatters';
import { exportFilamentToFullCSV, FILAMENT_FIELD_MAPPINGS } from '@/lib/filamentExportUtils';
import { Database as SupabaseDB } from '@/integrations/supabase/types';

type Filament = SupabaseDB["public"]["Tables"]["filaments"]["Row"];

interface ExportOptionsModalProps {
  settings: PrintSettings;
  filamentImage?: string;
  trigger?: React.ReactNode;
  filament?: Filament;
}

export function ExportOptionsModal({ settings, filamentImage, trigger, filament }: ExportOptionsModalProps) {
  const [open, setOpen] = useState(false);
  const [exporting, setExporting] = useState<string | null>(null);

  const handleFullDataExport = () => {
    if (!filament) {
      toast.error('Filament data not available');
      return;
    }
    setExporting('fulldata');
    
    try {
      exportFilamentToFullCSV(filament);
      toast.success(`Exported all ${FILAMENT_FIELD_MAPPINGS.length} fields to CSV`);
    } catch (error) {
      toast.error('Failed to export data');
      console.error('Export error:', error);
    }
    
    setExporting(null);
  };

  const handlePDFExport = () => {
    setExporting('pdf');
    
    // Create a print-friendly HTML document
    const printContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${settings.filamentName} - Print Settings</title>
          <style>
            body { font-family: system-ui, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
            h1 { color: #0891b2; margin-bottom: 8px; }
            .meta { color: #666; margin-bottom: 24px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
            th { background: #f5f5f5; font-weight: 600; }
            .value { font-weight: 600; color: #0891b2; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #888; font-size: 12px; }
            .image { max-width: 200px; margin-bottom: 20px; }
          </style>
        </head>
        <body>
          ${filamentImage ? `<img src="${filamentImage}" class="image" alt="${settings.filamentName}" />` : ''}
          <h1>${settings.filamentName}</h1>
          <div class="meta">
            <p><strong>Material:</strong> ${settings.material} | <strong>Vendor:</strong> ${settings.vendor}</p>
            ${settings.printerName ? `<p><strong>Printer:</strong> ${settings.printerName}</p>` : ''}
          </div>
          <h2>Temperature Settings</h2>
          <table>
            <tr>
              <th>Setting</th>
              <th>Value</th>
              <th>Range</th>
            </tr>
            <tr>
              <td>Nozzle Temperature</td>
              <td class="value">${settings.nozzleTemp}°C</td>
              <td>${settings.nozzleTempMin && settings.nozzleTempMax ? `${settings.nozzleTempMin}-${settings.nozzleTempMax}°C` : '—'}</td>
            </tr>
            <tr>
              <td>Bed Temperature</td>
              <td class="value">${settings.bedTemp}°C</td>
              <td>${settings.bedTempMin && settings.bedTempMax ? `${settings.bedTempMin}-${settings.bedTempMax}°C` : '—'}</td>
            </tr>
            ${settings.chamberTemp ? `
            <tr>
              <td>Chamber Temperature</td>
              <td class="value">${settings.chamberTemp}°C</td>
              <td>—</td>
            </tr>
            ` : ''}
          </table>
          ${settings.printSpeed || settings.cooling !== undefined ? `
          <h2>Print Settings</h2>
          <table>
            <tr>
              <th>Setting</th>
              <th>Value</th>
            </tr>
            ${settings.printSpeed ? `<tr><td>Print Speed</td><td class="value">${settings.printSpeed} mm/s</td></tr>` : ''}
            ${settings.cooling !== undefined ? `<tr><td>Cooling</td><td class="value">${settings.cooling}%</td></tr>` : ''}
            ${settings.retraction ? `<tr><td>Retraction</td><td class="value">${settings.retraction}mm</td></tr>` : ''}
          </table>
          ` : ''}
          ${settings.dryingTemp ? `
          <h2>Drying Requirements</h2>
          <table>
            <tr><th>Setting</th><th>Value</th></tr>
            <tr><td>Temperature</td><td class="value">${settings.dryingTemp}°C</td></tr>
            ${settings.dryingTime ? `<tr><td>Duration</td><td class="value">${settings.dryingTime} hours</td></tr>` : ''}
          </table>
          ` : ''}
          <div class="footer">
            <p>Generated by FilaScope • ${new Date().toLocaleDateString()}</p>
          </div>
        </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.print();
    }
    
    setExporting(null);
    toast.success('PDF ready to save');
  };

  const handleCSVExport = () => {
    setExporting('csv');
    
    const rows = [
      ['Setting', 'Value', 'Unit', 'Min', 'Max'],
      ['Filament', settings.filamentName, '', '', ''],
      ['Material', settings.material, '', '', ''],
      ['Vendor', settings.vendor, '', '', ''],
      ['Printer', settings.printerName || '', '', '', ''],
      ['Nozzle Temperature', String(settings.nozzleTemp), '°C', String(settings.nozzleTempMin || ''), String(settings.nozzleTempMax || '')],
      ['Bed Temperature', String(settings.bedTemp), '°C', String(settings.bedTempMin || ''), String(settings.bedTempMax || '')],
      ['Chamber Temperature', String(settings.chamberTemp || ''), '°C', '', ''],
      ['Print Speed', String(settings.printSpeed || ''), 'mm/s', '', ''],
      ['Cooling', String(settings.cooling ?? ''), '%', '', ''],
      ['Retraction', String(settings.retraction || ''), 'mm', '', ''],
      ['Drying Temperature', String(settings.dryingTemp || ''), '°C', '', ''],
      ['Drying Time', String(settings.dryingTime || ''), 'hours', '', ''],
    ];

    const csv = rows.map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = `${settings.filamentName.replace(/[^a-z0-9]/gi, '_')}_settings.csv`;
    a.click();
    
    URL.revokeObjectURL(url);
    setExporting(null);
    toast.success('CSV downloaded');
  };

  const handleMarkdownExport = () => {
    setExporting('markdown');
    
    const markdown = formatAsMarkdown(settings);
    const blob = new Blob([markdown], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = `${settings.filamentName.replace(/[^a-z0-9]/gi, '_')}_settings.md`;
    a.click();
    
    URL.revokeObjectURL(url);
    setExporting(null);
    toast.success('Markdown file downloaded');
  };

  const handleTextExport = () => {
    setExporting('text');
    
    const text = formatAsPlainText(settings);
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    
    const a = document.createElement('a');
    a.href = url;
    a.download = `${settings.filamentName.replace(/[^a-z0-9]/gi, '_')}_settings.txt`;
    a.click();
    
    URL.revokeObjectURL(url);
    setExporting(null);
    toast.success('Text file downloaded');
  };

  const exportOptions = [
    ...(filament ? [{
      id: 'fulldata',
      icon: Database,
      label: 'Full Data Export',
      description: `All ${FILAMENT_FIELD_MAPPINGS.length} fields in CSV format`,
      onClick: handleFullDataExport,
    }] : []),
    {
      id: 'pdf',
      icon: Printer,
      label: 'PDF',
      description: 'Print-ready settings sheet',
      onClick: handlePDFExport,
    },
    {
      id: 'csv',
      icon: FileSpreadsheet,
      label: 'CSV',
      description: 'For Google Sheets / Excel',
      onClick: handleCSVExport,
    },
    {
      id: 'markdown',
      icon: FileText,
      label: 'Markdown',
      description: 'For documentation',
      onClick: handleMarkdownExport,
    },
    {
      id: 'text',
      icon: FileText,
      label: 'Plain Text',
      description: 'Simple text file',
      onClick: handleTextExport,
    },
  ];

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        {trigger || (
          <Button variant="outline" size="sm" className="gap-2">
            <Download className="h-4 w-4" />
            <span className="hidden sm:inline">Export</span>
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Download className="h-5 w-5 text-primary" />
            Export Settings
          </DialogTitle>
        </DialogHeader>

        <div className="grid gap-3 py-4">
          {exportOptions.map((option) => (
            <Button
              key={option.id}
              variant="outline"
              className="h-auto justify-start gap-4 p-4"
              onClick={option.onClick}
              disabled={exporting !== null}
            >
              {exporting === option.id ? (
                <Loader2 className="h-5 w-5 animate-spin text-primary" />
              ) : (
                <option.icon className="h-5 w-5 text-primary" />
              )}
              <div className="text-left">
                <div className="font-medium">{option.label}</div>
                <div className="text-sm text-muted-foreground">
                  {option.description}
                </div>
              </div>
            </Button>
          ))}
        </div>
      </DialogContent>
    </Dialog>
  );
}
