
-- Step A: Add commission_tiers column
ALTER TABLE affiliate_programs ADD COLUMN IF NOT EXISTS commission_tiers jsonb DEFAULT NULL;

-- Step B: Add source_parameter and source_value columns
ALTER TABLE affiliate_programs ADD COLUMN IF NOT EXISTS source_parameter text DEFAULT NULL;
ALTER TABLE affiliate_programs ADD COLUMN IF NOT EXISTS source_value text DEFAULT NULL;

-- Step C: Insert Creality affiliate program
INSERT INTO affiliate_programs (
  brand_name, region_code, affiliate_network, affiliate_id,
  referral_handle, account_email, portal_url, store_base_url,
  tracking_parameter, tracking_value, link_template,
  commission_rate, commission_type, commission_notes, commission_tiers,
  source_parameter, source_value,
  cookie_duration_hours, cart_persistence_days, attribution_model,
  payout_schedule, payout_method, payout_currency,
  deep_linking_supported, account_status, status_notes,
  is_active, program_notes
) VALUES (
  'Creality',
  'US',
  'Direct',
  '432793.sgEubTAk',
  NULL,
  'Admin@Filascope.com',
  'https://www.creality3dofficial.com/affiliate/dashboard',
  'https://www.creality3dofficial.com',
  'sca_ref',
  '432793.sgEubTAk',
  '{store_url}{path}?sca_ref={tracking_value}&source={source_value}',
  3.00,
  'percentage',
  'Tiered: 3% base, up to 10%. Monthly floating rate resets each month.',
  '[{"stage":1,"rate":3,"min_sales":1,"max_sales":3000,"label":"$1 – $3,000"},{"stage":2,"rate":5,"min_sales":3001,"max_sales":8000,"label":"$3,001 – $8,000"},{"stage":3,"rate":7,"min_sales":8001,"max_sales":15000,"label":"$8,001 – $15,000"},{"stage":4,"rate":8,"min_sales":15001,"max_sales":25000,"label":"$15,001 – $25,000"},{"stage":5,"rate":10,"min_sales":25001,"max_sales":null,"label":"Over $25,000"}]'::jsonb,
  'source',
  'filascope',
  NULL,
  NULL,
  'last_click',
  NULL,
  NULL,
  'USD',
  true,
  'active',
  NULL,
  true,
  'Standard Commission Program. Product-specific links can be generated by appending sca_ref parameter to any creality3dofficial.com product URL. The source parameter is optional but recommended for analytics. Commission tier resets monthly — higher volume in a single month unlocks better rates. Additional source values available: filascope-review, filascope-youtube, filascope-email.'
);

-- Step D: Insert discount code placeholder for Creality
INSERT INTO affiliate_discount_codes (
  program_id, code, is_assigned, is_active, assignment_notes, posting_restrictions
) VALUES (
  (SELECT id FROM affiliate_programs WHERE brand_name = 'Creality' AND region_code = 'US'),
  NULL,
  false,
  true,
  'No coupons currently assigned. Check the Affiliate Coupon section of the dashboard periodically for new codes.',
  NULL
);
